### ISSUE TITLE
[Feature Request] Azure OpenAI endpoint

### ISSUE THREAD

**Issue by sander110419** [Pythagora-io/gpt-pilot#10]
It would be great to be able to leverage Azure OpenAI services to get access to the gpt4-32k model.
Implementation should be relatively easy, if a developer can build this, I can supply testing credentials to help with the integration.

Right now I've tried several projects and all have errored out on too many tokens requested.

**Comment by klehmann** [comment]
Same here, would love to have Azure OpenAI support to use our gpt4-32k model. Just did my first test run and it stopped with "ValueError: Too many tokens in messages: 7980. Please try a different test.".

**Comment by zvone187** [comment]
You can do this quite easily. Just open llm_connection.py and change the openai URL (line `'https://api.openai.com/v1/chat/completions',`) as well as the model (line `'model': 'gpt-4',`). That should be enough to work.

**Comment by klehmann** [comment]
Yes, found it already, but it would be great to have this built-in (via environment variables) without the need to fork the project.

**Comment by zvone187** [comment]
Yea, exactly. I'll get that added to .env for sure. Btw, feel free to submit a PR if you make any changes on your local version that you think others would like

**Comment by sander110419** [comment]
I created a pull request, I tested it out and it's a lot easier with the 32k context size

**Comment by zvone187** [comment]
Merged
