### ISSUE TITLE
Steps of dev are recorded in the postgres, but main.py cant continue to develop normally

### ISSUE THREAD

**Issue by lhplol** [Pythagora-io/gpt-pilot#100]
I installed the postgres database, and the steps of my application are recorded in the database, but when I use commands to continue development, main.py will only enter the step where I describe my requirements. Please tell me how should I configure it so that the application can continue to develop normally?

![A0D9272C-FF1C-4ba8-8F1E-5B5BF207F55C](https://github.com/Pythagora-io/gpt-pilot/assets/36524051/788ac491-d441-4043-aabd-ae2067b36262)

////
(pilot-env) [lhp@localhost pilot]$ python main.py app_id=8b5ea0e5-25f7-4f16-8c1f-d7324cd66772 

------------------ LOADING PROJECT ----------------------
lhp20 (app_id=8b5ea0e5-25f7-4f16-8c1f-d7324cd66772)
--------------------------------------------------------------

? Describe your app in as many details as possible.                                                           
? How did GPT Pilot do? Were you able to create any app that works? Please write any feedback you have or just
 press ENTER to exit:  
(pilot-env) [lhp@localhost pilot]$ 
(pilot-env) [lhp@localhost pilot]$ python main.py app_id=8b5ea0e5-25f7-4f16-8c1f-d7324cd66772 step=12

------------------ LOADING PROJECT ----------------------
lhp20 (app_id=8b5ea0e5-25f7-4f16-8c1f-d7324cd66772)
--------------------------------------------------------------

Project_description already done for this app_id: 8b5ea0e5-25f7-4f16-8c1f-d7324cd66772. Moving to next step...
User_stories already done for this app_id: 8b5ea0e5-25f7-4f16-8c1f-d7324cd66772. Moving to next step...
Architecture already done for this app_id: 8b5ea0e5-25f7-4f16-8c1f-d7324cd66772. Moving to next step...
---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "/home/lhp/gpt-pilot/pilot/main.py", line 36, in <module>
    project.start()
  File "/home/lhp/gpt-pilot/pilot/helpers/Project.py", line 83, in start
    if self.args['step'] is not None and STEPS.index(self.args['step']) < STEPS.index('coding'):
ValueError: '12' is not in list
--------------------------------------------------
? How did GPT Pilot do? Were you able to create any app that works? Please write any feedback you have or just
 press ENTER to exit:  
(pilot-env) [lhp@localhost pilot]$ 
/////

**Comment by Umpire2018** [comment]
The available args are
```
STEPS = [
    'project_description',
    'user_stories',
    'user_tasks',
    'architecture',
    'development_planning',
    'environment_setup',
    'coding'
]
```

You need to use like
`python main.py app_id=8b5ea0e5-25f7-4f16-8c1f-d7324cd66772 step=project_description`

**Comment by lhplol** [comment]
> The available args are
> 
> ```
> STEPS = [
>     'project_description',
>     'user_stories',
>     'user_tasks',
>     'architecture',
>     'development_planning',
>     'environment_setup',
>     'coding'
> ]
> ```
> 
> You need to use like `python main.py app_id=8b5ea0e5-25f7-4f16-8c1f-d7324cd66772 step=project_description`

Thank you.I though "python main.py app_id=8b5ea0e5-25f7-4f16-8c1f-d7324cd66772" would continue from steps already exsist.I'll try

**Comment by Umpire2018** [comment]
> > The available args are
> > ```
> > STEPS = [
> >     'project_description',
> >     'user_stories',
> >     'user_tasks',
> >     'architecture',
> >     'development_planning',
> >     'environment_setup',
> >     'coding'
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You need to use like `python main.py app_id=8b5ea0e5-25f7-4f16-8c1f-d7324cd66772 step=project_description`
> 
> Thank you.I though "python main.py app_id=8b5ea0e5-25f7-4f16-8c1f-d7324cd66772" would continue from steps already exsist.I'll try “python main.py app_id=<ID_OF_THE_APP> skip_until_dev_step=<DEV_STEP>”

And this will lead you back to `project_description` which is a issue.

**Comment by lhplol** [comment]
> > > The available args are
> > > ```
> > > STEPS = [
> > >     'project_description',
> > >     'user_stories',
> > >     'user_tasks',
> > >     'architecture',
> > >     'development_planning',
> > >     'environment_setup',
> > >     'coding'
> > > ]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You need to use like `python main.py app_id=8b5ea0e5-25f7-4f16-8c1f-d7324cd66772 step=project_description`
> > 
> > 
> > Thank you.I though "python main.py app_id=8b5ea0e5-25f7-4f16-8c1f-d7324cd66772" would continue from steps already exsist.I'll try “python main.py app_id=<ID_OF_THE_APP> skip_until_dev_step=<DEV_STEP>”
> 
> And this will lead you back to `project_description` which is a issue.

I'm totally confused by：
     "python main.py app_id=8b5ea0e5-25f7-4f16-8c1f-d7324cd66772"
     "python main.py app_id=8b5ea0e5-25f7-4f16-8c1f-d7324cd66772 skip_until_dev_step=8"
this two command just lead me back to project_description，although：
      "python main.py app_id=8b5ea0e5-25f7-4f16-8c1f-d7324cd66772 step=coding"
do work，but users in other issue can flexibly jump to step like 20 or 30。
How can i do that? Please.Sincere thanks.

**Comment by Umpire2018** [comment]
> but users in other issue can flexibly jump to step like 20 or 30。

@lhplol Can you provide the issue link please?

First of all, this project is in an early stage, so things could go south. In my opinion, the developers may not have finished the relevant part of the code because I encountered the same issue with you.

In the code, even though you used the previous id, the code just reset current_step to PROJECT_DESCRIPTION.
```python
    def get_project_description(self):
        self.project.app = save_app(self.project.args)
        self.project.current_step = PROJECT_DESCRIPTION_STEP
```
All we can do is to stay tuned for the moment or welcome for PR. :)

**Comment by lhplol** [comment]
> > but users in other issue can flexibly jump to step like 20 or 30。
> 
> @lhplol Can you provide the issue link please?
> 
> First of all, this project is in an early stage, so things could go south. In my opinion, the developers may not have finished the relevant part of the code because I encountered the same issue with you.
> 
> In the code, even though you used the previous id, the code just reset current_step to PROJECT_DESCRIPTION.
> 
> ```python
>     def get_project_description(self):
>         self.project.app = save_app(self.project.args)
>         self.project.current_step = PROJECT_DESCRIPTION_STEP
> ```
> 
> All we can do is to stay tuned for the moment or welcome for PR. :)

In issue #1,another user said:
'If you want to start from a different dev_step then you run

Python main.py app_id=the_long_app_id_code dev_step=step_number

To find the Dev steps then look back through the console output and find the yellow/orange Dev step number. I often have to go back 10, 20 or 30+ Dev steps to get a working step to resume from.'
I think he may resume the work.
The interactive artificial intelligence open source project always excites me. I regard it as a way to realize my dream. I hope the author can improve the function of restoring progress. I pay tribute to you. Thank you.

**Comment by LeonOstrez** [comment]
should be fixed with https://github.com/Pythagora-io/gpt-pilot/pull/149
