### ISSUE TITLE
[Bug]: AttributeError: 'SpecWriter' object has no attribute 'telemetry'

### ISSUE THREAD

**Issue by data-science101** [Pythagora-io/gpt-pilot#1017]
### Version

Command-line (Python) version

### Operating System

MacOS

### What happened?

After inserting all prompts and confirming information with the agent, I get the following traceback:

[Pythagora] Stopping Pythagora due to error:

File `core/cli/main.py`, line 37, in run_project
    success = await orca.run()
File `core/agents/orchestrator.py`, line 67, in run
    response = await agent.run()
File `core/agents/spec_writer.py`, line 66, in run
    spec = await self.analyze_spec(spec)
File `core/agents/spec_writer.py`, line 128, in analyze_spec
    await self.telemetry.trace_code_event(
AttributeError: 'SpecWriter' object has no attribute 'telemetry'

Python 3.10.11 (built from source)

**Comment by littlejacky** [comment]
I encountered the same problem on Windows.

**Comment by LeonOstrez** [comment]
This issue should be resolved with https://github.com/Pythagora-io/gpt-pilot/commit/96cc7ee3b2c91afbd5671e1af0b8f81c41ab51b7
