### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by PNdlovu** [Pythagora-io/gpt-pilot#1037]
### Version

VisualStudio Code extension

### Operating System

Windows 10

### What happened?

 Code monkey seems to get stuck when updating any kind of file. this is the error code. This has happened with about 4 of my application. This mostly happens when the application  is over 70% . I have attempted to updated the code based on my research but it still fails to load code pilot.  
![pythagora](https://github.com/Pythagora-io/gpt-pilot/assets/19626320/c7b12451-fc1b-4cae-87d7-e65ac73b4143)

Stopping Pythagora due to error:

File `core/cli/main.py`, line 37, in run_project
    success = await orca.run()
File `core/agents/orchestrator.py`, line 67, in run
    response = await agent.run()
File `core/agents/code_monkey.py`, line 32, in run
    return await self.implement_changes()
File `core/agents/code_monkey.py`, line 63, in implement_changes
    user_feedback_qa = iterations[-1]["user_feedback_qa"]
KeyError: 'user_feedback_qa'

Please help, I cannot move on with development

**Comment by fishhead108** [comment]
Duplicate https://github.com/Pythagora-io/gpt-pilot/issues/1025

**Comment by aaronmrosenthal** [comment]
this killed me every which way today. wasted lots of tokens.
