### ISSUE TITLE
[Howto]:  Complete The New Step Six?

### ISSUE THREAD

**Issue by Real-Experienes** [Pythagora-io/gpt-pilot#1056]
### Version

Command-line (Python) version

### Operating System

Windows 11

### Your question

How is the new Step 6 supposed to be executed? Like which OS is the instruction for Step 6 for? 
"cp example-config.json config.json (create config.json file)" Is this instruction incomplete? 
"cp"??
"config.json"??

This is 1.) not working and 2.) confusing. Do I have to manually create a config.json file?

Any advice would be greatly appreciated.

**Comment by haddadnidal** [comment]
`cp example-config.json  config.json ` this command will create a new config.json which is a copy of example-config.json. 
the rest was text.

**Comment by Real-Experienes** [comment]
cp is not a recognized command
