### ISSUE TITLE
[Enhancement]: Update from Python 3.9 to something more current -- 3.12?

### ISSUE THREAD

**Issue by JeffreyPeacock** [Pythagora-io/gpt-pilot#1129]
### Version

Command-line (Python) version

### Suggestion

Requiring the app have such an outdated version of Python is a bit burdensome.  Yes, you can run it in a container, or you can install pyenv -- newer OSs don't even support  the install of 3.9 any more -- e.g., Ubuntu 22.04, 24.04 -- without cumbersome workarounds.  (A related bug will speak to a particular aspect of the 'burden'.)

**Comment by westonludeke** [comment]
Hey @JeffreyPeacock, you should be able to use any Python version from 3.9 - 3.12.

**Comment by JeffreyPeacock** [comment]
Hmmm.  Ok, thanks.  However I distinctly remember a file indicating 3.9 was a requirement.
