### ISSUE TITLE
[feature] Allow manual edits in development process

### ISSUE THREAD

**Issue by jonasdebeukelaer** [Pythagora-io/gpt-pilot#114]
It would be nice to be able to allow manual edits during the debugging process, as sometimes it's quicker to fix a typo manually than to have the llm figure it out.

I think currently this is not possible because the state of the code is saved to the db, and so the code is reset after manual edits?

---
Tangentially, it would be great to be able to save the code change events as git commits. This would solve the above issue, and we could regain some of the nice features we get with git development flow.

**Comment by nalbion** [comment]
I observed the other day that the system does pick up on manual changes

**Comment by LeonOstrez** [comment]
you should be able to add your changes and gpt-pilot picks up on them when continuing development. If you found a case where that doesn't work as intended please open an issue and provide some more details on it. Thank you

**Comment by jonasdebeukelaer** [comment]
Sorry not had much time to address this!

As linked by @nalbion, I think this was related to save/restore from db, as I was getting some errors when running which prob triggered this restore function. Looks like it's being sorted so happy to leave this one closed.
