### ISSUE TITLE
Issues with Unresolved References and the Need for Absolute Imports in the Project Structure

### ISSUE THREAD

**Issue by Umpire2018** [Pythagora-io/gpt-pilot#116]
```
gpt-pilot/
    pilot/
        const/
        main.py
        helpers/
            __init__.py
            Project.py
        database/
            __init__.py
            database.py
```
This is a preview of the current project structure. It is a modular directory structure that organizes code, promotes reusability, and facilitates scalability and testing. It enhances code maintenance, team collaboration, and overall project organization.

When starting the project in PyCharm and installing the requirements, i encountered numerous errors stating "Unresolved reference 'database'". ChatGPT suggests using relative imports to resolve this issue, but notes that one drawback of relative imports is that they cannot be used for module-level execution and require an absolute import path.

![image](https://github.com/Pythagora-io/gpt-pilot/assets/138990495/e0aaf176-3123-439c-aa34-c4e198185880)

Currently, I unable to proceed with debugging due to the aforementioned problem. 
If i made any mistakes or if i can open a pull request (PR) to switch to absolute import paths?
Additionally, i wonder if using `python -m gpt-pilot` to run the project can simplify the execution process and if it is possible to publish the project on PyPI after implementing the changes.

@nalbion @LeonOstrez Thanks in advance.

**Comment by nalbion** [comment]
- Right click on `pilot` and **Mark Directory as Sources Root**.
- Make sure that you've configured the project interpreter as the **venv** Python

**Comment by Umpire2018** [comment]
![image](https://github.com/Pythagora-io/gpt-pilot/assets/138990495/ea70f259-624e-4418-8d4e-6133d4c360cf)

I believe this will work.

But is it better for people to run `python -m gpt-pilot` or download it from pip?
