### ISSUE TITLE
Comparison to AutoGen

### ISSUE THREAD

**Issue by mnieber** [Pythagora-io/gpt-pilot#118]
I saw one of the videos, and it was really impressive. Making it very easy to run commands that ChatGPT suggests is a bit scary though, but okay, handle with care.

Yesterday I also saw an announcement of AutoGen by Microsoft. They seem to take a very similar approach. It would be interesting if you could also make a comparison to their product. I can imagine that with their immense resources, they are able to do certain things better, but that doesn't mean that GPT Pilot is not amazing. In any case, I would be interested in seeing a comparison.

**Comment by Umpire2018** [comment]
FYI
[Create Customized Software using Natural Language Idea (through LLM-powered Multi-Agent Collaboration)](https://github.com/OpenBMB/ChatDev/tree/main)

**Comment by nalbion** [comment]
I heard about AutoGen the other day. I don't think it's intended to be a tool that you'd _run_, expecting it to build a software project for you, but rather a _framework_ which something like GPT Pilot could (have) been based on.

https://www.microsoft.com/en-us/research/blog/autogen-enabling-next-generation-large-language-model-applications/

https://github.com/microsoft/autogen

Some of the code doesn't look all that advanced (or clear):

```python
def infer_lang(code):
    """infer the language for the code.
    TODO: make it robust.
    """
    if code.startswith("python ") or code.startswith("pip") or code.startswith("python3 "):
        return "sh"
    return "python"
```

**Comment by mnieber** [comment]
Thanks, I see the difference. If I have time, I'll play aroud with both.
