### ISSUE TITLE
end of `continue_development()`

### ISSUE THREAD

**Issue by nalbion** [Pythagora-io/gpt-pilot#137]
`continue_development()` calls `self.project.ask_for_human_intervention()`, provides "press "r" to run the app" but it's not clear how the user is supposed to proceed from here.

> Can you check if the app works please? Here is a description of what should be working: 
> You can test if the task was successfully implemented by running the app and checking if it's served on your local machine. 
> 
> Here's how you do it:
> 
> 1. Open a terminal/command prompt.
> 2. Using the terminal, navigate to the application's directory.
> 3. Run the command `npm run start`.
> 4. Open a web browser and go to `http://localhost:3000`.
> 
> You should see "Hello World" displayed. If so, then the task was implemented successfully.
>
> If you want to run the app, just type "r" and press ENTER and that will run `npm run start`

`ask_for_human_intervention()` loops while:

- `answer != 'continue'` (returns `None`)
- `answer in ['r']`  (returns the result of the callback)
- `answer != ''`  (returns `{user_input: answer}`)

I don't think that `user_feedback` would ever be "continue" as it doesn't return `answer` in that case.

```python
 user_feedback = response['user_input'] if 'user_input' in response else None
            if user_feedback == 'continue':
                return { "success": True, "user_input": user_feedback }
```

...neither would this:
```python
            if user_feedback is not None:
                iteration_convo = AgentConvo(self)
                iteration_convo.send_message('development/iteration.prompt', {
                    "name": self.project.args['name'],
                    "app_type": self.project.args['app_type'],
                    "app_summary": self.project.project_description,
                    "clarification": [],
                    "user_stories": self.project.user_stories,
                    # "user_tasks": self.project.user_tasks,
                    "technologies": self.project.architecture,
                    "array_of_objects_to_string": array_of_objects_to_string,
                    "directory_tree": self.project.get_directory_tree(True),
                    "files": self.project.get_all_coded_files(),
                    "user_input": user_feedback,
                })

                # self.debugger.debug(iteration_convo, user_input=user_feedback)

                task_steps = iteration_convo.send_message('development/parse_task.prompt', {}, IMPLEMENT_TASK)
                iteration_convo.remove_last_x_messages(2)

                return self.execute_task(iteration_convo, task_steps, is_root_task=True)
```

**Comment by LeonOstrez** [comment]
This should be fixed now because continue_development can loop forever if `user_feedback is not None and user_feedback != 'continue'`
