### ISSUE TITLE
Can't run main.py - Windows installing instructions not clear

### ISSUE THREAD

**Issue by yensyciprian** [Pythagora-io/gpt-pilot#14]
PS C:\Users\yensi\Documents\CODING AND DEV\VISUAL STUDIO CODE\gpt-pilot> & "c:/Users/yensi/Documents/CODING AND DEV/VISUAL STUDIO CODE/gpt-pilot/pilot-env/Scripts/Activate.ps1"
(pilot-env) PS C:\Users\yensi\Documents\CODING AND DEV\VISUAL STUDIO CODE\gpt-pilot> & "c:/Users/yensi/Documents/CODING AND DEV/VISUAL STUDIO CODE/gpt-pilot/pilot-env/Scripts/python.exe" "c:/Users/yensi/Documents/CODING AND DEV/VISUAL STUDIO CODE/gpt-pilot/pilot/main.py"
Traceback (most recent call last):
  File "c:\Users\yensi\Documents\CODING AND DEV\VISUAL STUDIO CODE\gpt-pilot\pilot\main.py", line 31, in <module>
    args = init()
           ^^^^^^
  File "c:\Users\yensi\Documents\CODING AND DEV\VISUAL STUDIO CODE\gpt-pilot\pilot\main.py", line 17, in init
    create_database()
  File "c:\Users\yensi\Documents\CODING AND DEV\VISUAL STUDIO CODE\gpt-pilot\pilot\database\database.py", line 396, in create_database
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\yensi\Documents\CODING AND DEV\VISUAL STUDIO CODE\gpt-pilot\pilot-env\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
        Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
        Is the server running on that host and accepting TCP/IP connections?

(pilot-env) PS C:\Users\yensi\Documents\CODING AND DEV\VISUAL STUDIO CODE\gpt-pilot>

**Comment by nawek** [comment]
do you have a postgresql server on your windows ?

**Comment by yensyciprian** [comment]
I installed it and manually created the database since the app didn't to it automatically, those instructions are not included in the installation process. More clear instructions are needed including the prerequisites.

**Comment by yensyciprian** [comment]
I installed it and manually created the database since the app didn't to it automatically, those instructions are not included in the installation process. More clear instructions are needed, including the prerequisits.

**Comment by jjaimealeman** [comment]
Linux user.

I too, found it confusing when it tried to connect to a database, but nothing was mentioned in the readme. So I searched for `database` in the cloned repo, and found a reference to postgres. I already have it running, so I just added my details.

I feel like that step should be mentioned in the readme 👍

**Comment by HarshShah0203** [comment]
can anyone please explain step by step how to solve this issue I am unable to connect with postgresql getting many error like duplicate database error, password error and many more

**Comment by Niutonian** [comment]
same as @HarshShah0203, I can't get it working, 
I will try again with a fresh database

**Comment by LeonOstrez** [comment]
Thank you for opening the issue 🙏  The problem is that you didn't have postgresql installed and running. Thanks to everyone helping out here to solve the issue.

We added "requirements" section to Readme so it should be more clear now.
