### ISSUE TITLE
Support for AutoGPT plugins

### ISSUE THREAD

**Issue by nalbion** [Pythagora-io/gpt-pilot#140]
Once a web app is complete the GPT Pilot currently asks the user to verify that the web app is running & displaying the content that it should. It would be neat if we implemented support for AutoGPT plugins. [GitHub - gravelBridge/AutoGPT-Web-Interaction: A plugin to enable AutoGPT to interact with websites.](https://github.com/gravelBridge/AutoGPT-Web-Interaction)

- potentially auto-download code from GitHub
- `plugin.name` and `plugin.description` describe to the LLM what the plugin provides
- Actually, the introduction for the LLM seems to be in `post_prompt` where it calls `prompt.add_resource()`
- `prompt.add_command()` calls set up something like function calling

More documentation here - https://github.com/Significant-Gravitas/AutoGPT/blob/master/autogpts/autogpt/autogpt/models/base_open_ai_plugin.py

**Comment by LeonOstrez** [comment]
For now we don't have this on roadmap. Maybe we revisit it in future

**Comment by GoZippy** [comment]
Roadmap this +1
