### ISSUE TITLE
[MacOS] Split the output into lines in terminal

### ISSUE THREAD

**Issue by Darwinium** [Pythagora-io/gpt-pilot#142]
I'm not sure how to solve it, but I've noticed that in MacOS when it asks for user input, the instructions are lengthy and don't have line breaks. As a result, I can't see what I'm supposed to do, and there's no horizontal scroll. It seems that this issue only occurs when input is needed, as the rest of the pilot's output is fine.
<img width="1142" alt="Screenshot 2023-10-06 at 16 09 12" src="https://github.com/Pythagora-io/gpt-pilot/assets/52569/c830592c-36a8-43a1-8231-434edc637e28">

And here for example is all good:
<img width="1147" alt="Screenshot 2023-10-06 at 16 17 44" src="https://github.com/Pythagora-io/gpt-pilot/assets/52569/a0cdba93-1113-4da6-93a5-910bb29b85b5">

**Comment by nalbion** [comment]
I've tried this on Windows (from IntelliJ)

![image](https://github.com/Pythagora-io/gpt-pilot/assets/1866161/d76e288c-3df0-4430-92b4-60ffbf1c7e8f)

Windows cmd prompt:

![image](https://github.com/Pythagora-io/gpt-pilot/assets/1866161/f518136e-b42d-459a-b77e-8ec3e48acbec)

and Ubuntu (WSL)

![image](https://github.com/Pythagora-io/gpt-pilot/assets/1866161/55b37bd6-8ff2-409a-8025-1fb16956873e)

**Comment by nalbion** [comment]
To test this, I edited `pilot/helpers/Project.py`:

```python
    def start(self):
        """
        Start the project.
        """
        self.project_manager = ProductOwner(self)
        print(json.dumps({
            "project_stage": "project_description"
        }), type='info')

        self.current_step = 'asdf'
        styled_text(self, 'I am not sure how to solve it, but I have noticed that in MacOS when it asks for user input, '
                          'the instructions are lengthy and do not have line breaks. As a result, I can not see '
                          'what I am supposed to do, and there is no horizontal scroll. '
                          'It seems that this issue only occurs when input is needed, as the rest of the output is fine.')

        self.project_manager.get_project_description()
```

...maybe the question actually ended right at the point where it hit the edge of your window.?
