### ISSUE TITLE
GPT Pilot exits with error when running npm start

### ISSUE THREAD

**Issue by junyjeon** [Pythagora-io/gpt-pilot#154]
## Description:
I'm trying to set up the project environment for a new Electron.js application. When I run npm start, Electron.js starts and waits for the server at localhost:3000 as expected. However, there's no actual server or frontend code to serve at localhost:3000 yet, so Electron.js shows an error because there's nothing to load. This behavior is expected and okay for now.

But after setting up the project environment, I get an error message saying "GPT PILOT EXITING WITH ERROR". I'm not sure why this error is occurring.

## Steps to reproduce:
1. Set up the project environment as described in Dev step 5.
2. Run npm start.

## Error message:
`Dev step 5

Since we are just setting up the project environment, there are no visual indications to confirm if things are working fine. However, we can verify things by running the `npm start` command. If everything is set up correctly, npm should not return any error and the terminal should stay running with Electron.js waiting for the server at `localhost:3000`.

However, keep in mind there is no actual server or frontend code to serve at localhost:3000, so Electron.js would show an error as there's nothing to load. This behavior is expected and okay for now until we've created the actual frontend. 

Hence, if there are no errors on running `npm start`, that means Electron.js has been set up successfully and you can consider this task as done and move on to the next.

Restoring development step with id 6
Updated file /home/junyojeo/gpt-pilot/workspace/Memori/package.json
Updated file /home/junyojeo/gpt-pilot/workspace/Memori/main.js
---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "/home/junyojeo/gpt-pilot/pilot/main.py", line 52, in <module>
    project.start()
  File "/home/junyojeo/gpt-pilot/pilot/helpers/Project.py", line 134, in start
    self.developer.start_coding()
  File "/home/junyojeo/gpt-pilot/pilot/helpers/agents/Developer.py", line 40, in start_coding
    self.implement_task(i, dev_task)
  File "/home/junyojeo/gpt-pilot/pilot/helpers/agents/Developer.py", line 67, in implement_task
    return self.execute_task(convo_dev_task, task_steps, development_task=development_task, continue_development=True, is_root_task=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junyojeo/gpt-pilot/pilot/helpers/agents/Developer.py", line 288, in execute_task
    return self.task_postprocessing(convo, development_task, continue_development, result, function_uuid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junyojeo/gpt-pilot/pilot/helpers/agents/Developer.py", line 175, in task_postprocessing
    return self.continue_development(convo, last_branch_name, continue_description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junyojeo/gpt-pilot/pilot/helpers/agents/Developer.py", line 334, in continue_development
    task_steps = iteration_convo.send_message('development/parse_task.prompt', {}, IMPLEMENT_TASK)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junyojeo/gpt-pilot/pilot/helpers/AgentConvo.py", line 89, in send_message
    response = parse_agent_response(response, function_calls)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junyojeo/gpt-pilot/pilot/utils/function_calling.py", line 73, in parse_agent_response
    values = list(json.loads(text).values())
                  ^^^^^^^^^^^^^^^^
  File "/home/junyojeo/.brew/opt/python@3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junyojeo/.brew/opt/python@3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junyojeo/.brew/opt/python@3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
--------------------------------------------------`

## Hints to the problem
1. npm start command execution: This keyword indicates that the issue occurs when executing the npm start command.
2. JSONDecodeError: Expecting value: line 1 column 1 (char 0): This keyword specifies the exact error that occurred. This error is thrown when there is no valid JSON data.
3. Electron.js setup: This keyword suggests that the issue is related to the setup of Electron.js.

**Comment by nalbion** [comment]
@junyjeon this should be resolved by recent changes to the `llm_connection.py`
