### ISSUE TITLE
Debugger prompt confuses LLM

### ISSUE THREAD

**Issue by nalbion** [Pythagora-io/gpt-pilot#166]
In `Debugger.debug()` we call:

```python
            debugging_plan = convo.send_message('dev_ops/debug.prompt',
                {
                    'command': command['command'] if command is not None else None,
                    'user_input': user_input,
                    'issue_description': issue_description,
                    'os': platform.system()
                },
                DEBUG_STEPS_BREAKDOWN)
```

> I will give you 2 functions that you can use - `run_command` and `implement_code_changes`.
> `run_command` function will run a command on the machine and will return the CLI output to you so you can see what to do next. Note that the command will run on a {{ os }} machine.
>
> `implement_code_changes` function will change the code where you just need to thoroughly describe what needs to be implemented, I will implement the requested changes and let you know.

...but `DEBUG_STEPS_BREAKDOWN` doesn't follow that instruction:

```python
        {
            'name': 'start_debugging',
            'description': 'Starts the debugging process based on the list of steps that need to be done to debug the problem.',
            'parameters': {
                'type': 'object',
                "properties": {
                    "steps": {
                        'type': 'array',
                        'description': 'List of steps that need to be done to debug the problem.',
                        'items': {
                            'type': 'object',
                            'description': 'A single step that needs to be done to get closer to debugging this issue.  Remember, if you need to run a command that doesnt\'t finish by itself (eg. a command to run an app), put the timeout to 3000 milliseconds. If you need to create a directory that doesn\'t exist and is not the root project directory, always create it by running a command `mkdir`',
                            'properties': {
                                'type': {
                                    'type': 'string',
                                    'enum': ['command', 'code_change', 'human_intervention'],
                                    'description': 'Type of the step that needs to be done to debug this issue.',
                                },
                                'command': command_definition('Command that needs to be run to debug this issue.', 'Timeout in milliseconds that represent the approximate time this command takes to finish. If you need to run a command that doesnt\'t finish by itself (eg. a command to run an app), put the timeout to 3000 milliseconds.'),
                                'code_change_description': {
                                    'type': 'string',
                                    'description': 'Description of a step in debugging this issue when there are code changes required. This should be used only if the task is of a type "code_change" and it should thoroughly describe what needs to be done to implement the code change for a single file - it cannot include changes for multiple files.',
                                },
                                'human_intervention_description': {
                                    'type': 'string',
                                    'description': 'Description of a step in debugging this issue when there is a human intervention needed. This should be used only if the task is of a type "human_intervention".',
                                },
                                "check_if_fixed": {
                                    'type': 'boolean',
                                    'description': 'Flag that indicates if the original command that triggered the error that\'s being debugged should be tried after this step to check if the error is fixed. If you think that the original command `delete node_modules/ && delete package-lock.json` will pass after this step, then this flag should be set to TRUE and if you think that the original command will still fail after this step, then this flag should be set to FALSE.',
                                }
                            },
                            'required': ['type', 'check_if_fixed'],
                        }
                    }
                },
                "required": ['steps'],
            },
        },
```

**Comment by nalbion** [comment]
In unit testing (`testDebugger.test_debug()`)

> assert_json_response() ] ERROR: LLM did not respond with JSON: type: command

...so LLM responded with `type: command`

and another one

> ERROR: LLM did not respond with JSON: type: human_intervention

There were some valid responses though...

```json
{
    "steps": [
        {
            "type": "command",
            "command": {
                "command": "npm install --global --force npm@latest",
                "timeout": 3000
            },
            "check_if_fixed": False
        },
        {
            "type": "command",
            "command": {
                "command": "npm cache clean --force",
                "timeout": 3000
            },
            "check_if_fixed": False
        },
        {
            "type": "command",
            "command": {
                "command": "npm install mime",
                "timeout": 3000,
                "success_message": "+ mime@latest added"
            },
            "check_if_fixed": True
        }
    ]
}
```

**Comment by BeingStupid** [comment]
def command_definition(param, param1):
    pass


{
    'name': 'start_debugging',
    'description': 'Starts the debugging process based on the list of steps that need to be done to debug the problem.',
    'parameters': {
        'type': 'object',
        "properties": {
            "steps": {
                'type': 'array',
                'description': 'List of steps that need to be done to debug the problem.',
                'items': {
                    'type': 'object',
                    'description': 'A single step that needs to be done to get closer to debugging this issue.  Remember, if you need to run a command that doesnt\'t finish by itself (eg. a command to run an app), put the timeout to 3000 milliseconds. If you need to create a directory that doesn\'t exist and is not the root project directory, always create it by running a command `mkdir`',
                    'properties': {
                        'type': {
                            'type': 'string',
                            'enum': ['command', 'code_change', 'human_intervention'],
                            'description': 'Type of the step that needs to be done to debug this issue.',
                        },
                        'command': command_definition('Command that needs to be run to debug this issue.',
                                                      'Timeout in milliseconds that represent the approximate time this command takes to finish. If you need to run a command that doesnt\'t finish by itself (eg. a command to run an app), put the timeout to 3000 milliseconds.'),
                        'code_change_description': {
                            'type': 'string',
                            'description': 'Description of a step in debugging this issue when there are code changes required. This should be used only if the task is of a type "code_change" and it should thoroughly describe what needs to be done to implement the code change for a single file - it cannot include changes for multiple files.',
                        },
                        'human_intervention_description': {
                            'type': 'string',
                            'description': 'Description of a step in debugging this issue when there is a human intervention needed. This should be used only if the task is of a type "human_intervention".',
                        },
                        "check_if_fixed": {
                            'type': 'boolean',
                            'description': 'Flag that indicates if the original command that triggered the error that\'s being debugged should be tried after this step to check if the error is fixed. If you think that the original command `delete node_modules/ && delete package-lock.json` will pass after this step, then this flag should be set to TRUE and if you think that the original command will still fail after this step, then this flag should be set to FALSE.',
                        }
                    },
                    'required': ['type', 'check_if_fixed'],
                }
            }
        },
        "required": ['steps'],
    },
},

**Comment by BeingStupid** [comment]
def command_definition(param, param1):
    pass


{
    'name': 'start_debugging',
    'description': 'Starts the debugging process based on the list of steps that need to be done to debug the problem.',
    'parameters': {
        'type': 'object',
        "properties": {
            "steps": {
                'type': 'array',
                'description': 'List of steps that need to be done to debug the problem.',
                'items': {
                    'type': 'object',
                    'description': 'A single step that needs to be done to get closer to debugging this issue.  Remember, if you need to run a command that doesnt\'t finish by itself (eg. a command to run an app), put the timeout to 3000 milliseconds. If you need to create a directory that doesn\'t exist and is not the root project directory, always create it by running a command `mkdir`',
                    'properties': {
                        'type': {
                            'type': 'string',
                            'enum': ['command', 'code_change', 'human_intervention'],
                            'description': 'Type of the step that needs to be done to debug this issue.',
                        },
                        'command': command_definition('Command that needs to be run to debug this issue.',
                                                      'Timeout in milliseconds that represent the approximate time this command takes to finish. If you need to run a command that doesnt\'t finish by itself (eg. a command to run an app), put the timeout to 3000 milliseconds.'),
                        'code_change_description': {
                            'type': 'string',
                            'description': 'Description of a step in debugging this issue when there are code changes required. This should be used only if the task is of a type "code_change" and it should thoroughly describe what needs to be done to implement the code change for a single file - it cannot include changes for multiple files.',
                        },
                        'human_intervention_description': {
                            'type': 'string',
                            'description': 'Description of a step in debugging this issue when there is a human intervention needed. This should be used only if the task is of a type "human_intervention".',
                        },
                        "check_if_fixed": {
                            'type': 'boolean',
                            'description': 'Flag that indicates if the original command that triggered the error that\'s being debugged should be tried after this step to check if the error is fixed. If you think that the original command `delete node_modules/ && delete package-lock.json` will pass after this step, then this flag should be set to TRUE and if you think that the original command will still fail after this step, then this flag should be set to FALSE.',
                        }
                    },
                    'required': ['type', 'check_if_fixed'],
                }
            }
        },
        "required": ['steps'],
    },
},

**Comment by BeingStupid** [comment]
`def command_definition(param, param1):
    pass


{
    'name': 'start_debugging',
    'description': 'Starts the debugging process based on the list of steps that need to be done to debug the problem.',
    'parameters': {
        'type': 'object',
        "properties": {
            "steps": {
                'type': 'array',
                'description': 'List of steps that need to be done to debug the problem.',
                'items': {
                    'type': 'object',
                    'description': 'A single step that needs to be done to get closer to debugging this issue.  Remember, if you need to run a command that doesnt\'t finish by itself (eg. a command to run an app), put the timeout to 3000 milliseconds. If you need to create a directory that doesn\'t exist and is not the root project directory, always create it by running a command `mkdir`',
                    'properties': {
                        'type': {
                            'type': 'string',
                            'enum': ['command', 'code_change', 'human_intervention'],
                            'description': 'Type of the step that needs to be done to debug this issue.',
                        },
                        'command': command_definition('Command that needs to be run to debug this issue.',
                                                      'Timeout in milliseconds that represent the approximate time this command takes to finish. If you need to run a command that doesnt\'t finish by itself (eg. a command to run an app), put the timeout to 3000 milliseconds.'),
                        'code_change_description': {
                            'type': 'string',
                            'description': 'Description of a step in debugging this issue when there are code changes required. This should be used only if the task is of a type "code_change" and it should thoroughly describe what needs to be done to implement the code change for a single file - it cannot include changes for multiple files.',
                        },
                        'human_intervention_description': {
                            'type': 'string',
                            'description': 'Description of a step in debugging this issue when there is a human intervention needed. This should be used only if the task is of a type "human_intervention".',
                        },
                        "check_if_fixed": {
                            'type': 'boolean',
                            'description': 'Flag that indicates if the original command that triggered the error that\'s being debugged should be tried after this step to check if the error is fixed. If you think that the original command `delete node_modules/ && delete package-lock.json` will pass after this step, then this flag should be set to TRUE and if you think that the original command will still fail after this step, then this flag should be set to FALSE.',
                        }
                    },
                    'required': ['type', 'check_if_fixed'],
                }
            }
        },
        "required": ['steps'],
    },
},`
