### ISSUE TITLE
API responded with status code: 429.  Rate limit reached for 10KTPM-200RPM in organization org-WyXXXXXXXXX

### ISSUE THREAD

**Issue by akamalov** [Pythagora-io/gpt-pilot#17]
Getting immediate:

```There was a problem with request to openai API:
API responded with status code: 429. Response text: {
    "error": {
        "message": "Rate limit reached for 10KTPM-200RPM in organization org-WyXXXXXXXXX on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.",
        "type": "tokens",
        "param": null,
        "code": "rate_limit_exceeded"
    }
}
```
This is my first attempt to access OpenAPI for today and I am already getting this error. I am running other applications to generate python code and I am not getting this error.

**Comment by zenchantlive** [comment]
i am having the same issue

**Comment by zvone187** [comment]
This happens when you have a small limit on the number of tokens per minute. OpenAI puts 10k tokens per minute by default which is too little for GPT Pilot, but you can request a limit increase from OpenAI.

**Comment by Zate** [comment]
> This happens when you have a small limit on the number of tokens per minute. OpenAI puts 10k tokens per minute by default which is too little for GPT Pilot, but you can request a limit increase from OpenAI.

No they do not up the limit on GPT-4 according to their own docs and forms.

I'd love to see a combination of using GPT 3.5 Turbo for places where it doesnt matter, with GPT4 just used for the important pieces.

Be nice to have it implement some kind of automated handling of the rate limit such as like https://help.openai.com/en/articles/5955604-how-can-i-solve-429-too-many-requests-errors or similar.

**Comment by zenchantlive** [comment]
I completely agree with you! There s no ability to up our limits
unfortunately.

**Comment by nalbion** [comment]
This is fixed now at https://github.com/Pythagora-io/gpt-pilot/blob/main/pilot/utils/llm_connection.py#L152

I do like @CyKiller's suggestion of exponential back-off. Currently it follows the instructions in the response which is always "Please try again in 6ms"

@Zate also suggests using "GPT 3.5 Turbo for places where it doesnt matter" which is also a good idea.
