### ISSUE TITLE
Pilot restart not working

### ISSUE THREAD

**Issue by gwc4github** [Pythagora-io/gpt-pilot#180]
### ISSUE:
When attempting to restart pilot it can't find the UUID.

### RECREATE:
```
$python main.py app_id='My_AppNAME'
python: can't open file '/usr/src/app/workspace/My_AppNAME/main.py': [Errno 2] No such file or directory
root@9c1716460cd6:/usr/src/app/workspace/My_AppNAME# cd /usr/src/app/pilot
root@9c1716460cd6:/usr/src/app/pilot# python main.py app_id='My_AppNAME'
---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 3246, in execute_sql
    cursor.execute(sql, params or ())
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type uuid: "My_AppNAME"
LINE 1: ...1"."status" FROM "app" AS "t1" WHERE ("t1"."id" = 'My_App...
                                                             ^
```

### EXPECTED:
Pilot would restart where I left off describing the app and let me give it new instructions.

Note that when I named the app I used a space instead of an underscore but when restarting I tried 
- with the underscore
- with the space escaped
- with the name in single quotes
- with the name in double quotes

**Comment by nalbion** [comment]
`My_AppNAME` is not the `app_id`. It's displayed in the banner when you create a new app. 

You might need to check the DB.

You should also be able to run `python main.py --get-created-apps-with-steps`
