### ISSUE TITLE
New here! MAX_TOKENS is probably not pointed towards .env or I did something wrong (Highly plausible :D)

### ISSUE THREAD

**Issue by KevinGeLe** [Pythagora-io/gpt-pilot#195]
![image](https://github.com/Pythagora-io/gpt-pilot/assets/125448701/bba98780-05e8-437f-991e-a35066461d74)

I have tried with different models and MAX_TOKENS= in .env.
Same goes with other prompts.

It does create the user task, but fails when it reaches development. The screenshot is a retry after a reboot with the app_id added.

**Comment by LeonOstrez** [comment]
should be fixed with https://github.com/Pythagora-io/gpt-pilot/pull/201
