### ISSUE TITLE
Lack of possibility to edit technological stack

### ISSUE THREAD

**Issue by GregorD1A1** [Pythagora-io/gpt-pilot#203]
When trying to create an element for Unity game, app halucinated that I need to use Bootstrap, NodeJS and MongoDB for it ;) Defenitely it's needed to be able to go into intereaction with app at technology stack choosing step.

**Comment by LeonOstrez** [comment]
we have that option but it is disabled for this MVP. We don't really suggest it to others because we don't maintain it at the moment but if you really want, try adding flag
`python main.py --advanced`
There will be more features that will be added there

**Comment by GregorD1A1** [comment]
@LeonOstrez I tryied to run with that flag, but can't see any difference. It is not asking me I want to change the technology stack.

**Comment by GregorD1A1** [comment]
After digging in code, I found that to call advanced mode next commend should be used:
python main.py advanced (without --)
But still it not really helps in technology stack edition.
