### ISSUE TITLE
`docker compose up` stuck on attaching services

### ISSUE THREAD

**Issue by anuj-scanova** [Pythagora-io/gpt-pilot#207]
I followed the steps in the readme file to run the application using docker, however on `docker compose up` command, the process is stuck with

```
gpt-pilot git:(main) docker compose up
[+] Building 0.0s (0/0)
Attaching to gpt-pilot-gpt-pilot-1, gpt-pilot-postgres-1
```

**Comment by constantine008** [comment]
same problem

**Comment by dave1010** [comment]
Did you set your OpenAI API key?

If you have this in the `docker-compose.yml`

    OPENAI_API_KEY=${OPENAI_API_KEY}

Then you can set it in your shell with

    export OPENAI_API_KEY=sk-.....

**Comment by techjeylabs** [comment]
i was not able to reproduce the error, i assume you simply forget the env vars. therefore closing
