### ISSUE TITLE
Response in Windows terminal is not being cut into lines

### ISSUE THREAD

**Issue by KevinGeLe** [Pythagora-io/gpt-pilot#209]
![image](https://github.com/Pythagora-io/gpt-pilot/assets/125448701/c58a3d61-429f-444b-b758-3647fb84c845)
Problem:
Response in Windows terminal (CMD,) doesnt get cut when it is longer than the terminal window (or display in full screen.) Zooming in on the terminal waiting for the response and zoom out again, allows my to see the entire task, but it is rather difficult to read the long responses because the text will end up being incredible small.

Note: (Thanks for fixing the last bug, but there was another one :D)
Neat repo for visualizing how an app is going to work. It cant make bigger projects work without flaws. But that was also not what gpt-pilot was supposed to do. It helps gather modules and code snippets that I (a beginner) can use as a template when creating the final product.

**Comment by nalbion** [comment]
@KevinGeLe can you reproduce the issue using this snippet?

https://github.com/Pythagora-io/gpt-pilot/issues/142#issuecomment-1756644718

**Comment by KevinGeLe** [comment]
> @KevinGeLe can you reproduce the issue using this snippet?
> 
> [#142 (comment)](https://github.com/Pythagora-io/gpt-pilot/issues/142#issuecomment-1756644718)

I havent run into issues after cloning a newer version. 

Will close this.
