### ISSUE TITLE
State that Python 3.12 isn't working right now

### ISSUE THREAD

**Issue by CRD716** [Pythagora-io/gpt-pilot#218]
https://github.com/psycopg/psycopg2/issues/1628

python db_init.py currently fails on python 3.12 with 
```
Traceback (most recent call last):
  File "E:\Installs\gpt-pilot\pilot\db_init.py", line 3, in <module>
    from database.database import create_tables, drop_tables
  File "E:\Installs\gpt-pilot\pilot\database\__init__.py", line 1, in <module>
    from .database import database_exists, create_database, save_app
  File "E:\Installs\gpt-pilot\pilot\database\database.py", line 6, in <module>
    import psycopg2
  File "E:\Installs\gpt-pilot\pilot-env\Lib\site-packages\psycopg2\__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: DLL load failed while importing _psycopg: The specified module could not be found.
```

**Comment by CRD716** [comment]
Maybe consider upgrading to psycopg3?

**Comment by Umpire2018** [comment]
https://github.com/Pythagora-io/gpt-pilot/commit/08280d4371498811ee304ed1ec4da1c1d844657a

Confimed.
It seems that python 3.12 doesn't work at the moment but thanks for pointing out.Please open a PR of update required python version in README.MD if you can.

**Comment by Umpire2018** [comment]
About https://github.com/Pythagora-io/gpt-pilot/pull/221#issuecomment-1763574262

I believe there is no need to add rust to requirements.txt because `pip install tiktoken` will finish the job. What `tiktoken` rely is theirs concern.

Maybe you can find help from https://github.com/openai/tiktoken/issues/172 .
