### ISSUE TITLE
OpenAI API not working with JSON

### ISSUE THREAD

**Issue by amanattrish** [Pythagora-io/gpt-pilot#227]
I wanted to build a simple react project with a landing page. I gave description and answered all of the questions. As a result, a project director was created in `workspace` directory.
Everything was smooth until then, finally it asked me to give command to allow to run the `npm start` script, to which I hit entered, then I ran into a weird bug saying `LLM did not respond with JSON`

![image](https://github.com/Pythagora-io/gpt-pilot/assets/53205776/35ae2335-c683-47a2-98f8-10ee960566d0)

Is there anything I'm missing here?

Thanks in advanced and I'm really enjoying this repo.

**Comment by Umpire2018** [comment]
Are you using GPT-4?

Please upload pilot/logger/debug.log so we can take a look.

**Comment by nalbion** [comment]
`ENTER` to retry might work. The retries include extra instructions to the LLM referring to the JSON schema.

**Comment by amanattrish** [comment]
@Umpire2018  Yes I'm using GPT-4. Adding the debug.log file here

[debug.log](https://github.com/Pythagora-io/gpt-pilot/files/12937548/debug.log)

@nalbion I tried `ENTER` to retry, it didn't work.

**Comment by nalbion** [comment]
I've seen this `type: command` error before. It should be fixed in the latest version on `main`

**Comment by amanattrish** [comment]
I'll update you on this one after taking the latest pull

**Comment by amanattrish** [comment]
It worked thanks
