### ISSUE TITLE
GPT-PILOT not coding the project

### ISSUE THREAD

**Issue by Scratch-project** [Pythagora-io/gpt-pilot#258]
Hi everyone,

I just started using GPT-PILOT and I want to make a small IOS APP which scans a barcode and shows a message if the scanned bar code is in the database or not. Every time I start describing the APP, it then shows me 5 questions after that, and waits for an answer to all of them, then after the user stories is ready to go, it says 

```
Great! Now that we have a clear understanding of the requirements for the "Qadyaty_IOS" app, I will proceed with providing these specifications to Throughout the development process, I will keep you updated on the progress and any additional questions that may arise. Once the app is completed, I will provide you with the final version of the app. Thank you for providing the detailed specifications for the "Qadyaty_IOS" app. We will do our best to create a sleek and functional app that meets your requirements. If you have any further questions or concerns, please let me know.
```

Then it just stops.. got-pilot is still running but it just do nothing, I tried to restart it a couple of times and I get the same thing every time. It also said to me once 

`Great! Now that we have a clear understanding of the requirements for the "Qadyaty_IOS" app, we wish you all the best developing your application.`

**Comment by nalbion** [comment]
Which model is this? Try the `feature/258-PO-prompt-for-gpt-3.5` branch

**Comment by Scratch-project** [comment]
> Which model is this? Try the `feature/258-PO-prompt-for-gpt-3.5` branch

I think the problem was just that gpt-3.5-turbo was not good enough. I used gpt-4 and it worked (although another problem emerged, but not this particular problem).

**Comment by Scratch-project** [comment]
I think the problem was just that gpt-3.5-turbo was not good enough. I used gpt-4 and it worked (although another problem emerged, but not this particular problem).
