### ISSUE TITLE
Bad escape \A

### ISSUE THREAD

**Issue by Scratch-project** [Pythagora-io/gpt-pilot#262]
While running gpt-pilot to make an IOS app to scan products and return a specific answer, I got the following error.
<img width="987" alt="Screenshot 2023-10-21 at 20 43 23" src="https://github.com/Pythagora-io/gpt-pilot/assets/88293551/303b1871-8a80-44d6-99b9-01d420cf77b2">

I really have no Idea what the error is + I'm not good dealing with regex. The Error seems to be in a file from python 3.10 version, but why ?

**Comment by LeonOstrez** [comment]
should be fixed with https://github.com/Pythagora-io/gpt-pilot/pull/264 once it is merged

**Comment by Scratch-project** [comment]
Sorry, but I'm still a beginner. When this pull request is accepted, what should I do on my side to have the updates as well ?

**Comment by Scratch-project** [comment]
> should be fixed with #264 once it is merged

Sorry, but I'm still a beginner. When this pull request is accepted, what should I do on my side to have the updates as well ?

**Comment by LeonOstrez** [comment]
Nothing on your side, should have been closed automatically but i misspelled
