### ISSUE TITLE
can you add the easiest way to update get-pilot when you have made changes?

### ISSUE THREAD

**Issue by pryh4ck** [Pythagora-io/gpt-pilot#268]
__ 

is it as easy as going to a GitHub connected IDE and reclone or merge the repo again or just git clone it in the terminal and set it all up again? sorry noob question I know

**Comment by pryh4ck** [comment]
and I mean add to the readme? please?

**Comment by Scratch-project** [comment]
just run:

 `git pull`

this will update your main branch to match every change made till the moment of running.

**Comment by pryh4ck** [comment]
Ok, obv run it in the root dir of the initial git clone? Also will doing this erase personal changes I have added as a fork but never did a pr

**Comment by pryh4ck** [comment]
Oh and thank you!
