### ISSUE TITLE
[Feature] Add app_id to file inside app directory

### ISSUE THREAD

**Issue by jcobreros** [Pythagora-io/gpt-pilot#27]
Maybe I'm missing something obvious, but I'm constantly losing the app_id

**Comment by LeonOstrez** [comment]
when you run "python main.py" first line of output has command to continue developing same project and it contains app_id. Nevertheless, you are right, we do have to change that! I'll keep you updated here once we push changes for this issue

**Comment by jcobreros** [comment]
Yes, sorry if I wasn't clear. I can see the app_id in the first line, but it disappears after a while (when the terminal history reaches its maximum size?), or if I want to go back to the project at a later time.

**Comment by nalbion** [comment]
I've submitted a PR which adds a `--workspace=` arg. It will look up the app by workspace path

**Comment by jonasdebeukelaer** [comment]
hey thanks for adding this but I've been struggling to get this feature to work. 

I have one app named `bot-1`

```
sqlite> select name from app;
bot-1
```

but running this:
```
(venv) ~/C/g/pilot ❯❯❯ python main.py workspace=bot-1                                                                                                                       
------------------ STARTING NEW PROJECT ----------------------
If you wish to continue with this project in future run:
python main.py app_id=da965118-7f05-4dcc-9405-c17d25c3e367
--------------------------------------------------------------

? What is the project name? 
```

I manually found the app id and that works as intended:
```
(venv) ~/C/g/pilot ❯❯❯ python main.py app_id=646673835faa4faaaa7e566d9a79bcb2
<picks up the existing app and continued from where it crashed>
```

Any ideas? 

Also initially I had two apps with the same name, not sure if that might have caused an issue? I deleted the dir and second `bot-1` entry in sqlite before trying these commands.

**Comment by LeonOstrez** [comment]
@jonasdebeukelaer  can you please check what is directory name from the app that you named `bot-1`?

**Comment by nalbion** [comment]
To get the `workspace=bot-1` working I had to add a new `user_apps` table, so you may need to re-run

```
python db_init.py
```

...but beware - it will drop & create new tables.

**Comment by jonasdebeukelaer** [comment]
@LeonOstrez  workspace in `$ROOT/workspaces/bot-1/`

@nalbion ah could make sense, it's possible I had init before this feature was added. looks like my user_apps table is empty. I'll just work around this for now then no worries.

**Comment by nalbion** [comment]
If you _have_ the `user_apps` table then it should work. I've also made changes to `user_id`. At one point it was a random UUID every time you ran the app. Now it comes from your OS username
