### ISSUE TITLE
text color issue on macOS

### ISSUE THREAD

**Issue by ManishAradwad** [Pythagora-io/gpt-pilot#284]
Some text from the gpt pilot seems to be having color issues in light mode on macOS

<img width="447" alt="Screenshot 2023-11-01 at 12 48 13 PM" src="https://github.com/Pythagora-io/gpt-pilot/assets/29497701/0aedd13d-e7b3-4887-8628-94f1c40bf3f1">

Works fine in case of dark mode though

<img width="442" alt="Screenshot 2023-11-01 at 12 50 01 PM" src="https://github.com/Pythagora-io/gpt-pilot/assets/29497701/0cc674d9-fac2-4ddd-9ab7-de2b0542b59b">

Is there a problem with my terminal or GPT Pilot?

**Comment by LeonOstrez** [comment]
did you try using light theme `python main.py theme=light`?

**Comment by jamesdnexa** [comment]
Same problem here.  theme-light doesn't help.  With that setting it's still putting white text for "What is the project name?"  So far I've found it impossible to use in light mode.  Dark themes give me headaches so it's something I'll have to solve as I prefer terminal use to vscode
