### ISSUE TITLE
gpt-pilot doesn't seem to understand pip install output

### ISSUE THREAD

**Issue by vaibhavnayel** [Pythagora-io/gpt-pilot#285]
<img width="1157" alt="Screenshot 2023-11-01 at 3 27 42 PM" src="https://github.com/Pythagora-io/gpt-pilot/assets/19236390/79a4f845-8f24-4475-bdb9-d2c34ade9229">

the agent doesn't seem to understand cli outputs correctly even when it's clear that the operation was successful. is this a bug or am I doing something wrong?

**Comment by CRD716** [comment]
Might just be a failure of GPT4.

**Comment by fenilsuchak** [comment]
I have faced something similar. Even with cli commands that are working fine. It goes into an infinite loop trying to fix something that is already working.

**Comment by techjeylabs** [comment]
closed after inactivity
