### ISSUE TITLE
Dublicate key value (Errors from heaven)

### ISSUE THREAD

**Issue by KevinGeLe** [Pythagora-io/gpt-pilot#287]
Spent the past hour or two, trying to get around this.
```
peewee.IntegrityError: duplicate key value violates unique constraint "file_app_id_name_path"
DETAIL:  Key (app_id, name, path)=(0b9bf143-b3a9-4360-97c5-86019e41322b, package.json, ) already exists.
```
Replicate:
Windows 11 Pro
Newest Main branch.
OpenAI / Gpt-4 (Hella expensive, when your work is closed :D )
Development steps: 3-22.

Fix:
Gpt-Pilot couldnt remove folders/files.
When that error comes it doesnt matter if I go back to earlier development steps.
I have to delete the files/folders, and then on the next dev step it does it again. Most annoying loop, and the more is missing/added from the code, making it unusable.

Maybe:
It creates package-lock.json. So maybe its being used and edited at the same time, if the code was written before I let it Continue till next dev step. That part of the app would still work eg. Socket.io or connected to MongoDB.

**Comment by JanKubicek07** [comment]
Hi, i had same problem. My hot fix. Open somewhere in editor package-lock.json (now is not possible delete file). Try run it again.
