### ISSUE TITLE
check_hostname requires server_hostname

### ISSUE THREAD

**Issue by cyhan8611** [Pythagora-io/gpt-pilot#289]
why this
ENDPOINT=OPENAI

OPENAI_ENDPOINT=https://api.openai.com/v1/chat/completions
OPENAI_API_KEY=[my api key]
AZURE_API_KEY=
AZURE_ENDPOINT=

OPENROUTER_API_KEY=

# In case of Azure/OpenRouter endpoint, change this to your deployed model name
# MODEL_NAME=gpt-4
MODEL_NAME=openai/gpt-3.5-turbo-16k
MAX_TOKENS=8192

# Folders which shouldn't be tracked in workspace (useful to ignore folders created by compiler)
# IGNORE_FOLDERS=folder1,folder2

# Database
# DATABASE_TYPE=postgres

DB_NAME=gpt-pilot
DB_HOST=localhost
DB_PORT=3306

**Comment by senko** [comment]
You seem to have pasted `pilot/.env.example` instead of the error output.

Could you paste the actual error and also please tell us the OS you're using (Windows, MacOS, Linux) and which version/distro? And also which version of Python you're using.

**Comment by LeonOstrez** [comment]
@cyhan8611 can you please provide error you encountered?

**Comment by techjeylabs** [comment]
closing this after inactivity
