### ISSUE TITLE
For reverse chatgpt api, got error "The message you submitted was too long"

### ISSUE THREAD

**Issue by zeushera140** [Pythagora-io/gpt-pilot#294]
> API responded with status code: 413. Response text: {"detail":{"code":"message_length_exceeds_limit","message":"The message you submitted was too long, please reload the conversation and submit something shorter."}}

Any way to customize the length for request to GPT? Cause official GPT-4 is too expensive, I have to use  reverse chatgpt api.

I read the source code, I think I can modify the code here, to cut the length to the limit. But not sure how/where to cut.

> def construct_and_add_message_from_prompt(self, prompt_path, prompt_data):
>        if prompt_path is not None and prompt_data is not None:
>            prompt = get_prompt(prompt_path, prompt_data)
 >           logger.info('\n>>>>>>>>>> User Prompt >>>>>>>>>>\n%s\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>', prompt)
 >           self.messages.append({"role": "user", "content": prompt})

Thanks.

**Comment by pryh4ck** [comment]
I have to use reverse chatgpt api.
> 
> Thanks.

what the heck is reverse chatGPT api? it sounds awesome

**Comment by Salm3** [comment]
Hi, Thank you for sharing about the reverse chatGPT API! It sounds really
interesting. Best regards, Salma Ehab  
  

-  
مُرسل من [MailTime](https://www.mailtime.com) لنظام التشغيل Android

  

On ٠٤‏/١١‏/٢٠٢٣ ٠٣:١٦:٠٩ pryh4ck ***@***.***&gt; wrote:  

> I have to use reverse chatgpt api.

>

>> Thanks.

>

> what the heck is reverse chatGPT api? it sounds awesome

>

> --  
> Reply to this email directly, [view it on GitHub](https://github.com
/Pythagora-io/gpt-pilot/issues/294#issuecomment-1793283594), or
[unsubscribe](https://github.com/notifications/unsubscribe-
auth/BCR7SVF4Z7KKNU6KCZSQR3LYCWJNTAVCNFSM6AAAAAA65FOJ5WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOJTGI4DGNJZGQ).  
> You are receiving this because you are subscribed to this
thread.![](https://github.com/notifications/beacon/BCR7SVEE2GLLEBRYCOMOA6DYCWJNTA5CNFSM6AAAAAA65FOJ5WWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTK4NLAU.gif)Message
ID: ***@***.***&gt;

**Comment by zeushera140** [comment]
> I have to use reverse chatgpt api.
> 
> > Thanks.
> 
> what the heck is reverse chatGPT api? it sounds awesome

https://github.com/xqdoo00o/ChatGPT-to-API

The one still working, as I know, Only ChatGPT account is needed, Plus user could use GPT-4 api

**Comment by techjeylabs** [comment]
closing this after inacitivity
