### ISSUE TITLE
Unable to resume development  - KeyError: 'start_debugging'

### ISSUE THREAD

**Issue by Captain-Bacon** [Pythagora-io/gpt-pilot#3]
I've not completed a project yet as it always crashes into a token limit.

When I restart the app I get the following:

Restoring development step with id 28
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/index.js
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/package.json
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/models/Trade.js
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/public/index.html
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/public/index.js
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/routes/index.js
Dev step 28
DONE

Restoring development step with id 29
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/index.js
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/package.json
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/models/Trade.js
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/public/index.html
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/public/index.js
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/routes/index.js
Dev step 29
NO

Restoring development step with id 30
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/package.json
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/models/Trade.js
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/public/index.html
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/public/index.js
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/routes/index.js
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/index.js
Dev step 30
npm run start

Can you check if the app works?
If you want to run the app, just type "r" and press ENTER
Restoring user input id 23: I want it to figure that out for itself
Restoring development step with id 31
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/index.js
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/package.json
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/models/Trade.js
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/public/index.html
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/public/index.js
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/routes/index.js
Dev step 31
NEEDS_DEBUGGING

Restoring development step with id 32
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/index.js
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/package.json
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/models/Trade.js
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/public/index.html
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/public/index.js
Updated file /Users/<username>/SDP/gpt-pilot/workspace/My_App/routes/index.js
Traceback (most recent call last):
  File "/Users/<username>/SDP/gpt-pilot/pilot/main.py", line 35, in <module>
    project.start()
  File "/Users/<username>/SDP/gpt-pilot/pilot/helpers/Project.py", line 78, in start
    self.developer.start_coding()
  File "/Users/<username>/SDP/gpt-pilot/pilot/helpers/agents/Developer.py", line 32, in start_coding
    self.implement_task()
  File "/Users/<username>/SDP/gpt-pilot/pilot/helpers/agents/Developer.py", line 53, in implement_task
    self.execute_task(convo_dev_task, task_steps, continue_development=True)
  File "/Users/<username>/SDP/gpt-pilot/pilot/helpers/agents/Developer.py", line 112, in execute_task
    self.continue_development(convo)
  File "/Users/<username>/SDP/gpt-pilot/pilot/helpers/agents/Developer.py", line 140, in continue_development
    task_steps = iteration_convo.send_message('development/parse_task.prompt', {}, IMPLEMENT_TASK)
  File "/Users/<username>/SDP/gpt-pilot/pilot/helpers/AgentConvo.py", line 60, in send_message
    response = self.postprocess_response(response, function_calls)
  File "/Users/<username>/SDP/gpt-pilot/pilot/helpers/AgentConvo.py", line 117, in postprocess_response
    response = function_calls['functions'][response['function_calls']['name']](**response['function_calls']['arguments'])
KeyError: 'start_debugging'

Not sure where to go from here.

FWIW a great 'upgrade' would be a text file with the app id's logged in them alongside their project names.  When the terminal loses text then it's a massive pain to go through the debug and hope you've got the right one!

Absolutely loving what I'm seeing so far - really want to get to a point where I can see what it outputs because this is slicker than an oilfield!

**Comment by zvone187** [comment]
I'm so sorry for the late reply. It might happen that you get into a token limit during the debugging process. Right now, the best would be to go back to the development step before the debugging happens and either change the code directly or tell GPT Pilot what's wrong in more details. At the moment, the infinite debugging loops are still not implemented. I'd love to get it implemented asap - just don't have time yet. If you'd like to try, let me know and I can help with getting to know the codebase
