### ISSUE TITLE
after answering second question got an error 

### ISSUE THREAD

**Issue by tianyuzhangterry** [Pythagora-io/gpt-pilot#302]
I successfully open the GPT-pilot. I successfully answer the first question of project name. Then I typed my answer for second question of describing your app. Then when I entered my answer, I got the error like this: 
There was a problem with request to openai API:
HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002175DBCEFA0>: Failed to establish a new connection: [WinError 10060] ))

**Comment by senko** [comment]
Hi.

This looks like a connection error, maybe OpenAI API servers were down or your connection had a problem at the time.

If this persists, please check that your OpenAI key is correctly set in `.env` file (the error in that case might be similar enough).

**Comment by LeonOstrez** [comment]
Hey @tianyuzhangterry , OpenAI API is down a lot since new release, you can check status here https://status.openai.com/

Just try again later when their API is up again or try using some other models
