### ISSUE TITLE
"message": "The model `gpt-3` does not exist",

### ISSUE THREAD

**Issue by owinoalfred** [Pythagora-io/gpt-pilot#304]
There was a problem with request to openai API:
API responded with status code: 404. Response text: {
    "error": {
        "message": "The model `gpt-3` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}

? Do you want to try make the same request again? If yes, just press ENTER. Otherwise, type 'no'. 

same for gpt-4, and others

**Comment by LeonOstrez** [comment]
That means that you don't have access to them using your API key. You should verify that you put in correct API key to .env and also check in your OpenAI account that you have access to API.
