### ISSUE TITLE
Ability to use GPT 3.5 Turbo

### ISSUE THREAD

**Issue by Zate** [Pythagora-io/gpt-pilot#31]
I keep hitting the limits of my GPT4 API access, and I'd love to have the capacity to change over to using GPT3.5

Has any testing been done with that? is it not delivering what is needed or would it be possible to allow the swapping of modesl via a config item perhaps?  Some things I might need the power and complexity of GPT4, but I suspect we could likely make do with GPT 3.5 in some situations perhaps?

**Comment by sander110419** [comment]
I've made a PR to enable the selection of the model.
We aware that GPT3.5 provides way worse code, you're better off using the Azure endpoint and using the gpt4-32k model.

**Comment by coolxeo** [comment]
Just created a PR that could solve it in a simple way
https://github.com/Pythagora-io/gpt-pilot/pull/39

I recommend to use `gpt-3.5-turbo-16k-0613` model as has high capacity

**Comment by coolxeo** [comment]
If you are having problems with rate limited you could try to downgrade to GPT-3 that doesn't have so many restrictions

To make the change, just setup your env variable to whatever model you want to use
`OPENAI_MODEL=gpt-3.5-turbo-16k-0613`

Thanks @zvone187 for merging my PR 🤗

**Comment by zvone187** [comment]
Happy to do so - thank you for the PR 🙏
