### ISSUE TITLE
Name for gpt-3.5

### ISSUE THREAD

**Issue by sergiopani** [Pythagora-io/gpt-pilot#323]
I add this name to docker-compose.yml but it is not recognized when the chat app is started.

MODEL_NAME=gpt-3.5 

I don't have gpt 4 purchased. What is the name for the model 3?

**Comment by senko** [comment]
The name is `gpt-3.5-turbo`, and the variant with larger context is [`gpt-3.5-turbo-16k`](https://github.com/Pythagora-io/gpt-pilot/blob/main/pilot/.env.example#L15C1-L15C1).

Please note that we have known issues with GPT-3.5 - on some runs we end up in an endless loop or GPT ignores the user input, so a headsup it's possible you may run into the same issues.
