### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by Scratch-project** [Pythagora-io/gpt-pilot#324]
```
---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "/Users/omarnagy/Downloads/migration/gpt-pilot/pilot/main.py", line 80, in <module>
    project.start()
  File "/Users/omarnagy/Downloads/migration/gpt-pilot/pilot/helpers/Project.py", line 140, in start
    self.developer.start_coding()
  File "/Users/omarnagy/Downloads/migration/gpt-pilot/pilot/helpers/agents/Developer.py", line 53, in start_coding
    self.implement_task(i, dev_task)
  File "/Users/omarnagy/Downloads/migration/gpt-pilot/pilot/helpers/agents/Developer.py", line 87, in implement_task
    "files": self.project.get_all_coded_files(),
  File "/Users/omarnagy/Downloads/migration/gpt-pilot/pilot/helpers/Project.py", line 198, in get_all_coded_files
    files = self.get_files([file.path + '/' + file.name for file in files])
  File "/Users/omarnagy/Downloads/migration/gpt-pilot/pilot/helpers/Project.py", line 222, in get_files
    file_content = open(full_path, 'r').read()
  File "/Users/omarnagy/anaconda3/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 0: invalid continuation byte
```

Getting this error while implementing the first coding task

**Comment by glwdl** [comment]
> ```
> ---------- GPT PILOT EXITING WITH ERROR ----------
> Traceback (most recent call last):
>   File "/Users/omarnagy/Downloads/migration/gpt-pilot/pilot/main.py", line 80, in <module>
>     project.start()
>   File "/Users/omarnagy/Downloads/migration/gpt-pilot/pilot/helpers/Project.py", line 140, in start
>     self.developer.start_coding()
>   File "/Users/omarnagy/Downloads/migration/gpt-pilot/pilot/helpers/agents/Developer.py", line 53, in start_coding
>     self.implement_task(i, dev_task)
>   File "/Users/omarnagy/Downloads/migration/gpt-pilot/pilot/helpers/agents/Developer.py", line 87, in implement_task
>     "files": self.project.get_all_coded_files(),
>   File "/Users/omarnagy/Downloads/migration/gpt-pilot/pilot/helpers/Project.py", line 198, in get_all_coded_files
>     files = self.get_files([file.path + '/' + file.name for file in files])
>   File "/Users/omarnagy/Downloads/migration/gpt-pilot/pilot/helpers/Project.py", line 222, in get_files
>     file_content = open(full_path, 'r').read()
>   File "/Users/omarnagy/anaconda3/lib/python3.10/codecs.py", line 322, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 0: invalid continuation byte
> ```
> 
> Getting this error while implementing the first coding task

File "/Users/omarnagy/Downloads/migration/gpt-pilot/pilot/helpers/Project.py", line 222
change:
file_content = open(full_path, 'r', encoding='iso-8859-1').read()

**Comment by senko** [comment]
@Scratch-project could you please try [this branch](https://github.com/Pythagora-io/gpt-pilot/tree/refactor-helpers-files) and see if that improves things for you?

It's an attempt at solving the encoding issues across all three major platforms we support.

**Comment by DimShadoWWW** [comment]
@senko I had the same issue and the branch worked for me

**Comment by senko** [comment]
> @senko I had the same issue and the branch worked for me

Great, thanks for testing it! That branch has now been merged to main, closing this as fixed.

**Comment by cian0** [comment]
It hasn't been merged yet?
