### ISSUE TITLE
Add a way to steer the AI when it asks for the yes/no question

### ISSUE THREAD

**Issue by cian0** [Pythagora-io/gpt-pilot#331]
So I encountered an issue whenever it asks a yes/no (just press enter for yes) question where it gets lost in the directory it's in, but I can't seem to prompt or correct it and tell it "Hey, you're just running in circles, actually you're in just the wrong working directory", it will keep on pushing to run a mkdir command, or a cd/ls whatever, when I can just correct it. Is this possible? Or am I missing something?

**Comment by KevinGeLe** [comment]
If gptpilet does try to go into the wrong folder. Just put it in ignorefolders and run from the dev step before, then when it has completed, remember the dev step and close gpt-pilot, remove the folders from ignorefolders, and start from the dev step.

But when it is using python3 and it isnt an environmental value. Then saying that the correct command is python, then it also wouldnt change. 

I had to type this quickly, as it is also annoying me greatly

**Comment by iaoakes** [comment]
@KevinGeLe When using Deb variants you can use python-is-python3 package. And yes, it is annoying AF

**Comment by iaoakes** [comment]
+1 when gpt-pilot gets stuck in a circle there is no way to redirect. I was stuck with it installing the project one layer deeper than it needed to be, but then only looking at the root level. This was briefly fixed by moving all the files and directories up a level, but it still kept spinning, burning more credit.

**Comment by KevinGeLe** [comment]
Thanks, though it is fixed now it seems. But if it happens again i know what to do (:1st_place_medal:

**Comment by techjeylabs** [comment]
i think this topic became obsolete, closing this issue therefore
