### ISSUE TITLE
Cannot use `PeeWee` for NodeJS apps

### ISSUE THREAD

**Issue by nodeGarden** [Pythagora-io/gpt-pilot#338]
Seem's I'm stuck in a forever loop of gpt-pilot trying to fix issues with `peewee`... because, well, there is no `peewee` library for npm. The only one is a random dude's own version of creating `http-server` or `express`-like setup for simple asset serving. 

```
--------- EXECUTE COMMAND ----------
Can I execute the command: `npm install peewee --save` with 30000ms timeout?
```

Based on the agents info, I'm pretty sure this is NOT what is needed. At one point I saw that the API came back with a recommendation to use `https://www.npmjs.com/package/sequelize`, and I said yes, but it keeps getting stuck trying to use PeeWee again. Even after I removed references to it from package.json.

Recommendation: Different package recommendations based on project? Ie, PeeWee for Python, and Sequelize (or similar) for NodeJS.

**Comment by techjeylabs** [comment]
closing this after inacitivy
