### ISSUE TITLE
Pilot ignores steps with renaming files

### ISSUE THREAD

**Issue by Diamanter** [Pythagora-io/gpt-pilot#339]
This step:

`"tasks": [
    {
      "type": "code_change",
      "code_change": {
        "name": "LandingPage.js",
        "path": "src/pages/LandingPage.jsx",
        "content": "import React from 'react';\n\nconst LandingPage = () => {\n  return (\n    <div>\n      <h1>Welcome to Fly Charts!</h1>\n      <p>This is the landing page of the app.</p>\n      <p>More information about the app can be added here.</p>\n    </div>\n  );\n};\n\nexport default LandingPage;\n"
      }
    },`
    
 end up with saving 'LandingPage.js'.
 
 should be 'LandingPage.jsx'
 
 Please, use path, not name for saving!

**Comment by techjeylabs** [comment]
hey there closing this after inacitivty
