### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by dal-bati** [Pythagora-io/gpt-pilot#340]
There was a problem with request to openai API:
API responded with status code: 429. Response text: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

and my env

MODEL_NAME=gpt-3.5-turbo
MAX_TOKENS=40000

![image](https://github.com/Pythagora-io/gpt-pilot/assets/141632722/87fe5549-7efe-4a10-ad72-7e92a64ede71)

**Comment by KarmaLecter** [comment]
I also had this problem ,how can I solve it

**Comment by henryclw** [comment]
You need to pre-pay some money into your OpenAI billing account. If you have no credit, then you could not call the APIs
(I assume that your $5 credit already expired)

**Comment by eyildiz-ugoe** [comment]
i face the same problem. how much do we need to pay to get this off?

**Comment by techjeylabs** [comment]
hey there thats a openai related topic, closing this issue therefore
