### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by KevinGeLe** [Pythagora-io/gpt-pilot#354]
GPT-Pilot (commit): 930
OS: Ubuntu 22.04
Python: 3.9

![image](https://github.com/Pythagora-io/gpt-pilot/assets/125448701/dae8db89-60f2-4913-bc5d-4488814e947d)

Wouldn't it be easier to just check if it was an object or a string. Instead of just halting?

**Comment by senko** [comment]
This should always be a string, so the fact this crashed means there's a bug somewhere else in the code that calls this. Did the project (where this crashed) have non-text files (eg. images, favicons, zip files, stuff like that)?

**Comment by KevinGeLe** [comment]
> This should always be a string, so the fact this crashed means there's a bug somewhere else in the code that calls this. Did the project (where this crashed) have non-text files (eg. images, favicons, zip files, stuff like that)?

It only had .js and .db from sqlite3. The database wasnt corrupt as i could navigate the tables and .js runs without error. But gpt-pilot had some problems where it did not create the .db the first few tries.

**Comment by notnitsuj** [comment]
I'm having the same issue. Looking into the workspace directory, I can see that it has created some non-text files like webpack and some in node_modules. How can I deal with this?

![Screenshot from 2023-12-12 00-46-40](https://github.com/Pythagora-io/gpt-pilot/assets/75330856/6eaa0ecd-2754-404c-a012-b0a1348d32a2)

**Comment by kingshah13** [comment]
me too

**Comment by clickbrain** [comment]
Just got the same error after I believe 19 dev steps.

**Comment by clickbrain** [comment]
Per #363 I didn't send any files to the LLM and got this message. Anything having to do with binary files was generated by. gptpilot if that was the cause, but I don't think it was.

**Comment by dsitnik** [comment]
@clickbrain @senko 
I changed the function escape_specials in AgentConvo and it fixed the issue for me. I don't know what could be causing the error.
```
    def escape_specials(self, s):
        try:
            # Try decoding with utf-8
            if isinstance(s, bytes):
                s = s.decode('utf-8')
        except UnicodeDecodeError:
            try:
                # Try another encoding if UTF-8 fails
                s = s.decode('iso-8859-1')
            except UnicodeDecodeError:
                # Handle cases where decoding fails
                s = s.decode('utf-8', errors='replace')
        s = s.replace("\\", "\\\\")

        # List of sequences to preserve
        sequences_to_preserve = [
            # todo check if needed "\\\\",  # Backslash - note: probably not eg. paths on Windows
            "\\'",  # Single quote
            '\\"',  # Double quote
            # todo check if needed '\\a',  # ASCII Bell (BEL)
            # todo check if needed '\\b',  # ASCII Backspace (BS) - note: different from regex \b
            # todo check if needed '\\f',  # ASCII Formfeed (FF)
            '\\n',  # ASCII Linefeed (LF)
            # todo check if needed '\\r',  # ASCII Carriage Return (CR)
            '\\t',  # ASCII Horizontal Tab (TAB)
            # todo check if needed '\\v'  # ASCII Vertical Tab (VT)
        ]

        for seq in sequences_to_preserve:
            s = s.replace('\\\\' + seq[-1], seq)
        return s
```
