### ISSUE TITLE
After installaing the GPT-pilot VSCode extension, I am not able to register a new account.

### ISSUE THREAD

**Issue by kristiankyvik** [Pythagora-io/gpt-pilot#373]
After installing the GPT-pilot VSCode extension, I am not able to register a new account. I get no feedback, the UI is just not responsive after having introduced an emails + password.

<img width="440" alt="CleanShot 2023-12-21 at 16 34 55@2x" src="https://github.com/Pythagora-io/gpt-pilot/assets/6661158/a3e8f03a-8d96-40c4-9b57-a779037e9818">

**Comment by itunza** [comment]
i am having the same issue

**Comment by Seyyid64** [comment]
same

**Comment by mr-robotanist** [comment]
same

**Comment by nickorlabs** [comment]
Same

**Comment by ShaneGCareCru** [comment]
same

**Comment by crisadasmeq** [comment]
same

**Comment by MikeTheBard** [comment]
same

**Comment by vootshiclone** [comment]
same

**Comment by heiningair** [comment]
plus one!

**Comment by Wodawic** [comment]
and again...

**Comment by khaled-wsa** [comment]
same

**Comment by majklovec** [comment]
Same here.

VSCode: v1.83.0
```
Distributor ID: Ubuntu
Description:    Pop!_OS 22.04 LTS
Release:        22.04
Codename:       jammy
```

**Comment by jyorko** [comment]
me too

**Comment by BytePhoenixCoding** [comment]
Same here

**Comment by michaelirey** [comment]
I wonder if there are any possible work arounds for login/signup issue.

**Comment by Taxuspt** [comment]
Same

**Comment by wilderuncat** [comment]
+1

**Comment by michaelirey** [comment]
According to Matthew Berman he just released a new youtube video about GPT Pilot. The folks are aware of the issue and actively looking into it.

**Comment by cwdaniel** [comment]
Seems to be an issue with their mongo database setup, the API calls are failing with 400's and 500's. 

Since the vs-plugin is not open sourced we can't really see whats happening in the code. But it calls the below endpoints when Registering and Logging in. It appears the plugin doesn't have any validation around failures from the api. Since that's the case someone might want to raise an issue here? Expecting the plugin to return reasonable error messages when calling the api. Otherwise people will just keep posting about this issue. 

Calling `https://api.pythagora.io/register` **returns** 

> "Authentication Failed" when signing up. 

Calling `https://api.pythagora.io/login` **returns**
> {address: 'some-specific-shard-monogo-url'}

**Comment by BytePhoenixCoding** [comment]
Appears to be fixed now at least for me..

**Comment by Mobivs** [comment]
Still unresponsive.

**Comment by rw201** [comment]
same

**Comment by Soliperso** [comment]
The issue hasn’t been fixed

**Comment by Jermfumaster** [comment]
Same here

**Comment by sid-newby** [comment]
ack fuck

**Comment by techjeylabs** [comment]
became obsolete with new versions

**Comment by Aneous** [comment]
I'm still facing this issue. After installing the VS Code extension and I try logging in with my Pythagora account, it says 'Something went wrong, try again later'. Same thing when I try registering a new account. I have a separate laptop running Windows 10 and it's working fine there. However, on my other laptop running PopOS, this problem persists. Anyone with a solution?

**Comment by Tolson321** [comment]
Same here. If I try to use google sign in I get this error. 

MongoServerError: E11000 duplicate key error collection: pythagoraApi.users index: email_1 dup key: { email: "tolson516@gmail.com" }
    at /home/ubuntu/api/node_modules/mongoose/node_modules/mongodb/lib/operations/insert.js:50:33
    at /home/ubuntu/api/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection_pool.js:331:21
    at /home/ubuntu/api/node_modules/mongoose/node_modules/mongodb/lib/sdam/server.js:207:17
    at handleOperationResult (/home/ubuntu/api/node_modules/mongoose/node_modules/mongodb/lib/sdam/server.js:323:20)
    at Connection.onMessage (/home/ubuntu/api/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:206:9)
    at MessageStream.<anonymous> (/home/ubuntu/api/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:61:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/home/ubuntu/api/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:124:16)
    at MessageStream._write (/home/ubuntu/api/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:391:12)

**Comment by mataps** [comment]
I'm having similar issue, I filled up for early access and nothing happened. Theres no email or follow up to Login. 
Then I went to try the extension in VSCode and it requires Login so I signed up with Google but nothing happens. It didn't even log me in.

Till now I could not find a way to use the Plugin.

**Comment by Aladdin1978** [comment]
> I'm having similar issue, I filled up for early access and nothing happened. Theres no email or follow up to Login. Then I went to try the extension in VSCode and it requires Login so I signed up with Google but nothing happens. It didn't even log me in.
> 
> Till now I could not find a way to use the Plugin.

same

**Comment by chrisggr225** [comment]
I don't know if this applies, but it did take me a minute to figure out that I had to totally uninstall the old GPT pilot to get it to work, as they have the same named  'View Container'.
