### ISSUE TITLE
Possible external AI model integration?

### ISSUE THREAD

**Issue by BytePhoenixCoding** [Pythagora-io/gpt-pilot#379]
In future can the AI API endpoint URL be configurable so we can link it to say localhost for our own local AI models such as LLM studio / mistral / openchat etc?

**Comment by BytePhoenixCoding** [comment]
* configurable via the VS code extension

**Comment by mr-robotanist** [comment]
Please add these requests to discussions instead of issues :)

https://github.com/Pythagora-io/gpt-pilot/discussions/24#discussioncomment-7251204

**Comment by vanetreg** [comment]
> * configurable via the VS code extension

I installed it in Cursor, but only one config option found: Gpt Pilot: Installation Path.
I would also prefer ( or at least test ) local LLMs or LLM inference other than OpenAI's, for cost reasons.

**Comment by senko** [comment]
The extension doesn't expose this setting right now, but there's a workaround: [Using GPT Pilot with local LLMs](https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT%E2%80%90Pilot-with-Local-LLMs).

To expose it in the extension we need to:
  * expose it as a command-line flag in GPT Pilot core
  * extension should show the extra "API Endpoint:" field if "advanced" checkbox is enabled, and pass that on when invoking GPT Pilot

**Comment by techjeylabs** [comment]
hi there, closed after inacitivy, also as allready mentioned see wiki
