### ISSUE TITLE
[Enhancement]: add the vscode plugin to a opensource marketplace

### ISSUE THREAD

**Issue by Kreijstal** [Pythagora-io/gpt-pilot#386]
VS Code marketplace is propietary so it can't be used with open source editors such as vscodium, please use Open VSX Registry

**Comment by afiiijooon** [comment]
[](url)

**Comment by afiiijooon** [comment]
https://acala.network

**Comment by techjeylabs** [comment]
@afiiijooon no self promotion

@Kreijstal we highly encourage to have a go yourself. The Core Github repo is opensource, but at this point our developers are busy.
