### ISSUE TITLE
[BUG]: VSC: Error, venv cannot be imported after adding a directory in settings.

### ISSUE THREAD

**Issue by YosuCadilla** [Pythagora-io/gpt-pilot#394]
In VSC, after installation, if you click on the "configuration" button, you are asked to introduce a path or directory.
If you do so, chances are you will break the installation and Python won't be able to find your venv environment.

**Comment by senko** [comment]
@YosuCadilla would you say this is the same issue as #387 ? I'm trying to triage issues and link/close duplicates, so we can have as much info about different bugs and a clear list of what needs to get fixed.

(Note that the bug in the issue I linekd is Windows specific. I don't know if you're also on Windows?)

**Comment by YosuCadilla** [comment]
I am on Debian 12. and my error msg is different, so probably not, but both seem path related.

**Comment by techjeylabs** [comment]
closed after inacitivy
