### ISSUE TITLE
PLEASE SOME QUICK HELP NEEDED HERE : ISSUE IN VSCODE. I'M LOST

### ISSUE THREAD

**Issue by RFARREY** [Pythagora-io/gpt-pilot#398]
Traceback (most recent call last):

File "d:\/gpt-pilot/pilot/main.py", line 8, in

from dotenv import load_dotenv

ModuleNotFoundError: No module named 'dotenv'
![Screenshot 2023-12-23 000816](https://github.com/Pythagora-io/gpt-pilot/assets/45320379/be92921c-bc2e-4bc7-8f3b-6b8975a71b74)

**Comment by ralphilius** [comment]
@RFARREY I caught up here as well. What's your solution?

**Comment by dreallday** [comment]
> @RFARREY I caught up here as well. What's your solution?

This solution worked for me: https://github.com/Pythagora-io/gpt-pilot/issues/387#issuecomment-1868328940

Specifically the py-env part, I didn't remove the extension
