### ISSUE TITLE
Can't install VSCode extension

### ISSUE THREAD

**Issue by olivermorris05** [Pythagora-io/gpt-pilot#400]
"Can't install 'pythagoratechnologies.gpt-pilot-vs-code' extension because it is not compatible with the current version of Visual Studio Code (version 1.79.2)."

on first install.

**Comment by mferris77** [comment]
Any reason you can't upgrade?  I last upgraded a week ago and I'm on version 1.85.1

**Comment by olivermorris05** [comment]
Just downloaded as I use another IDE, assumed it would be up-to-date, all good now!
