### ISSUE TITLE
Error when trying to use as api oobabooga instead of openai on windows

### ISSUE THREAD

**Issue by Redenrik** [Pythagora-io/gpt-pilot#403]
When in windows  I try to use the oobabooga api by setting the correct endpoint and key in the .env file I get this error each time pilot tries an api call (never went after the app description).

`API responded with status code: 404. Response text: {"detail":"Not Found"}
`
How can I fix this (If is fixable)?

**Comment by senko** [comment]
This sounds like there's a mismatch in the URL somewhere. Can you test with curl (or whatever test method oobabooga recomments) first to check if it's server is responding properly?

Maybe [this will help](https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT%E2%80%90Pilot-with-Local-LLMs) (it's not for oobabooga but describes a general method for getting local llms to work); also you can join our [Discord server](https://discord.gg/HaqXugmxr9) there's a couple of people trying out local LLMs and some might be able to help.

**Comment by donymorph** [comment]
got the same issue at first then solved it. have a look the picture. and don't forget to load model 
![1703676192889](https://github.com/Pythagora-io/gpt-pilot/assets/94922760/955518c7-1b28-483b-9ebc-69d3c325d3a6)

**Comment by Redenrik** [comment]
Solved it for me, it was my mistake: I wrote the BASE_ENDPOINT without "chat/completition" at the end.
