### ISSUE TITLE
There was a problem with request to openai API:

### ISSUE THREAD

**Issue by soorajlegend** [Pythagora-io/gpt-pilot#416]
API responded with status code: 404. Response text: { "error": { "message": "The model gpt-4-1106-preview does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.", "type": "invalid_request_error", "param": null, "code": "model_not_found" } }

**Comment by OctoberNicole** [comment]
Maybe try to request a new api

**Comment by soorajlegend** [comment]
I do, but it gives the same error message, I've upgraded to GPT4 since

**Comment by OctoberNicole** [comment]
src/helpers/api.js

**Comment by senko** [comment]
Try to set model (in the `gpt-pilot/pilot/.env`) to a different one, like `gpt-4` or `gpt-3.5-turbo`, and check if you get the same error. If that one works, it's likely that you don't have access to the latest model. If the older ones don't work, perhaps there's an error with the key (maybe copy/pasted incorrectly or similar problem).

**Comment by soorajlegend** [comment]
thank you so much, it works

**Comment by soorajlegend** [comment]
I didn't add the billing details to the openai.com website that's the issue

**Comment by mrAibo** [comment]
I have the same issue under VS Code. Any solution? Where can I change the model? Or will it fixed soon? :/

**Comment by soorajlegend** [comment]
Well, I just added $10 to my open.ai account, this gives my API keys the
capability to access all the available models
