### ISSUE TITLE
vscode does not get the the correct $PATH when searching for installed respositories

### ISSUE THREAD

**Issue by jackmullen** [Pythagora-io/gpt-pilot#417]
I set up a test project that requires access to npm and node.js, both are installed and the path is correct when viewing $PATH. The path includes /usr/bin.  Node.j and npm both respond to WHICH -- but GPT-Pilot does an echo $PATH and the variable is empty. 

This install is running on ubuntu based linux with latest VS Code installed. 

So I opened the terminal (VS Code) in my project folder and found that NPM and node.js are installed in the root path and not the environment path. For example, locally at /usr/bin there is no npm and which npm fails. I am attempting to install node in environment. 

Thank you, 

JM

**Comment by techjeylabs** [comment]
actually you need todo anything inside the venv in the gpt-pilot folder. Make sure the PATH is included there.

**Comment by techjeylabs** [comment]
closed after inactivity
