### ISSUE TITLE
Code for true or false are not written in the correct case

### ISSUE THREAD

**Issue by brain1961** [Pythagora-io/gpt-pilot#42]
While GPT Pilot was creating code and attempted to run the app.py, an error was displayed indicating that the boolean True was written in lower case, the same with False. the code writer would try to debug the error but it continued to write the true or false with lower case. It would attempt to correct it several time until I killed the process. Here is a sample of one of the line it occurred in. app.run(debug=true) It also occurred in db queries. This was a simple python/flask app.

It would be helpful, if the program asked to continue to debug rather than continuing in a loop, at that prompt we could give input on how to correct the error.

**Comment by LeonOstrez** [comment]
Yeah, makes sense. We will have to update that to ask user if it should continue with debugging or if user can fix the error

**Comment by nalbion** [comment]
If the LLMs are going to spit out code that isn't even valid, we might need to have sanitizer classes which fix up such errors?

https://github.com/tree-sitter may be useful?

**Comment by techjeylabs** [comment]
closed after inactivity
