### ISSUE TITLE
Does not respond to no prompt

### ISSUE THREAD

**Issue by brain1961** [Pythagora-io/gpt-pilot#43]
In instances where GPT Pilot prompts the user if they would like to install a module or other item, if the user types no, it is ignored and the program continues with the install process.

**Comment by LeonOstrez** [comment]
this is similar issue to https://github.com/Pythagora-io/gpt-pilot/issues/35

will let you know once we got a fix for it

**Comment by LeonOstrez** [comment]
This is fixed, command will be skipped if you type "no".

We still plan to add functionality where you can add suggestions to change command or do something else
