### ISSUE TITLE
How can I restore a session from existing workspace in a specific step OR retrieve an App ID from a previous run?

### ISSUE THREAD

**Issue by GusGusGusGus** [Pythagora-io/gpt-pilot#436]
### Version

Command-line (Python) version

### Operating System

Windows 10

### Your question

I made a project with 59 steps. I lost access to the original App ID (because the terminal is like a rolling file, it deleted the initial outputs). Right now, I have a workspace, with which I tried to follow the instructions to restore an old session (by providing workspace=my\workspace\path). It didn't work. I tried also to give it the last step where we left off:
python.exe main.py workspace=..\workspace step=59
Didn't work either as GPTPilot always seems to start from a new project. How can I either 
1) get the app ID of a previous run?
OR 
2) restore a project based on a workspace at a specific step?

**Comment by senko** [comment]
You can get a list of projects you started with:

```
python main.py --get-created-apps-with-steps
```

Then copy-paste the `app_id` from the project and run it as `python main.py app_id=<your-app-id>`
