### ISSUE TITLE
[Bug]: Crashes 

### ISSUE THREAD

**Issue by fti9999** [Pythagora-io/gpt-pilot#450]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### What happened?

<img width="345" alt="image" src="https://github.com/Pythagora-io/gpt-pilot/assets/118088675/80709bb7-8fa2-433a-8e30-f3863199aab7">

It asks to save the project and then crashes. It crashes when it begins when it is downloading the requirements of the app that it is creating. Plus, it doesn't allow you to see the actual errors. I have provided a screen shot of the point at which it crashes.

**Comment by robbertjanssen85** [comment]
I have the same bug. also no record of any errors, it just crashes and the GPT-pilot extension 'unloads' / disappears
