### ISSUE TITLE
[Bug]: The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by ceponatia** [Pythagora-io/gpt-pilot#457]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### What happened?

I've just installed the extension and selected a folder in Documents > Code. When I choose the option to start a new project, I get the error "The filename, directory name, or volume label syntax is incorrect.". I've tried this with several different folders and always get the same error.

**Comment by ceponatia** [comment]
This issue was caused by having the Documents folder on OneDrive selected instead of my local drive. Works now.

**Comment by ceponatia** [comment]
Lol, nevermind. Now I get this error: Error installing GPT Pilot: Command failed: "c:\Code"\gpt-pilot\pilot-env\Scripts\python -m pip install -r requirements.txt C:\Python312\python.exe: can't open file 'c:\\gpt-pilot\\pilot-env\\Scripts\\python': [Errno 2] No such file or directory"

Why is it trying to go into c:\gpt-pilot when that folder isn't specified anywhere?

**Comment by larrybird1** [comment]
Im having the same issue

filename, directory name, or volume syntaxx is incorrect

while trying to use for the first time

**Comment by larrybird1** [comment]
![Screenshot_212](https://github.com/Pythagora-io/gpt-pilot/assets/13463012/6f024765-4078-428a-85cf-66d82cc75cb9)
