### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by larrybird1** [Pythagora-io/gpt-pilot#458]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### What happened?

I try to start using and i get this error

The filename, directory name, or volume label syntax is incorrect

![Screenshot_212](https://github.com/Pythagora-io/gpt-pilot/assets/13463012/010cb99e-818e-42bb-8a3b-c1cba5e865b6)

**Comment by senko** [comment]
This should be fixded with the newer version of the extension (0.0.27 or newer). Please reinstall the extension, restart VS Code, and then when you open the extension, go to its settings and select a different installation folder for GPT Pilot. This will force reinstall of gpt pilot.

After these steps, you should have a working installation. If you encounter errors at any point, reach out to us on Discuss and we'll try to help.
