### ISSUE TITLE
[Bug]: GPTP probably not compatible with PHP Composer

### ISSUE THREAD

**Issue by Michal-Mikolas** [Pythagora-io/gpt-pilot#468]
### Version

Command-line (Python) version

### Operating System

Windows 10

### What happened?

1. I tried to prompt GPTP to create "Hello World" web page using PHP. 
2. GPTP suggested everything correctly, then run propper `composer` command. 
3. After that it marked every line of `composer` output as `CLI ERROR` even though the command run without any problem (see attachment). 
4. After the `composer` command finished, GPTP exited with `OSError` (EDIT: `OSError` fixed in newest version). 

### I currently use: 

- Windows 10 22H2, 
- Python 3.11.2
- Composer 2.3.10 

------

#### GPTP markes successfull output of `composer` as `CLI ERROR` 

![jXOuSPQn6E](https://github.com/Pythagora-io/gpt-pilot/assets/900316/b6771fcd-9672-40d0-a038-24d3e704e10a)

#### OSError after `composer` finishes (EDIT: `OSError` fixed in newest version)

![GR9mBsAEdF](https://github.com/Pythagora-io/gpt-pilot/assets/900316/c1d12f5c-c277-4565-a302-6ea652b0b158)

#### Full powershell log of my run

[Windows PowerShell Log.txt](https://github.com/Pythagora-io/gpt-pilot/files/13797917/Windows.PowerShell.Log.txt)

**Comment by Michal-Mikolas** [comment]
I've tried to update GPTP to the newest version: 

- The `OSError` does not longer appear (so I think is resolved). 
- The `CLI ERROR` bug is still there, but doesn't interrupt the process. So even though it's confusing, user can still continue using GPTP to build the project.

**Comment by senko** [comment]
The `CLI ERROR` there is just output from stderr. Looks like `composer` uses stderr (as opposed to stdout) to log during the project creation process.

The other error (trying to open directory as a file) was fixed in https://github.com/Pythagora-io/gpt-pilot/commit/89120dbffe9dcf30743f50e87d0f48e28354f01c
