### ISSUE TITLE
Unable to use GPT-3.5-turbo from .env file

### ISSUE THREAD

**Issue by parjanyaacoder** [Pythagora-io/gpt-pilot#47]
Getting this error on running command `python main.py` in terminal 

```
------------------ STARTING NEW PROJECT ----------------------
If you wish to continue with this project in future run:
python main.py app_id=8337ff83-bde9-413b-af89-d141dae36b4f
--------------------------------------------------------------

What is the project name? New Project


 Describe your app in as many details as possible. New Sample Project


There was a problem with request to openai API:
API responded with status code: 404. Response text: {
    "error": {
        "message": "The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}

 Do you want to try make the same request again? If yes, just press ENTER. Otherwise, type 'no'. 
```

### .env file 

> 
> #OPENAI or AZURE
> ENDPOINT=OPENAI
> OPENAI_API_KEY=xyz
> AZURE_API_KEY=
> AZURE_ENDPOINT=
> MODEL_NAME=gpt-3.5-turbo
> MAX_TOKENS=8192
> DB_NAME=gpt-pilot
> DB_HOST=localhost
> DB_PORT=5432
> DB_USER=postgres
> DB_PASSWORD=postgres

Operating system - Windows
python --version  - Python 3.11.4

**Comment by interceptor** [comment]
You have to change the following:
gpt-pilot\pilot\const\llm.py:

MIN_TOKENS_FOR_GPT_RESPONSE = 600
MAX_GPT_MODEL_TOKENS = 4097
MAX_QUESTIONS = 5
END_RESPONSE = "EVERYTHING_CLEAR"

gpt-pilot\pilot\utils\llm_connection.py

find replace gpt-4 with gpt-3.5-turbo

I did however run into problems later on, I guess its because of gpt-3.5 smaller context size. I guess we have to wait until our API accounts are granted access to the gpt-4 model.

**Comment by nalbion** [comment]
Were you able to move on @parjanyaacoder ?

**Comment by bobwatcherx** [comment]
i follow you and change to gpt-3.5-turbo but openai key not free 

API responded with status code: 429. Response text: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

**Comment by nalbion** [comment]
@bobwatcherx try the branch of https://github.com/Pythagora-io/gpt-pilot/pull/153
