### ISSUE TITLE
[Howto]: 

### ISSUE THREAD

**Issue by riyazmohammad** [Pythagora-io/gpt-pilot#473]
### Version

VisualStudio Code extension

### Operating System

Windows 10

### Your question

GPT Pilot reply

Apologies for any confusion. As an AI language model, I don't have real-time interaction with the development team. However, I can guide you through the process and assist with any questions or concerns you may have.

To get started with the development, I recommend the following steps:

1. Plan and Design: Work closely with the development team to review and finalize the application requirements and design. This includes discussing the desired features, user interface design, and overall architecture of the application.

2. Development Iterations: Break down the development process into iterations. Each iteration should focus on implementing specific features or functionalities outlined in the user stories. This allows for better organization and collaboration among the development team.

3. Version Control: Set up a version control system, such as Git, to manage the source code. This helps to track changes, collaborate effectively, and maintain code integrity throughout the development process.

4. Agile Development: Consider adopting an agile development methodology, such as Scrum or Kanban. This promotes iterative development, frequent communication, and adaptability, allowing for better efficiency and responsiveness to any changes or feedback.

5. Regular Communication: Maintain regular communication with the development team to provide clarifications, address any questions or concerns, and monitor the progress of the project. This can be done through meetings, email updates, or project management tools.

Remember, the pace of development will depend on the complexity of the application and the availability of the development team. It's essential to have a clear plan, open lines of communication, and regular collaboration to ensure a successful outcome.

If you have any specific questions or need further guidance, please feel free to ask.

**Comment by senko** [comment]
@riyazmohammad I don't understand, what is your question? This just seems like a copy-pasted response from GPT.

**Comment by riyazmohammad** [comment]
GPT Pilot is not providing code here is that reply

Apologies for any confusion. As an AI language model, I don't have real-time interaction with the development team. However, I can guide you through the process and assist with any questions or concerns you........

**Comment by Nahueleti** [comment]
I believe I'm having a similar issue. I create the app description, and then GPT Pilot replies with clarifying questions, all at once, no prompting or waiting for any actual response. When I answer in my own way, GPT pilot states something of the sort of "here are the numbered steps I'll take" and then "Once these steps are completed, I will share the details of the project plan, repository link, and other relevant information with you for your review and approval. Let me know if you have any questions or concerns before we move forward.", yet GPT Pilot never starts creating actual code.

I tweaked the code to use a local llm by hardcoding the openai URL to a local server running an OpenAI compatible API service, so that _might_ be the issue on my end.

**Comment by riyazmohammad** [comment]
I think GPT Pilot  creating actual code only with Model **gpt-4-1106-preview**

b'coz i use 
codellama-34b-instruct, 
mixtral-8x7b-instruct, 
openhermes-2.5-mistral-7b, 
gpt-3.5-turbo-16k 

but responce same 

if I am wrong please anybody can tell me which local model  work fine with code?

**Comment by senko** [comment]
Yes, the prompts are all optimized for GPT4. If you want to run GPT Pilot with another model, you should tweak the prompts (in `pilot/prompts`) directory, here's a bit more context: https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT%E2%80%90Pilot-with-Local-LLMs
