### ISSUE TITLE
bigger app and visualisation model

### ISSUE THREAD

**Issue by Areen3** [Pythagora-io/gpt-pilot#49]
I see an area that needs to be addressed.
larger applications are characterized by the fact that they have a complex structure.
the problem of the designer is that such a complex structure must be maintained either in the head (which is difficult) or in some external tool. This means that without some visualization mode it will be difficult for the person issuing the commands to write such an application. Unless the analyst makes an application model and then the programmer will commission tasks according to this model

**Comment by LeonOstrez** [comment]
you are correct. we have discussed that before and have few potential solutions. It is definitely on our roadmap

**Comment by nalbion** [comment]
- [ ] #68 
- [ ] #83
- [ ] #89
