### ISSUE TITLE
[Howto]: Change extension email address in VS code

### ISSUE THREAD

**Issue by Thincoder** [Pythagora-io/gpt-pilot#493]
### Version

VisualStudio Code extension

### Operating System

Windows 10

### Your question

Please help. How can I change the email address that I used when installing the GPT Pilot extension in VS code.

The reason I am asking is because I cannot get access to my GPT-4 account. I suspect it is because I used a different email address  when installing the GPT Pilot extension in VS code than the one I used as login for my Openai GPT-4 account.

I get the following error:
API responded with status code: 404. Response text: { "error": { "message": "The model gpt-4-1106-preview does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.", "type": "invalid_request_error", "param": null, "code": "model_not_found" } }

Your help will be greatly appreciated.
Thank you.

**Comment by senko** [comment]
@Thincoder the email/password in the extension don't need to be the same as your OpenAI emali or password - we're *not* using those credentials to access your OpenAI account. There's a separate step in settings where you can enter your OpenAI key, and that's what we use for accessing GPT4.

You can use any emali address that you have, and as a general rule you shouldn't reuse passwords anywhere.

Check that you can log in to https://platform.openai.com/playground and that you can select `gpt-4-1106-preview` model from the models list in the playground page. If it's not listed, then your account doesn't have access to this model.

**Comment by Thincoder** [comment]
Thank you for your reply.

I didn't realize that  ChatGPT API and ChatGPT Plus subscription are billed separately. My OpenAI account now have access to this model.
