### ISSUE TITLE
[Bug]: Unable to open projects due to "listen EACCES error" in VSCode

### ISSUE THREAD

**Issue by Hexodus** [Pythagora-io/gpt-pilot#497]
### Version

VisualStudio Code extension

### Operating System

Windows 10

### What happened?

Since the new update of the extension every attempt to open an existing project results in the "listen EACCES error". Some others on Discord reported running into the same problem.  

![image](https://github.com/Pythagora-io/gpt-pilot/assets/243039/2d4a7c9f-f8b5-49af-9bac-0688147b2659)

**Comment by senko** [comment]
This should be fixed in the latest version of the VSCode extension, version 0.0.27 - make sure you reload (or quit/restart) VSCode for the changes to take effect.

**Comment by dedors** [comment]
I just installed the VS Code extension. Now I get this:

![image](https://github.com/Pythagora-io/gpt-pilot/assets/17786985/51d0ce30-8e87-422b-87d9-4828a9b3411e)
