### ISSUE TITLE
difference between skip_until_dev_step vs step?

### ISSUE THREAD

**Issue by Agupta00** [Pythagora-io/gpt-pilot#499]
Hi, 

Could someone explain the difference to me. It wasn't clear to me from the readme. 
thanks!

**Comment by senko** [comment]
Step is a phase in development like `project_description`, `architecture`, `coding`, ... while a dev step is a numbered step within the coding (development) phase. 

In most cases you'd want to specify `skip_until_dev_step` to fast-forward to a specific step in coding and resume from there (instead from the last one).

**Comment by Agupta00** [comment]
thanks very much
