### ISSUE TITLE
[Bug]: No continuation after specifications step

### ISSUE THREAD

**Issue by ilyarvv** [Pythagora-io/gpt-pilot#500]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### What happened?

**IMPORTANT**: From now on, respond with "SPECIFICATIONS_CLEAR" once you have reviewed the specifications and they are clear.

**//So i send it**

SPECIFICATIONS_CLEAR

**//He answering me in a loop something like this**

Great! The specifications are clear. I will now proceed to provide these specifications to the development team so they can start working on creating the "X" app according to the given requirements.

Throughout the development process, I will keep you updated on the progress and any additional clarifications that may be needed. 

Thank you for providing the detailed information for the "X" app. Our team will start working on it, and we will deliver the app to you as per the agreed timeline.

If you have any further questions or concerns, please feel free to let me know.

Thank you for choosing our services! We look forward to creating the "X" app for you.

**Comment by senko** [comment]
This sounds like an AI model other than GPT4.

Currently we have prompts optimized for GPT4, which can easily confuse other LLMs, more info here: https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT%E2%80%90Pilot-with-Local-LLMs

**Comment by ilyarvv** [comment]
Yeah, thanks! I used gpt 3.5
