### ISSUE TITLE
[Bug]: GPT pilot crashes

### ISSUE THREAD

**Issue by Bengan1** [Pythagora-io/gpt-pilot#517]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### What happened?

I was pretty far in the project and the whole GPT pilot window just crashes and becomes gray.

At the step GPT pilot had done an npm install but it didnt work so it wanted to delete the directory and start over. So it started to delete the files. It was a long process of deleting files, then suddenly the window just grayed out. If I enter the project again the window is just gray.

If I go back a step it will do the same deletion of files again and then same thing happens.
![Screenshot 2024-01-11 094027](https://github.com/Pythagora-io/gpt-pilot/assets/36185815/450b8026-abbc-471c-8473-4bd3d7e8df24)

**Comment by LeonOstrez** [comment]
hey @Bengan1 thank you so much for reporting this issue. We are aware of it but it is very hard for us to reproduce it, so it would be extremely helpful if you would be open for a quick call so we can try and debug with you to see what is causing the issue. Would you be open for a quick call? If yes, you can send me an email to leon@gpt-pilot.ai or give me your email and I can send you an invite for meet. Thank you

**Comment by LeonOstrez** [comment]
This is resolved with Beta release
