### ISSUE TITLE
[Bug]: System Stable 59 files, 3,896 lines of code in <12hours- 209 dev steps

### ISSUE THREAD

**Issue by Techfluent-au** [Pythagora-io/gpt-pilot#519]
### Version

VisualStudio Code extension

### Operating System

Windows 10

### What happened?

Can't get past this dev step count. Getting stuck in loops repeating itself. 

Overclocked Amd rizen 7 CPU at 3.5ghz running at 100% 
75% of 24gig ddr4 ram being consumed 
8gig Nvidia card 0% utilisation 

Total : 59 files, 3605 codes, 38 comments, 253 blanks, all 3896 lines

<html>
<body>

language | files | code | comment | blank | total

JSON | 3 | 2,348 | 0 | 2 | 2,350

JavaScript | 53 | 1,185 | 38 | 227 | 1,450

Markdown | 1 | 42 | 0 | 23 | 65

Properties | 1 | 17 | 0 | 1 | 18

HTML | 1 | 13 | 0 | 0 | 13

</body>
</html>

**Comment by techjeylabs** [comment]
duplicate: https://github.com/Pythagora-io/gpt-pilot/issues/539
