### ISSUE TITLE
Hello, a question for the community and a request for the author

### ISSUE THREAD

**Issue by Turbo1337GS** [Pythagora-io/gpt-pilot#522]
### Version

VisualStudio Code extension

### Suggestion

Who would like the author of this toy to add the "basurl" parameter for handling custom endpoints to OpenAI? Because I have my own API for GPT, and I would like to integrate it into this toy instead of using the official one!

**Comment by senko** [comment]
Hi, here's how you can do it: https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT%E2%80%90Pilot-with-Local-LLMs

**Comment by Turbo1337GS** [comment]
> Hi, here's how you can do it: https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT%E2%80%90Pilot-with-Local-LLMs

U are the best BRO!
