### ISSUE TITLE
[Bug]: Installation/Setup Bug (unsupported zip format)

### ISSUE THREAD

**Issue by omarmoss** [Pythagora-io/gpt-pilot#525]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### What happened?

After installing the plugin, the application gives an error reading: 

Error installing GPT Pilot: can't extract the ZIP Error: Invalid or unsupported zip format. No END header found

I have tried uninstalling and reinstalling by running VS code in both administrator mode and not (just attempting in ordinary user mode first time) and I get the same problem, although, the first time I installed it I got a little further by seeing a Create Account page, which encountered an error when I entered an email address and password.

**Comment by senko** [comment]
@omarmoss can you selecting a different folder as the installation folder?

@pavel-pythagora  If the ZIP file is corrupted (eg. as a consequence of network error and failed download), we should remove it so the user can retry the process without changing to a new directory.

**Comment by techjeylabs** [comment]
closed after inactivity
