### ISSUE TITLE
Does GPT pilot navigate the file structure both up and down or only in its current scope?

### ISSUE THREAD

**Issue by wakywayne** [Pythagora-io/gpt-pilot#549]
### Version

Command-line (Python) version

### Operating System

Ubuntu Linux

### Your question

In the docs it talks about how there is a hidden folder variable that you can use to distinguish what folders you do not want GPT pilot to look at. In order for me to know what folders I need to ignore. I need to know if it's also going to navigate back up the tree from whatever folder I execute in or just down. Also **It is really unclear how to specify/know where the ai is building the project.**

**Comment by techjeylabs** [comment]
hey there, you can find the specific var in the .env 

IGNORE_PATHS=./dir1,./dir2


and the workspace the GPT pilot is using is within the gpt-pilot dir itself

**Comment by techjeylabs** [comment]
closing this after inactivity.
