### ISSUE TITLE
[Bug]: files not being found although they are in proper folder

### ISSUE THREAD

**Issue by Real-Experienes** [Pythagora-io/gpt-pilot#574]
### Version

Command-line (Python) version

### Operating System

Windows 11

### What happened?

PS C:\development\gpt-pilot\pilot> python main.py
Traceback (most recent call last):
  File "C:\development\gpt-pilot\pilot\main.py", line 16, in <module>
    from utils.style import color_red
  File "C:\development\gpt-pilot\pilot\utils\style.py", line 3, in <module>
    from questionary import Style
ModuleNotFoundError: No module named 'questionary'
PS C:\development\gpt-pilot\pilot> 

getting this error. First time I have seen it. The files are present and in the proper folders --names all spelled correctly. 
Any advice would be deeply appreciated. 

Thanks guys!

**Comment by AyushModi123** [comment]
You can check if 'questionary' module is installed or not by running
`pip show questionary`
in your command line.

If 'questionary' module is not found, make sure virtual environment is activated then you can try running 'pip install questionary' .
Let me know if this resolves the issue.
Happy to help!

**Comment by Real-Experienes** [comment]
Hi,
Thanks for the reply. I just deleted everything and cloned it again from git. I figured maybe I had one something wrong by accident. Everything worked after that but I know what to try in the future if the problem arises again.

Now everything is working fine except for the artisan, php artisan serve and php artisan migrate. gpt-pilot simply will not accept that it is in the proper folder. It seems the problem is that it is not prefacing "artisan" with "php", not sure why it cannot run the other commands (because when it gives it "thoughts" it clearly states that it wants to check the directory to make sure it is trying to run from the proper one) When I type them into the powershell--they work fine. Could it me using powershell that is causing the issue because powershell will not change directories with gpt-pilot? Just curious. ANY thoughts will be appreciated.

**Comment by Real-Experienes** [comment]
> You can check if 'questionary' module is installed or not by running `pip show questionary` in your command line.
> 
> If 'questionary' module is not found, make sure virtual environment is activated then you can try running 'pip install questionary' . Let me know if this resolves the issue. Happy to help!

Also what is the deal with that "utils.style import color red" error? What in the world  is that and how do I address it in the future?

**Comment by AyushModi123** [comment]
> Now everything is working fine except for the artisan, php artisan serve and php artisan migrate. gpt-pilot simply will not accept that it is in the proper folder. It seems the problem is that it is not prefacing "artisan" with "php", not sure why it cannot run the other commands (because when it gives it "thoughts" it clearly states that it wants to check the directory to make sure it is trying to run from the proper one) When I type them into the powershell--they work fine. Could it me using powershell that is causing the issue because powershell will not change directories with gpt-pilot? Just curious. ANY thoughts will be appreciated.

From what you are saying, manually typing them in powershell works but gpt-pilot is not able to access those files it may be a relative path issue, try 
- setting the full paths to directories
- create and activate a virtual environment (if not) then run gpt-pilot from same terminal

if all else fails, you can always use the docker file to run gpt-pilot in docker container, which really helps in resolving dependency issues.

**Comment by AyushModi123** [comment]
No problem buddy.
Its great that you start by creating a virtual environment.
I meant in system variables only as sometimes system is not able to detect installation(not a gpt-pilot issue).
Run on cmd bro not powershell.
Gpt pilot creates workspace folder for the project.
You can checkout the CLI Arguments in readme.md to resume the project where it left off.

> Thanks again for taking the time Ayush. I really, really appreciate the support, guidance and education! It is so motivating!!
> 
> You suggested "setting the full paths to directories". Do you mean in the OS System EnVar? I don't think so right? Where do you mean I should set the full path? In gpt-pilot somewhere? I always start by creating a virtual environment before starting the project.
> 
> Docker was my last resort because I am getting the same errors when using the GPT-Pilot VS Code plugin/extension. It will not find the PATHS to flutter, android, etc... even though I have, meticulously, properly set them in the System EnVar. GPT-Pilot also creates an extra project folder for some reason(workspace\myproject\my_project\ and places all files and folders in there--is that right? Seems odd but I need your advice.
> 
> Also, is there a way to restart GPT-Pilot where it left off after a reboot or shutdown? The VS Code plugin does it but I am running in powershell. Is there a cmd that I can use?

**Comment by Real-Experienes** [comment]
I hope that you have had a successful, productive week! 
Okay, that's what I thought in the SysEnVar. 
MAN! I KNEW I that I should not have been running on powershell! That little voice was nagging at me for days, telling me not to. Why did I not listen?!?!?!
Yes, I know that GPT Pilot creates a workspace(I saw it work like that in a few YT tuts but could not figure out why I got different results) for the project and all of the files should be be created in there--not two folders in like the result that I have been getting every single time I run GPT-Pilot either from VS Code extension, terminal or powershell{which I should not have been doing}. Any thoughts on why that happens?

Thanks, I'll check that out as I clearly missed some key points in the readme.
Thank you again for your time and efforts and expertise also,
Welcome back o the weekend!!

**Comment by AyushModi123** [comment]
> two folders in like the result that I have been getting every single time I run GPT-Pilot either from VS Code extension, terminal or powershell{which I should not have been doing}. Any thoughts on why that happens?
No idea why that is happening....I am sure you can find an explanation if you look it up in documentation or maybe stackOverflow.

Anytime man. Glad I could be of help.
You can close this issue, if you have resolved it.
See ya
