### ISSUE TITLE
[Bug]: Setting Base URL (to use LM Studio feature for compatible endpoint)

### ISSUE THREAD

**Issue by Mayorc1978** [Pythagora-io/gpt-pilot#580]
### Version

VisualStudio Code extension

### Operating System

Windows 10

### What happened?

When installing the VSCode extension It's not possible to set the base_url to use a local endpoint created with apps like LM_Studio, just the API KEY. This would be important for also alternative endpoints, maybe ollama, openrouter and so on.

**Comment by senko** [comment]
Please have a look at https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT%E2%80%90Pilot-with-Local-LLMs#visual-studio-code-extension
