### ISSUE TITLE
List/Select/Clone/Extend projects

### ISSUE THREAD

**Issue by akamalov** [Pythagora-io/gpt-pilot#6]
Wondering if I can ask a feature request? Since there is a database in play , will it be possible to:

1. List current projects 
2. Select a project
3. Clone a project
4. Add a feature to requested project

This way, a project could be developed from simple to complex in phases.

Also for the existing main.py - For "_Do you want to try make the same request again? If yes, just press ENTER. Otherwise, type 'no'._",  perhaps add flag to 'continuously try until succeed', instead of prompting user to hit 'Enter' every time.

**Comment by zvone187** [comment]
You're right on point. These are great suggestions. I'm thinking to get GPT Pilot wrapped in a VSCode plugin so you could do these quite easily.

**Comment by nalbion** [comment]
- [x] list is provided by PR #213 
- [x] project can be selected by `app_id` or `workspace`

**Comment by LeonOstrez** [comment]
Thank you @akamalov for opening the issue and giving suggestions. As you can see #1, #2 and #4 are implemented and for #3 we don't have plans any time soon so I will open new ticket for feature request on our board and we will work on that in future. Thanks again for trying out GPT Pilot
