### ISSUE TITLE
Documentation for postgres is incorrect

### ISSUE THREAD

**Issue by shoff** [Pythagora-io/gpt-pilot#62]
tldr; update either database.py with "postgres" or change the readme to say DATABASE_TYPE=postgresql

The readme states:

PostgreSQL database info to the `.env` file
   - to change from SQLite to PostgreSQL in your .env just set `DATABASE_TYPE=postgres`

However, in database.py 
```             if DATABASE_TYPE == "postgresql":
                sql = f'DROP TABLE IF EXISTS "{table._meta.table_name}" CASCADE'
            elif DATABASE_TYPE == "sqlite":
                sql = f'DROP TABLE IF EXISTS "{table._meta.table_name}"'
            else:
                raise ValueError(f"Unsupported DATABASE_TYPE: {DATABASE_TYPE}")

            database.execute_sql(sql)
```

**Comment by LeonOstrez** [comment]
The idea is that you just change in .env from `DATABASE_TYPE=sqlite` to `DATABASE_TYPE=postgres` and everyhing else should be the same. I don't really understand what is the problem you are having.

Can you please explain in more details what exactly is the issue to you? It would be good if you could share error logs

**Comment by shoff** [comment]
> The idea is that you just change in .env from `DATABASE_TYPE=sqlite` to `DATABASE_TYPE=postgres` and everyhing else should be the same. I don't really understand what is the problem you are having.
> 
> Can you please explain in more details what exactly is the issue to you? It would be good if you could share error logs

The code and the documentation don't line up. In the documentation you say set "DATABASE_TYPE=postgres" however the code doesn't recognize the word **"postgres"** the code is looking for **"postgresql"**

**Comment by nalbion** [comment]
I can only find `postgres` in the code, no occurences of `postgresql`.
