### ISSUE TITLE
[Bug]: package "python-dotenv" is missing.

### ISSUE THREAD

**Issue by talkingtoaj** [Pythagora-io/gpt-pilot#631]
### Version

VisualStudio Code extension

### Operating System

Windows 10

### What happened?

I installed the VSCode extension on my windows machine, I'm running WSL2 with Ubuntu where the setup registers the folder after I select my python version. After clicking "New App" I receive error 
```
Traceback (most recent call last):
File "/root/temp/gpt-pilot/pilot/main.py", line 12, in
raise RuntimeError('Python environment for GPT Pilot is not completely set up: required package "python-dotenv" is missing.') from None
RuntimeError: Python environment for GPT Pilot is not completely set up: required package "python-dotenv" is missing.
```

In a shell I run `pip install -r requirements.txt` - after installing, it still fails in the same way - "python-dotenv" is missing.
In the shell I try `pip install python-dotenv` - I am told that it already exists.

- There is nothing in the documentation about having to manually install packages
- Attempting to install them manually doesn't seem to work in any case

**Comment by Girishparyani011** [comment]
same is happening with me

**Comment by carstenwawer** [comment]
Same for me.

**Comment by At0kir** [comment]
Same issue here using vs code extension on windows:

Traceback (most recent call last):

File "d:\GPT Pilot\gpt-pilot\pilot\main.py", line 12, in

raise RuntimeError('Python environment for GPT Pilot is not completely set up: required package "python-dotenv" is missing.') from None

RuntimeError: Python environment for GPT Pilot is not completely set up: required package "python-dotenv" is missing.
![image](https://github.com/Pythagora-io/gpt-pilot/assets/83778380/13088627-19d7-452d-8ed5-0d073ae3e759)

**Comment by JaySmith502** [comment]
Same issue is happening to me as noted above

**Comment by andycrellin** [comment]
Quick work around that seems to have worked for me for now:

Find:
`<your folder>\gpt-pilot\pilot-env\pyvenv.cfg`

Change the following line from false to true
`include-system-site-packages = true`

Install the requirements from the following file:
`<your folder>\gpt-pilot\requirements.txt`

`pip install -r <your folder>\gpt-pilot\requirements.txt`

This does mean installing the packages globally though.

**Comment by david-thrower** [comment]
Same here.

When I open Pythagora and click [create app], I get the error:

```
  File "[redacted]/pythagora/gpt-pilot/pilot/main.py", line 12, in <module>
    raise RuntimeError('Python environment for GPT Pilot is not completely set up: required package "python-dotenv" is missing.') from None
RuntimeError: Python environment for GPT Pilot is not completely set up: required package "python-dotenv" is missing.
```

I tried opening a terminal and running pip3 install python-dotenv. I close Pythagor and VS code. I re-open. When I return, I try again, and I get the same error.

I will try the workaround noted above.

**Comment by swichers-xx** [comment]
I fixed this by using the solution listed in issue #387 
Temporary workaround:

open command line in the gpt-pilot sub-directory of the folder which you selected for the installation of GPT Pilot (there should be requirements.txt file already there)
create the virtual environment with python -m venv pilot-env
activate the environment with pilot-env\Scripts\activate
install packages with pip install -r requirements.txt
go to the pilot subdirectory (not pilot-env, just pilot). If there is gpt-pilot file in that subdirectory delete it (that is sqlite database) and then run python db_init.py to initialize new database

**Comment by scout0773** [comment]
Unsure if this will be of any significant help but on my first installation, I was having the same issue. I ran `python -m pip install -r requirements.txt` and it worked for me.

**Comment by techjeylabs** [comment]
https://github.com/Pythagora-io/gpt-pilot/issues/387 

hey there you can find a temporary workarround here, aswell its a duplicate, therefore closing
