### ISSUE TITLE
ModuleNotFoundError: No module named 'playhouse'

### ISSUE THREAD

**Issue by ces-hoangdao** [Pythagora-io/gpt-pilot#64]
When I try run `python db_init.py  ` 
terminal throw the error 
`Traceback (most recent call last):
  File "/home/ces-user/Desktop/gpt-pilot/pilot/db_init.py", line 3, in <module>
    from database.database import create_tables, drop_tables
  File "/home/ces-user/Desktop/gpt-pilot/pilot/database/database.py", line 1, in <module>
    from playhouse.shortcuts import model_to_dict
ModuleNotFoundError: No module named 'playhouse'
`

**Comment by ces-hoangdao** [comment]
playhouse is a part of the peewee package, see [github.com/coleifer/peewee/blob/master/setup.py#L145-L146](https://github.com/coleifer/peewee/blob/master/setup.py#L145-L146) -- if you pip install peewee then playhouse is already installed

**Comment by ces-hoangdao** [comment]
- `pip install --upgrade prompt-toolkit  `
- `pip install --upgrade questionary `
- `pip install --upgrade yaspin `

**Comment by LeonOstrez** [comment]
if i see correct, nothing is missing in requirements.txt. Do you still have that issue or is was it solved once you did `pip install ...` ?

**Comment by ces-hoangdao** [comment]
@LeonOstrez  I don't know but once I did all comment above it run correctly

**Comment by Tzahile** [comment]
I got this error as well when I tried running `python db_init.py`.
Turns out I wasn't `source`'d on the `venv` (I closed and opened my terminal..)

```shell
source ./pilot-env/bin/activate
cd pilot
python db_init.py
```

**Comment by fluxthedev** [comment]
It seems that there are 2 requirements files, one at the root and one inside ./pilot. The app ran fine when I ran `pip install -r requirements.txt` both places.

**Comment by nalbion** [comment]
@LeonOstrez do we need both `requirements.txt` files?

**Comment by LeonOstrez** [comment]
requirements.txt inside pilot folder has been removed
