### ISSUE TITLE
[Enhancement]: Add Support for Open LLMs ..

### ISSUE THREAD

**Issue by dannycoin** [Pythagora-io/gpt-pilot#640]
### Version

VisualStudio Code extension

### Suggestion

Please add support for open LLMs compatible with endpoint API for LLM Studio / ollama / etc.

**Comment by AtHeartEngineer** [comment]
https://github.com/Pythagora-io/gpt-pilot/issues/404#issuecomment-1868489641

**Comment by rikbon** [comment]
Sorry to up this problem, but since updating to the new version of VS Code Plugin (Pythagora) I get this error

**[2024-03-12 16:36:16.958] [ERROR] Unexpected endpoint or method. (POST /v1). Returning 200 anyway**

Tried LM Studio and Ollama... previous version worked fine!

**Comment by Wladastic** [comment]
I fixed it, now it works with oobabooga textgeneration webui API:
edit file: gpt-pilot/pilot/utils/llm-connection.py:
lines 415 to 442:
   if endpoint == 'AZURE':
        # If yes, get the AZURE_ENDPOINT from .ENV file
        endpoint_url = os.getenv('AZURE_ENDPOINT') + '/openai/deployments/' + model + '/chat/completions?api-version=2023-05-15'
        headers = {
            'Content-Type': 'application/json',
            'api-key': get_api_key_or_throw('AZURE_API_KEY')
        }
    elif endpoint == 'OPENROUTER':
        # If so, send the request to the OpenRouter API endpoint
        endpoint_url = os.getenv('OPENROUTER_ENDPOINT', 'https://openrouter.ai/api/v1/chat/completions')
        headers = {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + get_api_key_or_throw('OPENROUTER_API_KEY'),
            'HTTP-Referer': 'https://github.com/Pythagora-io/gpt-pilot',
            'X-Title': 'GPT Pilot'
        }
        data['max_tokens'] = MAX_GPT_MODEL_TOKENS
        data['model'] = model
    else:
        # If not, send the request to the OpenAI endpoint
        endpoint_url = os.getenv('OPENAI_ENDPOINT', 'https://api.openai.com/v1/chat/completions')
        headers = {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + get_api_key_or_throw('OPENAI_API_KEY')
        }
        data['model'] = model
        if endpoint_url != 'https://api.openai.com/v1/chat/completions':
            data['mode'] = "instruct"

**Comment by Wladastic** [comment]
@hqnicolas  deepseek is horrible for this.
I dont even get a proper JSON,
I found a few to be working perfectly:
-gemma it 2B q8_0 gguf
- Mistral 7b pro 7b gguf (Works best so far, but only for json generation, codellama is better for text)
-codellama-7b-instruct.Q5_K_M.gguf
- Neural chatv3.3

**Comment by hqnicolas** [comment]
gemma:7b-text-q8_0
gemma:7b-instruct-q8_0
codellama:7b-instruct-fp16
codellama:7b-instruct-q5_K_M
Testing here.... will edit this comment pointing whats working on 7800XT

**Comment by Wladastic** [comment]
I am not sure what causes this, but whatever llm model I use, I keep getting those at the end of very clean responses:

                    },
                    "human_intervention_description": "Create a directory in root.",
                },
            },
        ]
    }
}
```
```
```

"
"Tower
##
##
                
##
## 1/
##  "Add  "Rem
##
    "Data
​
###  "Redissh
##  "L1
   "Depar---designer
    "and
  "Designb1 0 proposed
##
   Dynamic showed
"
    "Current 
    "F###
"D
  "##
#### 

##
## <dummy00014>w4 1
d  ion
##
##
   A------- - -F
 
## 
   	Accid0   Custom
        "
    */
                
## 	b   B This
##
                
   A

**Comment by hqnicolas** [comment]
@Wladastic i'm using:
**nous-hermes2:10.7b-solar-q6_K**
with OpenDevin 
it works fine!

**Comment by Wladastic** [comment]
I cannot confirm this with gpt-pilot.
For Gpt-Pilot what worked best now is still:
nous-hermes 2 pro 7b gguf with Q8_0 Quant

But very important: set n_batch and alpha value to those in my screenshot.
Context length has to be as much as possible but my RTX 4080 does not handle more than 17k with n_batch being on 1024.
<img width="714" alt="image" src="https://github.com/Pythagora-io/gpt-pilot/assets/11997278/7b6b0b39-9097-46ff-ac14-dc05b7afd12b">

**Comment by hqnicolas** [comment]
@Wladastic 
my model was running on AMD ROCm RX7800XT it's an 16GB Card
I will try to emulate this values on my Ollama
will use you parameters based on this https://github.com/ollama/ollama/blob/main/docs/modelfile.md

**Comment by piwi3910** [comment]
@Wladastic do you have any other magic to share. I've done your code share. 
Used my own preset with the temp on 1
and set al the settings like on your screenshot and running the same model
However i can't even get through the example application,
so i'm not sure what i'm missing to get decent json out of it. it's still looping like crazy

![image](https://github.com/Pythagora-io/gpt-pilot/assets/12539757/8c6e00ea-873f-49b4-ac57-e61ad9f3b7e0)

**Comment by Wladastic** [comment]
@piwi3910  Yes I do.
To fix this issue you have to edit the invalid_json.prompt which is inside gpt-pilot/pilot/prompts/utils/invalid_json.prompt

The last sentence in there is stupid, as giving negative examples is the worst thing you should do.
Change it to this:
`I received an invalid JSON response. The response was a parseable JSON object, but it is not valid against the schema I provided. The JSON is invalid {{ invalid_reason }}

Please try again with a valid JSON object, referring to the previous JSON schema I provided above.

Respond in JSON ONLY, DO NOT ADD ANYTHING ELSE.
`

**Comment by phalexo** [comment]
> I cannot confirm this with gpt-pilot. For Gpt-Pilot what worked best now is still: nous-hermes 2 pro 7b gguf with Q8_0 Quant
> 
> But very important: set n_batch and alpha value to those in my screenshot. Context length has to be as much as possible but my RTX 4080 does not handle more than 17k with n_batch being on 1024. <img alt="image" width="714" src="https://private-user-images.githubusercontent.com/11997278/318279644-7b6b0b39-9097-46ff-ac14-dc05b7afd12b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MDgxNzYsIm5iZiI6MTcxMjUwNzg3NiwicGF0aCI6Ii8xMTk5NzI3OC8zMTgyNzk2NDQtN2I2YjBiMzktOTA5Ny00NmZmLWFjMTQtZGMwNWI3YWZkMTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE2Mzc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyM2RjODdlMWFmNjI2NGRmYjUzNjkwMjViMDA2MzExODc5YzI4YmNmMmVlNDMyYTE0NjhkZjgyNzcwMTcyZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lfXPhirN4o5MR2YIDdC8t1SRLez0B8OuGD85Ot7Ubs8">

@Wladastic , what is the difference between Gpt-Pilot and gpt-pilot, if any? When you say it worked with "hermes........," did it poroduce code that was runnable and what you requested? Or does it mean you were simply able to connect to the model?

Thanks.

**Comment by Wladastic** [comment]
@phalexo  The code is runnable.
Gpt-Pilot (no difference to gpt-pilot, my iphone kept adding Caps) works best with the non quantized version of Mistral-7B v0.2 and Hermes 2 Pro.
You can connect to any model, no idea what that question is supposed to suggest?

**Comment by phalexo** [comment]
Some people think that if you can connect to a local API it actually works.
I just wanted to make certain that  Mistral-7B v0.2 and Hermes 2 Pro "work"
in the sense of
successfully generating code, that runs.

**Comment by Wladastic** [comment]
It does work, these models do generate actual code. 
the quantised models sometimes get stuck if they produce too much context but the unquantised just so not produce more than they can handle so far

**Comment by phalexo** [comment]
What is your setup? Do you use ollama and define a system prompt for the
models in the import file? Or do you use some litellm/ollama setup? Did you
ollama to pull the model weights directly to disk or
did you download the weights first and then use ollama to import them?
Thanks.

**Comment by Wladastic** [comment]
There is not only ollama and litellm.
I use both oobabooga text gen webui with api enabled which emulates the openai api.
LMStudio and I wrote my own adapter based on the function calling repo from noushermes on github.
Oobabooga works best so far as it offers the most compatibility and I cannot get a pure transformers model to run in ollama.

**Comment by phalexo** [comment]
As far as the custom adapter is concerned, you implemented a specific set
of functions that gpt-pilot uses and is implemented by OpenAI API?
Is the adapter part of gpt-pilot code in your implementation, or you made
it into a separate service?

**Comment by techjeylabs** [comment]
Hey there, by now local LLMs can be fully integrated. closing this issue therefore. You can learn more about how to implement local LLMs here -> https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT%E2%80%90Pilot-with-Local-LLMs
