### ISSUE TITLE
[Howto]: Remove the \n and the \ from my outputs

### ISSUE THREAD

**Issue by JunkBoy76** [Pythagora-io/gpt-pilot#665]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### Your question

For some reason I get responses like this:
![image](https://github.com/Pythagora-io/gpt-pilot/assets/76748776/4ecda298-e0e1-40f1-8928-a86b87300213)

I am using Lm Studio and I asked on the discord and we could not figure it out ether

**Comment by Chillthrower** [comment]
I believe I know the solution for this. just navigate to the settings of the gpt-pilot extension and look for an option related to output formatting or processing. There should be an option to remove extra characters such as backslashes or newlines.

**Comment by techjeylabs** [comment]
its not a gpt-pilot problem, its more a model related issue taht is inacapable of handling the requests. therefore i am goin to close this issue.
