### ISSUE TITLE
[Bug]: File "d:\gpt-pilot\pilot\utils\llm_connection.py", line 10, in  from jsonschema import validate, ValidationError  ModuleNotFoundError: No module named 'jsonschema'

### ISSUE THREAD

**Issue by jakers1792** [Pythagora-io/gpt-pilot#681]
### Version

VisualStudio Code extension

### Operating System

Windows 10

### What happened?

It was working fine until i started over and then this happened and it cant find the jsonschema module

**Comment by techjeylabs** [comment]
thread beeing inactive, closing therefore
