### ISSUE TITLE
[Enhancement]: Have it stop the process with CTRL C not kill everything.

### ISSUE THREAD

**Issue by cranyy** [Pythagora-io/gpt-pilot#682]
### Version

VisualStudio Code extension

### Suggestion

It will often start doing very stupid and clearly wrong things which I would like to stop and kill with CTRL c, not the entire process. IT should be once for stopping twice for killing.

**Comment by techjeylabs** [comment]
duplicate: https://github.com/Pythagora-io/gpt-pilot/issues/697
