### ISSUE TITLE
[Howto]: How do I get it to recognize the Dart installation

### ISSUE THREAD

**Issue by Real-Experienes** [Pythagora-io/gpt-pilot#685]
### Version

VisualStudio Code extension

### Operating System

Windows 10

### Your question

How do I get it to recognize the Dart installation? It runs the command, finds the version of Dart that is installed but then turns right around and claims that it is not installed. How do I remedy this? Please advise. Check out the screenshot.

"? Can I execute the command: `dart --version` with 10000ms timeout? 

answer: 
CLI OUTPUT:Dart SDK version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "linux_x64"
BUG

Dev step 2

BUG

❌ Dart (Dart SDK, required by Flutter for app development.) is not available. Please install it before proceeding with your app.
? When you're ready to proceed, press ENTER to continue.                                                  
? We would appreciate if you let us store your initial app prompt. If you are OK with that, please just pr
ess ENTER "

![Screenshot from 2024-02-27 05-24-27](https://github.com/Pythagora-io/gpt-pilot/assets/8176497/3463dd1f-ef1b-4c7e-9e1c-f1792c32ca11)

**Comment by techjeylabs** [comment]
hey there you need to make sure the dart path is known in the venv of your gpt-pilot, therefore checjk your venv folder in your gpt-folder.

**Comment by techjeylabs** [comment]
closing this after inactivity.
