### ISSUE TITLE
[Enhancement]: Is there a plan to support MySQL?

### ISSUE THREAD

**Issue by cntyt** [Pythagora-io/gpt-pilot#696]
### Version

Command-line (Python) version

### Suggestion

Is there a plan to support MySQL?

**Comment by KevinGeLe** [comment]
If I remember correctly, back when I used ran GPT-Pilot on Windows. I had MySQL as a database.

**Comment by techjeylabs** [comment]
hey there we allready support postgresql, you can find that in the .env of your gpt-pilot, therefore closing this request
