### ISSUE TITLE
Was this designed for dark mode?

### ISSUE THREAD

**Issue by huyz** [Pythagora-io/gpt-pilot#70]
I can't read the text:
![screenshot 2023-09-08T093532Z](https://github.com/Pythagora-io/gpt-pilot/assets/128394/415e2571-6c9e-4691-833e-0f7be2178243)

**Comment by LeonOstrez** [comment]
yes indeed, thanks for opening the issue! I will notify you here once its fixed.

**Comment by saaagar10** [comment]
i want to work on this
