### ISSUE TITLE
How do i get Pythagora to modifiy exsiting code base

### ISSUE THREAD

**Issue by RedWilly** [Pythagora-io/gpt-pilot#718]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### Your question

How do i get Pythagora to modifiy exsiting code base am looking for a way to get Pythagora to modify existing code base/repo / folder

**Comment by techjeylabs** [comment]
hey there, i am sorrry to say but there is no such function. 

Can I use this for an existing project?
Not yet. This is on our todo list, but currently you need to start the project with GPT Pilot. After finishing project with GPT Pilot, you are able to add additional features/changes to it, but at this moment you can't just open an existing project you built or downloaded from elsewhere and point GPT Pilot to it.

https://github.com/Pythagora-io/gpt-pilot/wiki/Frequently-Asked-Questions#can-i-use-this-for-an-existing-project
