### ISSUE TITLE
Add support for Vertex AI

### ISSUE THREAD

**Issue by haseeb-heaven** [Pythagora-io/gpt-pilot#72]
**_If you are looking for a powerful and affordable platform for text generation, I highly recommend Vertex AI._**

Vertex AI offers a variety of generative models, such as Text Bison, Chat Bison, Code Generation, Code Chat, and Code Completion. These models are fine-tuned for code generation, code chat, and code completion.

The pricing for Vertex AI generative models is very reasonable compared to OpenAI. You only pay for the input and output characters that you use, and the price per 1,000 characters is $0.0005 for most models.[Vertex AI Pricing](https://cloud.google.com/vertex-ai/pricing)

[Vertex AI Code Models](https://cloud.google.com/vertex-ai/docs/generative-ai/code/code-models-overview)

**Comment by LeonOstrez** [comment]
Thank you for suggestion, we will definitely look into it!

**Comment by haseeb-heaven** [comment]
This [Medium Article](https://medium.com/google-cloud/generative-ai-pricing-openai-vs-google-cloud-8fe708a5636a) is for reference now.

**Comment by nalbion** [comment]
GPT Pilot now supports [OpenRouter](https://openrouter.ai/docs#models) which includes Google PaLM 2 Bison at $0.0005/1k tokens

**Comment by haseeb-heaven** [comment]
> OpenRouter

Okay if its already implemented then we can close this issue
