### ISSUE TITLE
[Enhancement]: gpt-pilot should support taking a public or local repo as starter-code or inspiration

### ISSUE THREAD

**Issue by therohitdas** [Pythagora-io/gpt-pilot#720]
### Version

VisualStudio Code extension

### Suggestion

Hey there,

First off, kudos on the success with GPT-Pilot and the Y Combinator backing!

While experimenting with GPT-Pilot and exploring projects like [CodeWhisperer](https://github.com/Pythagora-io/gpt-pilot/wiki/Apps-created-with-GPT-Pilot#code-whisperer-demo), I came up with a couple of suggestions to enhance its functionality:

1. **Enhanced Repo Integration Skill:**
   - Enable GPT-Pilot to fetch GitHub repos or local paths specified in the prompt.
   - Store fetched repos in a hidden directory like `.gpt-pilot`.
   - This skill would facilitate code retrieval for agents, allowing them to utilize familiar project structures and reduce token usage.

2. **Textual Description Generation Skill:**
   - Develop a skill for generating and reading textual descriptions from fetched code.
   - Store these descriptions in the `.gpt-pilot` directory for agents requiring context without direct code access.

Here's how these skills could be put into action:

- **For Serial Indie-Hackers/Product Makers/Founders:**
  - They can instruct GPT-Pilot to utilize their starter-code repo via URL in the initial prompt.
  - This would enable GPT-Pilot to generate code and architecture based on familiar patterns, potentially reducing token usage and expenses.
  - Addition of a sub-skill for copy-pasting could further simplify tasks like file-based copying.

- **Language Conversion Scenarios:**
  - Suppose there's an SDK, API wrapper, or Unofficial API wrapper available in one programming language, and the user desires it in another language.
  - For instance, converting a Python tool like [youtube-transcript-api](https://github.com/jdepoix/youtube-transcript-api) into JavaScript.
  - The Writer Agent can create a descriptive prompt specifying the conversion task, while other agents leverage this prompt along with access to fetched code to generate corresponding steps or code in the desired language.

These enhancements would significantly augment GPT-Pilot's versatility and usability across various development scenarios.

**Comment by techjeylabs** [comment]
https://github.com/Pythagora-io/gpt-pilot/wiki/Frequently-Asked-Questions#can-i-use-this-for-an-existing-project
