### ISSUE TITLE
[Bug]: .env not respected

### ISSUE THREAD

**Issue by peterkelly70** [Pythagora-io/gpt-pilot#722]
### Version

Command-line (Python) version

### Operating System

Ubuntu Linux

### What happened?

If I have an OpenAI key specified in my environment already, it will use that key over the one specified in .env file. I believe you need: load_dotenv(override=True) rather than load_dotenv(), to always respect the variables set in the .env file.

**Comment by senko** [comment]
Thanks for reporting @peterkelly70 !

We fixed this later in https://github.com/Pythagora-io/gpt-pilot/commit/8f6e5936281dc38949eb676004b06762161bf405 but forgot to close this issue.
