### ISSUE TITLE
[Bug]: GPT Pilot is not completely set up: required package "python-dotenv" is missing.

### ISSUE THREAD

**Issue by pacnimo** [Pythagora-io/gpt-pilot#723]
### Version

VisualStudio Code extension

### Operating System

Ubuntu Linux

### What happened?

gpt-pilot/pilot/main.py", line 12, in <module>
    raise RuntimeError('Python environment for GPT Pilot is not completely set up: required package "python-dotenv" is missing.') from None
RuntimeError: Python environment for GPT Pilot is not completely set up: required package "python-dotenv" is missing.

Ubuntu 22.04.3 LTS
pip3 install python-dotenv
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-dotenv in /home/tv0/.local/lib/python3.10/site-packages (1.0.0)

**Comment by terrynunn** [comment]
Same issue after trail expired and added own api key,

Traceback (most recent call last):
  File "c:\Users\nunnt\.vscode\extensions\Pythagora\gpt-pilot\pilot\main.py", line 12, in <module>
    raise RuntimeError('Python environment for GPT Pilot is not completely set up: required package "python-dotenv" is missing.') from None
RuntimeError: Python environment for GPT Pilot is not completely set up: required package "python-dotenv" is missing.

**Comment by jyashi** [comment]
Me too

`(base) navtejdhot@Navtej-Dhot pilot % python main.py --get-created-apps-with-steps
Traceback (most recent call last):
  File "/Users/navtejdhot/Documents/GitHub/gpt-pilot/pilot/main.py", line 12, in <module>
    raise RuntimeError('Python environment for GPT Pilot is not completely set up: required package "python-dotenv" is missing.') from None
RuntimeError: Python environment for GPT Pilot is not completely set up: required package "python-dotenv" is missing.`

**Comment by yuanjun5681** [comment]
me too 

Traceback (most recent call last):
  File "d:\DevelopAPP\gpt-pilot\pilot\main.py", line 12, in <module>
    raise RuntimeError('Python environment for GPT Pilot is not completely set up: required package "python-dotenv" is missing.') from None
RuntimeError: Python environment for GPT Pilot is not completely set up: required package "python-dotenv" is missing.

**Comment by techjeylabs** [comment]
they there this is a duplicate to https://github.com/Pythagora-io/gpt-pilot/issues/387

When setting up GPT-Pilot VSCode extension in windows, one of the steps is to create the Python virtual environment (venv).
This can fail (for as of yet unknown reason), and this is what the users see:
[image](https://private-user-images.githubusercontent.com/3362/292340111-7dbd5926-c94b-404c-b1eb-eaaef606c701.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MDAxNDYsIm5iZiI6MTcxMzU5OTg0NiwicGF0aCI6Ii8zMzYyLzI5MjM0MDExMS03ZGJkNTkyNi1jOTRiLTQwNGMtYjFlYi1lYWFlZjYwNmM3MDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjBUMDc1NzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTdiOGE0YmJkNThjOTMyNGExMTQ5ZTJjYWFmZGU2OWYzM2Y4MDYzYWZjMTk5Nzc3ZGQyNzk0NDA2YmRkMzFiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eg6ovOgVMV0NF7d6MzoeazN3zGof_STKH1Qj7IcKPzs)
Temporary workaround:
1. open command line in the gpt-pilot sub-directory of the folder which you selected for the installation of GPT Pilot (there should be requirements.txt file already there)
2. create the virtual environment with python -m venv pilot-env
3. activate the environment with pilot-env\Scripts\activate
4. install packages with pip install -r requirements.txt
5. go to the pilot subdirectory (not pilot-env, just pilot). If there is gpt-pilot file in that subdirectory delete it (that is sqlite database) and then run python db_init.py to initialize new database
After doing the above steps, the VSCode extension should start working.
