### ISSUE TITLE
Benchmarking using Auto-GPT/agbenchmark

### ISSUE THREAD

**Issue by nalbion** [Pythagora-io/gpt-pilot#73]
I've started working on benchmarking here:

https://github.com/nalbion/gpt-pilot/tree/feature/agbenchmark/agbenchmark

I need to figure out how to get the benchmark script to provide responses - probably using another LLM.

> Response message: Where should the .txt file containing the word 'Washington' be stored or saved?

![image](https://github.com/Pythagora-io/gpt-pilot/assets/1866161/f83f39fe-cf78-4211-9c90-c66030e18640)
https://lablab.ai/event/autogpt-arena-hacks

 - [ ] #91
 - [ ] https://github.com/Significant-Gravitas/Auto-GPT/pull/5184
 - [ ] #89 - Bonus points

**Comment by nalbion** [comment]
For this benchmarking (and other things I've mentioned in #68) to work, I think the first interaction with the LLM needs to be with a Concierge/Receptionist to route you to the agent who can best serve your needs..

The prompt might go something like:

> You are a receptionist of a software development company. You job is to answer the phone and direct the caller to an agent with the most suitable role to handle the request.
> ProductOwner talks to clients who have a high-level idea for a new software project that they would like to be designed and developed. The ProductOwner gathers requirements from the client and prepares project specifications for the dev team.
> Architect analyses project specifications and selects the most appropriate technologies to be used in a project.
> TechLead breaks down the project requirements into smaller tasks for the developers. 
> Developer implements tasks defined by the TechLead and develops modular code.
> CodeMonkey reads files and implements changes.

...I'm not sure how you wire in the `function_calls` to all of this...

Ideally, I'd like to be able to run GPT Pilot in an existing project and ask it things like:

- Write unit tests for AgentConvo.py
- Add a new `GET /user/details` endpoint to the user controller

The Auto-GPT benchmark system has various challenges that are intended to test a GPT app's ability to perform these types of activities:

## Write to file

> Write the word 'Washington' to a .txt file

This should just follow the user's simple instruction. Actually, because the file name is provided, the test would pass if the LLM chose the file name, but I would expect GPT Pilot to ask the user "what should the file be named?" and possibly the path to save the file (although ideally it would know that it needs to save everything to the project workspace).

Currently when I run gpt-pilot with this prompt it's leaping straight into over-engineering mode:

> Should the app automatically generate the .txt file upon running, or should there be a user interaction to trigger the word 'Washington' being written to a .txt file? 

> Do you want the application to create a new .txt file every time it runs, or should it overwrite the previous file it created?

> Will the word to be written to the .txt file always be 'Washington', or should the user be able to specify the word?

## Read from file

> Read the file called file_to_read.txt and write its content to a file called output.txt

This should be very straight-forward and easy to follow the user's clear instructions, but again it's over-engineering:

> Does the app "foo" need to handle a specific file format or can it be any text file?

> Does the application need to have a user interface or will it be run from the command line interface?

> Does the application need to support different types or sizes of files, or will it always be a .txt file?

## Memory

> Remember the following goal no matter what: 'Make as many paperclips as possible while keeping humanity safe'. Start by reading instructions.txt

A "goal" in Auto-GPT is similar to a "task" in GPT-Pilot.
`instructions.txt` contains some distracting text, and then says "IMPORTANT: Please print your original goal to a file called goal.txt"

## Web scraping
> Open 'https://silennaihin.com/random/plain.html' and paste all of the text on the page in a .txt file

I guess this would use a function_call to scrape the text (ignoring HTML markup)

## Code generation - Three Sum

> Create a three_sum function in a file called sample_code.py. Given an array of integers, return indices of the three numbers such that they add up to a specific target. You may assume that each input would have exactly one solution, and you may not use the same element twice. Example: Given nums = [2, 7, 11, 15], target = 20, Because nums[0] + nums[1] + nums[2] = 2 + 7 + 11 = 20, return [0, 1, 2].

**Comment by nalbion** [comment]
The first 2 challenges could be solved by calling the CodeMonkey directly.

https://github.com/Pythagora-io/gpt-pilot/pull/82/files#diff-d65eea6fccc81746df8b78236f7b98d2a8cdc35ef33d89a9c4beda178628838aR50

**Comment by LeonOstrez** [comment]
Re: benchmarks
we will not use Auto-GPT for benchmarking. Creating new task for setting up benchmark architecture.

Re: overengineering
currently we see gpt-pilot as dev-tool that help create applications. It is not meant to be used for simple prompts like `Write the word 'Washington' to a .txt file`

Re: Code generation
we will add option for user to pick what he wants to create using gpt-pilot and "scripts" will be one of them but going lower to functions is not what gpt-pilot is meant to be used for.
