### ISSUE TITLE
2000ms timeout insufficient for dependency installs

### ISSUE THREAD

**Issue by tconroy** [Pythagora-io/gpt-pilot#75]
Awesome work on gpt-pilot! 

I am trying to have it create a node/JS project. A few things I've observed:
1. some dependencies it generated are not valid NPM dependencies, so it errors out while trying to install. Is there a way for me to override this?
2. when doing `npm install`, the timeout of 2000ms is too short for dependencies to install, causing the step to error out and debugging to start

example of 1:
```
--------- EXECUTE COMMAND ----------
Can i execute the command: `npm install --save-dev okta-oidc-js @okta/jwt-verifier @okta/okta-react` with 30000ms timeout?
Restoring user input id 15:
t: 10695ms : CLI ERROR:npm ERR! code E404
t: 10697ms : CLI ERROR:npm ERR! 404 Not Found - GET https://registry.npmjs.org/okta-oidc-js - Not found
t: 10697ms : CLI ERROR:npm ERR! 404
t: 10697ms : CLI ERROR:npm ERR! 404  'okta-oidc-js@*' is not in this registry.
t: 10697ms : CLI ERROR:npm ERR! 404
t: 10697ms : CLI ERROR:npm ERR! 404 Note that you can also install from a
t: 10697ms : CLI ERROR:npm ERR! 404 tarball, folder, http url, or git url.
t: 10697ms : CLI ERROR:
t: 10697ms : CLI ERROR:npm ERR! A complete log of this run can be found in: /Users/tom/.npm/_logs/2023-
Saving file /package.json

Dev step 18

NEEDS_DEBUGGING
```

Example of 2
```
Can i execute the command: `npm install --save-dev okta-oidc-js @okta/jwt-verifier @okta/okta-react` with 2000ms timeout?
Restoring user input id 11:
t: 2000ms :
Saving file /package.json

Dev step 11

NEEDS_DEBUGGING

Got incorrect CLI response:
stdout:
```

```
```

It might be good to allow the timeout to be user-configurable?

**Comment by nalbion** [comment]
The timeout is suggested by the LLM. We could retry with an longer timeout, but ideally the user would be able to provide free-form input for the LLM such as

> My computer is slow, it's going to take 10 minutes.

or

> Don't use @okta/okta-react, use @me/okta-react

**Comment by HIMA-MB02** [comment]
Hey @nalbion 
What if we asked the LLM to use yarn to manage dependencies?
Installation of parallel dependencies will definitely improve install times.
Additionally, can we ask the LLM to batch installations of dependencies?
We could define a threshold for max number of dependencies that can be installed in one command.

I am interested in picking this up, happy to discuss further

**Comment by nalbion** [comment]
@HIMA-MB02 is Yarn still considered to be superior to NPM? or PNPM? or Bun?

...In any case, these are all very specific to the JavaScript world. People are using GPT Pilot with Unity, Python, Kotlin and potentially the next big language/framework.

You could probably include "use yarn for dependency management" in the original prompt, or add the `--advanced` arg when running and it will ask for further discussion on the technologies proposed.

There's a lot of room for improvement in "advanced" mode.  I think that it should (be able to) explain why it's chosen each technology and allow you to have a discussion and either say "ok" or insist on a different choice/s.

https://github.com/Pythagora-io/gpt-pilot/issues/78

**Comment by HIMA-MB02** [comment]
Yarn is still quite superior than NPM, but Bun is the new kid on the block. It's very promising, but it is still too early to say. They don't have complete 100% support for Node.js yet, as we speak today.

Nevertheless, this is case specific, and I believe the solution you've provided should work.

Alternatively, what do you think about a "de-bugger" persona, that can possibly handle such decisions automatically, without having the developer involved?
Just one additional layer of checks, before the LLM requests for the developer to get involved.

**Comment by nalbion** [comment]
Yes, we can add other personas, but I think for this time out we could feedback to the LLM that the process timed out. Maybe it will try again with a longer timeout
