### ISSUE TITLE
[Enhancement]: support for Claude 3 models in GPT Pilot

### ISSUE THREAD

**Issue by ShivamB25** [Pythagora-io/gpt-pilot#751]
### Version

VisualStudio Code extension

### Suggestion
I would like to request adding support for Anthropic's latest Claude 3 model family, particularly Claude 3 Opus, to further enhance the AI development capabilities of the tool.
Reasons for adding Claude 3 support:
1. Larger context window: Claude 3 offers an industry-leading 200K token context window, compared to GPT-4's 32K. This allows processing much larger codebases and repositories, enabling GPT Pilot to understand and generate code for more extensive projects.
2. Enhanced code quality: Based on user reports, Claude models tend to produce higher quality, bug-free code compared to GPT-3.5 or 4[6]. Claude 3's strong performance on coding benchmarks like HumanEval suggests it could help GPT Pilot write cleaner, more efficient code out of the box.
3. Improved instruction following: Claude 3 is known for its superior instruction following capabilities[12]. This could enable developers to provide more specific, nuanced instructions to GPT Pilot and get desired code outputs with fewer iterations.

I believe incorporating Claude 3, with its exceptional language understanding and generation capabilities, will unlock new possibilities for GPT Pilot and greatly benefit its developer community. Looking forward to this powerful upgrade to an already impressive tool!

**Comment by senko** [comment]
Thanks for the suggestion @ShivamB25 - implemented in #759, see here for how to set it up: https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT-Pilot-with-Anthropic-models

**Comment by ShivamB25** [comment]
@senko  
<img width="607" alt="Screenshot 2024-03-23 at 12 27 51 AM" src="https://github.com/Pythagora-io/gpt-pilot/assets/104637569/02698f65-cc1e-4405-9951-6c282e57416e">
<img width="597" alt="Screenshot 2024-03-23 at 12 28 01 AM" src="https://github.com/Pythagora-io/gpt-pilot/assets/104637569/09a934f4-4414-495c-8f8f-0c997d700c33">

```yaml
# OPENAI or AZURE or OPENROUTER (ignored for Anthropic)
ENDPOINT=OPENAI

# OPENAI_ENDPOINT=https://api.openai.com/v1/chat/completions
OPENAI_ENDPOINT=
OPENAI_API_KEY=

AZURE_API_KEY=
AZURE_ENDPOINT=

OPENROUTER_API_KEY=

# Set this to use Anthropic API directly
# If using via OpenRouter, OPENROUTER_API_KEY should be set instead
ANTHROPIC_API_KEY=sk-ant--]m-api-key
# You only need to set this if not using Anthropic API directly (eg. via proxy or AWS Bedrock)
# ANTHROPIC_ENDPOINT=

# In case of Azure/OpenRouter endpoint, change this to your deployed model name
#MODEL_NAME=gpt-4-turbo-preview
# In case of Anthropic, use "anthropic/" + the model name, example for Claude 3 Opus

MODEL_NAME=anthropic/claude-3-opus-20240229
MAX_TOKENS=8192

# Folders which shouldn't be tracked in workspace (useful to ignore folders created by compiler)
# IGNORE_PATHS=folder1,folder2

# Database
# DATABASE_TYPE=postgres

DB_NAME=gpt-pilot
DB_HOST=
DB_PORT=
DB_USER=
DB_PASSWORD=

# USE_GPTPILOT_FOLDER=true

# Load database imported from another location/system - EXPERIMENTAL
# AUTOFIX_FILE_PATHS=false

# Set extra buffer to wait on top of detected retry time when rate limmit is hit. defaults to 6
# RATE_LIMIT_EXTRA_BUFFER=
```
it doesn't wants me to go further than this.

**Comment by ShivamB25** [comment]
@senko
