### ISSUE TITLE
[Bug]: Running into problems with JSON parsing whenever using any open source model with Ollama.

### ISSUE THREAD

**Issue by phalexo** [Pythagora-io/gpt-pilot#768]
### Version

Command-line (Python) version

### Operating System

Ubuntu Linux

### What happened?

 I have tested several open source models, deepseek-coder-33b-instruct.Q6_K, deepseek-coder-6.7b-instruct.Q6_K, phind-codellama-34b-v2.Q6_K with ollama providing the OpenAI compatible API. 

They all seem to suffer from having problems either parsing or generating clean JSON format and go into infinite development loops, failing, debugging, and so on.

Has anyone used an open source coder model successfully? What is your recipe? Maybe you have discovered a good system prompt for these models to deal with JSON.

Thanks.

**Comment by phalexo** [comment]
The problem appears to be comments that an LLM may make BEFORE and AFTER formatted JSON.

For example:

Here is JSON formatted ...... Can I help you with something else?

There has to be a filter within gpt-pilot that does a RegEx on \`\`\`json ..... \`\`\` tags.

**Comment by phalexo** [comment]
Even after changed prompting that reduced the problem with JSON formatting, actual useful function using phindcodellama and deepseek33b is pretty much non-existent. It seems that gpt-pilot is optimized for GPT-4 and that's it. It would make sense if the software relies on prompt engineering.

**Comment by senko** [comment]
Using GPT Pilot with local LLMs is challenging as they're just not there yet. ... see https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT%E2%80%90Pilot-with-Local-LLMs if you haven't already

We also have an active [Discord community](https://discord.gg/HaqXugmxr9) and a `#local-llm` channel dedicated for discussing local LLMs.
