### ISSUE TITLE
[Bug]: There was a problem with request to openai API for LMstudio

### ISSUE THREAD

**Issue by nothingness6** [Pythagora-io/gpt-pilot#769]
### Version

VisualStudio Code extension

### Operating System

Windows 10

### What happened?

I followed this instruction, https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT%E2%80%90Pilot-with-Local-LLMs, and changed .env file as following to use LMstudio:
```
OPENAI_ENDPOINT=http://localhost:1234/v1/chat/completions
OPENAI_API_KEY=dummy
```

After I launched main.py, this error messages showed up:
```
There was a problem with request to openai API:
API responded with status code: 500. Request token size: 23 tokens. Response text: {"error":"Model with key 'gpt-4-turbo-preview' not loaded."}
```

**Comment by senko** [comment]
You might need to update `MODEL_NAME` based on your LM Studio settings.

In general, if you want to run GPT Pilot with local LLMs, this is going to involve a lot of tweaking (as mentioned in the linked wiki page). We have an active community in the `#local-llm` in [our Discord community](https://discord.gg/HaqXugmxr9) and I encourage you to join and discuss your experiments with, and get help from, the other people in there.
