### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by zacreinke** [Pythagora-io/gpt-pilot#770]
### Version

VisualStudio Code extension

### Operating System

MacOS

### What happened?

OpenAI API Key documentation is incorrect. Says "OPENAI_KEY" when it should say "OPENAI_API_KEY"
https://github.com/Pythagora-io/gpt-pilot/wiki/Using-Pythagora-with-your-own-OpenAI-key

**Comment by senko** [comment]
Thanks, fixed.
