### ISSUE TITLE
[Bug]: Claude 3 api usage still generally unstable.

### ISSUE THREAD

**Issue by luyandadhlamini2** [Pythagora-io/gpt-pilot#779]
### Version

Command-line (Python) version

### Operating System

Ubuntu Linux

### What happened?

The addition of Claude 3 support has been great.
The biggest advantage of Claude 3 over current openai models is the costs saving that comes with the smaller claude model (Haiku).

However I've found that Claude is still very prone to producing errors that lead to gpt-pilot crashing.
These errors mostly relate to:
1. Extra data errors (gpt-pilot sometimes struggles with handling responses from Claude models. These are harder to workaround & sometimes require several restarts of a project to overcome)
2. 429 errors (rate limits - which can be fixed by upgrading to a higher tier of Anthropic subscription). 

Some examples in screenshots below
Extra data:
![Screenshot 2024-03-22 070528](https://github.com/Pythagora-io/gpt-pilot/assets/160016656/44f081bd-b22c-4df8-9c48-e252b7c910c5)
None type handling:
![Screenshot 2024-03-22 070502](https://github.com/Pythagora-io/gpt-pilot/assets/160016656/9007b3cd-f47e-4718-a9fb-173d6db44003)

Hopefully some of these issues will be resolved in coming days, with more robust error handling by gpt-pilot.

**Comment by senko** [comment]
@luyandadhlamini2 Haiku is known to struggle in a few places, so using Sonnet or Opus is recommended.
