### ISSUE TITLE
[Howto]: The token calculation is incorrect

### ISSUE THREAD

**Issue by chatterzhao** [Pythagora-io/gpt-pilot#781]
### Version

VisualStudio Code extension

### Operating System

Windows 10

### Your question

I subscribed to Pro - pay-as-you-go today. When I opened VSCode for the first time, I submitted a project name and clicked submit. Then, when I checked the settings, it prompted me that I had consumed so many tokens. Is this an anomaly?

![image](https://github.com/Pythagora-io/gpt-pilot/assets/11829944/16db623c-8973-4c15-b2cf-c906b44043fe)

**Comment by chatterzhao** [comment]
During the trial period, I consumed 100,000 tokens. Will this be counted as payable after subscribing?

**Comment by senko** [comment]
@chatterzhao Yes this shows total usage (including the free trial) as it directly pulls in the usage from our metering system, but the free trial cost will *not* be included in the invoice.

If the amount was like this immediately (before you even started the first project), please reach out to us at hello at pythagora.ai to investigate deeper.
