### ISSUE TITLE
[Howto]: Is the statistics token normal?

### ISSUE THREAD

**Issue by chatterzhao** [Pythagora-io/gpt-pilot#782]
### Version

VisualStudio Code extension

### Operating System

Windows 10

### Your question

The input volume is much larger than the output; is it normal for it to compute?

![image](https://github.com/Pythagora-io/gpt-pilot/assets/11829944/5e8fb518-100c-4f98-af00-d2ede9e877db)

**Comment by senko** [comment]
@chatterzhao yes. we use a very large context for many of the calls, holding all the project state, so this is expected
