### ISSUE TITLE
[Howto]: Long waiting time

### ISSUE THREAD

**Issue by jojozero1** [Pythagora-io/gpt-pilot#791]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### Your question

When I use this plugin in VScode, it is always in a waiting state. I have been waiting for an hour, but it is still in a waiting state.

**Comment by hieutq1912** [comment]
you should try to delete the gpt-copilot folder.

**Comment by ppsdang** [comment]
I have tried deleteing the gpt-copilot folder, but still facing the same issue.
OS - Ubuntu 22.04.4 LTS
Pythagora v0.1.11 / GPT Pilot v0.1.7
Node - 18.19.1

**Comment by techjeylabs** [comment]
hi there 

Temporary workaround:
1. open command line in the gpt-pilot sub-directory of the folder which you selected for the installation of GPT Pilot (there should be requirements.txt file already there)
2. create the virtual environment with python -m venv pilot-env
3. activate the environment with pilot-env\Scripts\activate
4. install packages with pip install -r requirements.txt
5. go to the pilot subdirectory (not pilot-env, just pilot). If there is gpt-pilot file in that subdirectory delete it (that is sqlite database) and then run python db_init.py to initialize new database

duplicate: https://github.com/Pythagora-io/gpt-pilot/issues/387
