### ISSUE TITLE
[Howto]: If I am serving a model directly by runnng llama.cpp server, what should the MODEL_NAME be in .env be?

### ISSUE THREAD

**Issue by phalexo** [Pythagora-io/gpt-pilot#794]
### Version

Command-line (Python) version

### Operating System

Ubuntu Linux

### Your question

If I am serving a model directly by runnng llama.cpp server, what should the MODEL_NAME in .env be?

Also, how do I instruction specific tags into the workflow?

If the model takes <s>[INST] ...[/INST] or any other template, how does this work with prompts provided by gpt-pilot?

**Comment by techjeylabs** [comment]
hey there, just have a look here:

https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT%E2%80%90Pilot-with-Local-LLMs

**Comment by phalexo** [comment]
I am using it now with Llama 3 70b Instruct. Seems to work in general with
some issues every now and then. With a little effort from someone who
already understands gpt-pilot, it could work really well.

p.s. it has better performance than most GPT-4 flavors except one.
