### ISSUE TITLE
[Howto]: Use a shared folder or onedrive to sync project and work from multiple computers

### ISSUE THREAD

**Issue by BinaryBeastMaster** [Pythagora-io/gpt-pilot#795]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### Your question

I write code with my laptop and desktop and use onedrive to sync my projects across devices. I installed gpt-pilot into this onedrive thus all gpt-giles are synced as well. It seems as if the sqlite db is being created for each machine and the software seems to be getting confused.

Is such a setup supported? Are there a best practice for such a configuration?

**Comment by techjeylabs** [comment]
they there, right now there is no official function for that, but you could do it like this:

1.  copy database which you can find on path INSTALLATION_FOLDER/gpt-pilot/pilot/gpt-pilot and past it to a new computer to same path which will overwrite existing database on that computer. NOTE: that means you will lose all projects on that new computer
2. add flag AUTOFIX_FILE_PATHS=true to INSTALLATION_FOLDER/gpt-pilot/pilot/.env on your new computer.
Click Create new app and you should see log "Updating file paths from {old_dir} to {new_dir}"
3. Now you can go back and click Load app. Select app that you want to load and select Latest step
