### ISSUE TITLE
Is anyone aware of a fine-tuned LLM for coding, that does NOT require a special format for system prompting.

### ISSUE THREAD

**Issue by phalexo** [Pythagora-io/gpt-pilot#797]
### Version

Command-line (Python) version

### Operating System

Ubuntu Linux

### Your question

Basically something that I can prompt similarly to GPT-4-turbo, with just text, no special tokens.

**Comment by invisiblepancake** [comment]
poetry will helpå you stable multiple enviorments,. Oslt pyenv (rem ur dir project directories pleas =)

**Comment by techjeylabs** [comment]
closing this after inactivity
