### ISSUE TITLE
[Bug]: Cannot register or sign in

### ISSUE THREAD

**Issue by wehuman** [Pythagora-io/gpt-pilot#803]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### What happened?

It says in the pythagora plugin "read ECONNRESET" everytime as I click on "create your pythagora acconut" button in register, or the "continue" button when I click in the sign in page

**Comment by senko** [comment]
Sounds like your firewall may be blocking access to `api.pythagora.io`.
