### ISSUE TITLE
[Bug]: Installed Pythagora but nothing shows in side bar

### ISSUE THREAD

**Issue by Orr0x** [Pythagora-io/gpt-pilot#806]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### What happened?

I installed the pythagora extension in VS Code and started the setup but didnt finish, now when i try and start the extension the side bar opens but it is blank so I cannot complete the setup.

**Comment by Orr0x** [comment]
Runtime Status
Activation
Activated by onStartupFinished event: 0ms
Uncaught Errors (6)
 EPERM: operation not permitted, mkdir 'c:\Program Files\gpt-pilot\workspace'
 EPERM: operation not permitted, mkdir 'c:\Program Files\gpt-pilot\workspace'
 EPERM: operation not permitted, mkdir 'c:\Program Files\gpt-pilot\workspace'
 EPERM: operation not permitted, mkdir 'c:\Program Files\gpt-pilot\workspace'
 EPERM: operation not permitted, mkdir 'c:\Program Files\gpt-pilot\workspace'
 EPERM: operation not permitted, mkdir 'c:\Program Files\gpt-pilot\workspace

**Comment by senko** [comment]
As an installation directory, please select a directory where your user account can create files and folders without being admin.

**Comment by techjeylabs** [comment]
seems solved, closing after inactivity
