### ISSUE TITLE
[Bug]: Pythagora window not showing up 

### ISSUE THREAD

**Issue by eindas** [Pythagora-io/gpt-pilot#809]
### Version

VisualStudio Code extension

### Operating System

MacOS

### What happened?

After installing Pythogara extention i needed to update my OS. That caused that all my python3 and my Homebrew was not found anymore. i did a full new installation homebrew and python3.
When i try to open the Pythagora extention Visual studio show me this "GPT Pilot is already running, please close current GPT Pilot window"
but i can not see an instant of GPT Pilot.

I deleted the Extentions multipe times, but i never get the start window. It never give me the option to set the Path again.

I tried to change the Path but it did not work, it still show me "EPERM: operation not permitted, mkdir `/usr/bin/gpt-pilot/wokspace'

When i think it is somehow stuck in my old nut used python3 instant.

Terminal:
 ~ % which -a python3
/opt/homebrew/bin/python3
/usr/bin/python3

**Comment by senko** [comment]
When you set the path, you should select a directory that you as a non-admin user has permission to write to, for example `/Users/eindas/Projects/Pythagora` . The path shown here `/usr/bin/...` is normally only writable by the admin (root) user.

**Comment by eindas** [comment]
I tried but I can not set a new path. Deinstalling and installing also always end at this path without the chance to set the path Von meinem iPhone gesendetAm 30.03.2024 um 01:23 schrieb Senko Rašić ***@***.***>:﻿
When you set the path, you should select a directory that you as a non-admin user has permission to write to, for example /Users/eindas/Projects/Pythagora . The path shown here /usr/bin/... is normally only writable by the admin (root) user.

**Comment by techjeylabs** [comment]
Hey there, any updates on this ?

**Comment by techjeylabs** [comment]
closing this after inactivity
