### ISSUE TITLE
[Howto]: Get this thing to work? 

### ISSUE THREAD

**Issue by githarkirat** [Pythagora-io/gpt-pilot#833]
### Version

VisualStudio Code extension

### Operating System

MacOS

### Your question

As easy as you make it sound, setting this up is far more complicated and simply installing the VSC extansion is useless. Half of the times the approach from pythagora is "go figure" or "Read the Fucking Manual". Getting this to start working is the biggest challenge. It is almost like this piece of software is written for people who don't need it (people who can write code themselves), while pretending to be usable for people who do need it (people who understand code, but may not be able to write entire programs themselves). If your target audience is expert programmers, then you should not market this to people who are looking to hire programmers to get something done.

What doesn't work?
1. Installing the extension does nothing, because
2. Python is not installed, installing python does nothing, because
3. GPT-Pilot destination is not defined, Defining the location does nothing, because
4. GPT-Pilot is already running, and no you can't see where is it running.
5. Uninstalling and reinstalling the extension does not work.
6. Uninstalling and reinstalling VS Code doesn't work.

If this is the future of Gen AI, I think our expert programmers shouldn't be scared of losing their jobs, because these guys obviously do not understand the value of a Product Manager or a UX engineer. 

> Product Owner agent like in real life, does nothing.

This belief and statement also the reason why your software does nothing.

**Comment by SeKi81** [comment]
RTFM

**Comment by techjeylabs** [comment]
hi there, it seems like you run into enviroment issues. By now the extension ask you where to install what. Issue closed since its not a pythagora issue
