### ISSUE TITLE
[Bug]: node.js (javascript runtime for building apps. this is required to be able to run the app you're building.) is not available. please intall it before proceeding with your app.

### ISSUE THREAD

**Issue by Jiuv** [Pythagora-io/gpt-pilot#837]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### What happened?

I keep getting "node.js (javascript runtime for building apps. this is required to be able to run the app you're building.) is not available. please intall it before proceeding with your app." as well as for mongodb and docker, they are all installed and work find within vscode and the paths are in the environment variables.

**Comment by techjeylabs** [comment]
sounds like your having issues with PATH

**Comment by techjeylabs** [comment]
closing this after inactivity
