### ISSUE TITLE
Azure openAI not working[Bug]: 

### ISSUE THREAD

**Issue by KermaniMojtaba** [Pythagora-io/gpt-pilot#839]
### Version

VisualStudio Code extension

### Operating System

MacOS

### What happened?

I've set the below config in gpt-pilot/pilot/.env file:

ENDPOINT=AZURE
AZURE_API_KEY= XXXXXXXXXXXXXXX
AZURE_ENDPOINT=XXXXXXXX
MODEL_NAME=gpt-4-turbo

But i get this error:
There was a problem with request to openai API:
API responded with status code: 404. Request token size: 23 tokens. Response text: { "statusCode": 404, "message": "Resource not found" }

I'm able to get responses using the same key& endpoint and model using Python in vscode, but they don't seem to work for Pythagora .

Am i missing something?

Thanks

**Comment by str0tta** [comment]
Hi @KermaniMojtaba,
I have the same issue.

Did you manage to solve by any chance?
Thanks

**Comment by techjeylabs** [comment]
hey there, seems like a 404 from the API, therefore i am gonna close this issue since its not a GPT-Pilot related problem
