### ISSUE TITLE
Developer.implement_task tries to do too much

### ISSUE THREAD

**Issue by nalbion** [Pythagora-io/gpt-pilot#84]
I think that `Developer.implement_task()` is trying to do too much in too quickly.

I've got so many `TODO`s here because I don't understand what/why it is this way.

```python
    def implement_task(self):
        convo_dev_task = AgentConvo(self)
        # TODO: why "This should be a simple version of the app so you don't need to aim to provide a production ready code"?
        # TODO: why `no_microservices`? Is that even applicable?
        task_description = convo_dev_task.send_message('development/task/breakdown.prompt', {
            "name": self.project.args['name'],
            "app_type": self.project.args['app_type'],
            "app_summary": self.project.project_description,
            "clarification": [],
            # TODO: why all stories at once?
            "user_stories": self.project.user_stories,
            # "user_tasks": self.project.user_tasks,
            # TODO: "I'm currently in an empty folder" may not always be true?
            "technologies": self.project.architecture,
            # TODO: `array_of_objects_to_string` does not seem to be used by the prompt template?
            "array_of_objects_to_string": array_of_objects_to_string,
            # TODO: prompt lists `files` if `current_task_index` != 0
            "directory_tree": self.project.get_directory_tree(True),
        })

        task_steps = convo_dev_task.send_message('development/parse_task.prompt', {}, IMPLEMENT_TASK)
        convo_dev_task.remove_last_x_messages(2)
        self.execute_task(convo_dev_task, task_steps, continue_development=True)
```

(I'm also getting errors about "maximum context length is 8192 tokens" when sending `dev_ops/ran_command.prompt` - there are _a lot_ of them)

Changes that I'd like to see:

- PO prioritises user_stories, considering pre-requisites/dependencies and possibly adding extra stories if required. 
- TechLead takes each title from `user_stories` and fleshes out the body with BDD scenarios with Given/When/Then steps. This would probably done one at a time.
- For each story:
  - start a new conversation (Including all story titles even if focusing on just one would probably help with context)
  - Developer writes unit tests for each scenario ("Then" assertions skipped/ignored)
  - Developer implements code for story
  - Developer runs tests for story
  - Developer/CodeMonkey fixes code until tests pass
  - "Can I execute the command? If yes, just press ENTER" should bail on "no" and also have other options to edit/give up on the current task.

**Comment by nalbion** [comment]
This article might be useful when designing the debugging flow

https://ntietz.com/blog/how-i-debug-2023/

**Comment by LeonOstrez** [comment]
implement_task should now focus strictly on specific task and should be able to finish it without running out of context
