### ISSUE TITLE
[Enhancement]: Add seperate prompts folders for local llm's based on token limits.

### ISSUE THREAD

**Issue by Wladastic** [Pythagora-io/gpt-pilot#841]
### Version

VisualStudio Code extension

### Suggestion

Currently all the prompts are only for GPT-4-Turbo, but using them with local llm's is currently impossible.

I would suggest adding a whole new folder structure that allows less tokens to be used or even one per architecture:
GPT,
LLama,
Mistral, ( I know its llama too but works different)
Gemma,
etc.

For each of those we can have then curated prompts or even a subfolder:
<model_arc_folder>/
- 1k/ (very experimental but would allow 1B or 3B models to work)
- 2k/ (especially gemma 2b)
 - 4k/ (llama or GPT-3.5-Turbo)
 - 8k/ (mistral 7B instruct 0.1 based or GPT-4)
 - 16k/ (Mixtral 4x7B or 8x7B)
 - 32k/ (mistral 7B instruct 0.2 based or Mixtral)
 - 64k/ (yarn mistral 7B or 13B models)
 - 128k/ (GPT-4 Turbo level)
 
 This way its easier to also add benchmarking to each level of those llm prompts and models.

**Comment by techjeylabs** [comment]
not exactly duplicate but sort of: https://github.com/Pythagora-io/gpt-pilot/issues/880
