### ISSUE TITLE
[Enhancement]: It does not appear to work with ANY open source model, and GPT-4 API is quite expensive.

### ISSUE THREAD

**Issue by phalexo** [Pythagora-io/gpt-pilot#844]
### Version

Command-line (Python) version

### Suggestion

Even with GPT-4-turbo, the process is very inefficient and ends up costing a lot of money with all the back and forth corrections.

I have tested it with multiple open source models, and none of them provide anything close to functional.

**Comment by techjeylabs** [comment]
duplicate suggestion
