### ISSUE TITLE
[Howto]: Setup .env for OpenRouter Anthropic/Claude3

### ISSUE THREAD

**Issue by Orinks** [Pythagora-io/gpt-pilot#846]
### Version

VisualStudio Code extension

### Operating System

Windows 10

### Your question

I don't think help exists for this, and the comments in the file specifically during the anthropic section confused me.

I have my OpenRouter key in but what is the Anthropic OpenRouter endpoint? I think that's what I'm missing.

Thanks.

**Comment by techjeylabs** [comment]
hey there, you might find your answers in our wiki 

https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT-Pilot-with-Anthropic-models
