### ISSUE TITLE
Cannot open an existing project I created to get assistance with gpt-pilot.[Bug]: 

### ISSUE THREAD

**Issue by CrownParkComputing** [Pythagora-io/gpt-pilot#856]
### Version

VisualStudio Code extension

### Operating System

Linux (other)

### What happened?

So your instruction for gpt-pilot says you can load an existing project you created outside of gpt-pilot. using the extension and load app it will only load exisiting gpt-pilot projects ?

**Comment by techjeylabs** [comment]
hey there, right now GPT pilot dosnt support such a feature.

**Comment by techjeylabs** [comment]
https://github.com/Pythagora-io/gpt-pilot/issues/381
