### ISSUE TITLE
[Bug]: lm studio to Pythagora There was a problem with request to openai API

### ISSUE THREAD

**Issue by baptistzaire** [Pythagora-io/gpt-pilot#869]
### Version

VisualStudio Code extension

### Operating System

Windows 10

### What happened?

**### lm studio to Pythagora** There was a problem with request to openai API:
string indices must be integers, not '![tempsnip](https://github.com/Pythagora-io/gpt-pilot/assets/87153965/cf4156f9-9b46-4878-8e60-e9f2b56933c5)tr'

**Comment by techjeylabs** [comment]
just let it run another time. There might have been a issue with the connection to the api and the request got corrupted
