### ISSUE TITLE
Does this need plus?

### ISSUE THREAD

**Issue by yangdan4** [Pythagora-io/gpt-pilot#87]
I got the insufficient funds error.

**Comment by nalbion** [comment]
get more funds

**Comment by nalbion** [comment]
...but seriously, I'm pretty sure that your Chat GPT is separate from the Open AI API. You need to set up billing here:

https://platform.openai.com/account/billing/overview

**Comment by LeonOstrez** [comment]
yeah, as @nalbion mentioned, you should check your billing. Make sure you have access to gpt-4 if you are using that model in GPT-Pilot
