### ISSUE TITLE
[Bug]: Load App

### ISSUE THREAD

**Issue by kneevil** [Pythagora-io/gpt-pilot#872]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### What happened?

I have started to create a project with Pythagora and have successfully reached the end. Now I wanted to develop the project further, but after I clicked on "Load App" only a loading symbol is displayed. 

How do I get into the old project to develop it further?

**Comment by mojtabakermani** [comment]
I'm having the same issue, using the VS code extension on Mac

**Comment by kneevil** [comment]
Update: I did fix it by creating a new app in the same folder.

**Comment by kneevil** [comment]
Colsed

**Comment by mojtabakermani** [comment]
@kneevil so you made a new app? Do you mean couldn't still upload the old app?

**Comment by kneevil** [comment]
I have started a new app. After creating the new files/folders, I canceled the program and reloaded it. Then I could also see and load the old projects.

**Comment by kneevil** [comment]
I have started a new app. After creating the new files/folders, I canceled the program and reloaded it. Then I could also see and load the old projects.
