### ISSUE TITLE
[Bug]: Pythagora stuck on "Waiting...", with console message "gpt-pilot process exited with code 255"

### ISSUE THREAD

**Issue by voxoid0** [Pythagora-io/gpt-pilot#876]
### Version

VisualStudio Code extension

### Operating System

MacOS

### What happened?

When I click "Create App", the next screen is indefinitely stuck on "Waiting..." with the progress spinner in the lower-right. When I open the developer tools, I seein the web console, "gpt-pilot process exited with code 255". 

My system python is 3.12.

**Comment by yuanfajun0912** [comment]
Me too！hoping to get an answer...

**Comment by yuanfajun0912** [comment]
I succeeded. I switched to "use the CLI tool" to install all the dependencies. Then I switched back to the vscode plug-in and it ran normally.

**Comment by mpvishal** [comment]
@yuanfajun0912 can you please explain which commands you use or how can i use CLI tool  for resolve this same issue. thank you,

**Comment by techjeylabs** [comment]
pip install -r requirements.txt  in your gpt-pilot folder, it will install the gpt-pilot dependencies on your computer

**Comment by techjeylabs** [comment]
duplicate to: https://github.com/Pythagora-io/gpt-pilot/issues/387


When setting up GPT-Pilot VSCode extension in windows, one of the steps is to create the Python virtual environment (venv).
This can fail (for as of yet unknown reason), and this is what the users see:
[image](https://private-user-images.githubusercontent.com/3362/292340111-7dbd5926-c94b-404c-b1eb-eaaef606c701.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MDAxNDYsIm5iZiI6MTcxMzU5OTg0NiwicGF0aCI6Ii8zMzYyLzI5MjM0MDExMS03ZGJkNTkyNi1jOTRiLTQwNGMtYjFlYi1lYWFlZjYwNmM3MDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjBUMDc1NzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTdiOGE0YmJkNThjOTMyNGExMTQ5ZTJjYWFmZGU2OWYzM2Y4MDYzYWZjMTk5Nzc3ZGQyNzk0NDA2YmRkMzFiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eg6ovOgVMV0NF7d6MzoeazN3zGof_STKH1Qj7IcKPzs)
Temporary workaround:
1. open command line in the gpt-pilot sub-directory of the folder which you selected for the installation of GPT Pilot (there should be requirements.txt file already there)
2. create the virtual environment with python -m venv pilot-env
3. activate the environment with pilot-env\Scripts\activate
4. install packages with pip install -r requirements.txt
5. go to the pilot subdirectory (not pilot-env, just pilot). If there is gpt-pilot file in that subdirectory delete it (that is sqlite database) and then run python db_init.py to initialize new database
After doing the above steps, the VSCode extension should start working.
