### ISSUE TITLE
[Howto]:  start use it? well , I'm stuck in waiting pages

### ISSUE THREAD

**Issue by PaperTigerL** [Pythagora-io/gpt-pilot#879]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### Your question

![屏幕截图 2024-04-14 190024](https://github.com/Pythagora-io/gpt-pilot/assets/114414011/eb12c4fa-afb1-4f38-abf0-7c5dfeab397b)
I'm stuking here for a long time, and I can't see the end of waiting.

**Comment by moha5145** [comment]
I have the same issue

**Comment by techjeylabs** [comment]
hey there, how is your enviroment looking? What python version have installed etc ?

**Comment by Thehiphippa** [comment]
I have the same issue, after completing the upgrade of the plugin in VScode

**Comment by PaperTigerL** [comment]
well, dude,&nbsp; I found maybe you should redo that, just uninstall the old one, and get it again, and my problem solved.&nbsp;&nbsp;


Epiphany
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月19日(星期五) 上午9:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Pythagora-io/gpt-pilot] [Howto]:  start use it? well , I&#39;m stuck in waiting pages (Issue #879)














 
I have the same issue, after completing the upgrade of the plugin in VScode

**Comment by techjeylabs** [comment]
issue solved

**Comment by techjeylabs** [comment]
duplicate: https://github.com/Pythagora-io/gpt-pilot/issues/387

solution:
Temporary workaround:
1. open command line in the gpt-pilot sub-directory of the folder which you selected for the installation of GPT Pilot (there should be requirements.txt file already there)
2. create the virtual environment with python -m venv pilot-env
3. activate the environment with pilot-env\Scripts\activate
4. install packages with pip install -r requirements.txt
5. go to the pilot subdirectory (not pilot-env, just pilot). If there is gpt-pilot file in that subdirectory delete it (that is sqlite database) and then run python db_init.py to initialize new database
