### ISSUE TITLE
openrouter 404 [Bug]: 

### ISSUE THREAD

**Issue by maxenergy** [Pythagora-io/gpt-pilot#883]
### Version

Command-line (Python) version

### Operating System

Ubuntu Linux

### What happened?

ENDPOINT=OPENROUTER
OPENROUTER_API_KEY="sk-or-v1-c16ba73a4xxxx"
OPENROUTER_ENDPOINT="https://openrouter.ai/api/v1/chat/completions"
MODEL_NAME=anthropic/claude-3-sonnet or MODEL_NAME=microsoft/wizardlm-2-8x22b
There was a problem with request to openai API:
API responded with status code: 404. Request token size: 23 tokens. Response text: {"error":{"message":"Model claude-3-sonnet is not available","code":404},"user_id":"user_2fAwa46HBxxxxxx"}
The request to OPENROUTER API failed with error: API responded with status code: 404. Request token size: 23 tokens. Response text: {"error":{"message":"Model claude-3-sonnet is not available","code":404},"user_id":"user_2fAwa46HBIavZhQU9M1iKnD7a6d"}. Please try again later.
Error connecting to the API. Please check your API key/endpoint and try again.

**Comment by bc-rep-project** [comment]
Openrouter 404 [Bug]: #883 - possible solutions

The bug report indicates a 404 error when using OpenRouter with specific models like anthropic/claude-3-sonnet and microsoft/wizardlm-2-8x22b. The error message "Model claude-3-sonnet is not available" suggests that the specified model might not be accessible through OpenRouter or could be experiencing temporary availability issues.

1. Verify Model Availability on OpenRouter:
Check the OpenRouter documentation or website to confirm if the models anthropic/claude-3-sonnet and microsoft/wizardlm-2-8x22b are currently supported and accessible.
OpenRouter may offer a list of available models or have specific instructions for accessing certain models.

2. Validate OpenRouter Configuration:
Double-check the OpenRouter API key and endpoint URL in the GPT Pilot configuration to ensure they are correct and up-to-date.
Any typos or outdated information might lead to connection errors.

3. Investigate Potential Access Restrictions:
Some models on OpenRouter might have access restrictions or require specific permissions.
Review your OpenRouter account or contact their support to confirm if there are any limitations on accessing the desired models.

**Comment by maxenergy** [comment]
I use command line and the sample can works,this two ways both can work.
curl https://openrouter.ai/api/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENROUTER_API_KEY" \
  -d '{
  "model": "anthropic/claude-3-haiku",
  "messages": [
    {"role": "user", "content": "What is the meaning of life?"}
  ]
}' 

import requests
import json

response = requests.post(
  url="https://openrouter.ai/api/v1/chat/completions",
  headers={
    "Authorization": f"Bearer {OPENROUTER_API_KEY}",
    "HTTP-Referer": f"{YOUR_SITE_URL}", # Optional, for including your app on openrouter.ai rankings.
    "X-Title": f"{YOUR_APP_NAME}", # Optional. Shows in rankings on openrouter.ai.
  },
  data=json.dumps({
    "model": "anthropic/claude-3-haiku", # Optional
    "messages": [
      {"role": "user", "content": "What is the meaning of life?"}
    ]
  })
)

**Comment by myoussef89** [comment]
Same here

There was a problem with request to openai API:
API responded with status code: 404. Request token size: 23 tokens. Response text: {"error":{"message":"Model gemini-pro-1.5 is not available","code":404},"user_id":"user_2dtf11X9cCB0XclzwFOE3AZCZYJ"}

**Comment by techjeylabs** [comment]
hey there, its a gemini api problem not a gpt-pilot related problem

**Comment by techjeylabs** [comment]
hey there we invite you to join our discord community to join further discussions about other LLM used with pythagora or gpt-pilot

https://discord.gg/wTR5auJB

**Comment by techjeylabs** [comment]
> having the same issue . tried with multiple models in openrouter API responded with status code: 404. Request token size: 23 tokens. Response text: {"error":{"message":"Model gemini-pro is not available","code":404},"user_id":"user_2Yz6wPA3A1qc8w1mtXloFpxkzxZ"}
> 
> API responded with status code: 404. Request token size: 23 tokens. Response text: {"error":{"message":"Model phind-codellama-34b is not available","code":404},"user_id":"user_2Yz6wPA3A1qc8w1mtXloFpxkzxZ"}

https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT%E2%80%90Pilot-with-Local-LLMs

**Comment by techjeylabs** [comment]
> ### Version
> Command-line (Python) version
> 
> ### Operating System
> Ubuntu Linux
> 
> ### What happened?
> ENDPOINT=OPENROUTER OPENROUTER_API_KEY="sk-or-v1-c16ba73a4xxxx" OPENROUTER_ENDPOINT="https://openrouter.ai/api/v1/chat/completions" MODEL_NAME=anthropic/claude-3-sonnet or MODEL_NAME=microsoft/wizardlm-2-8x22b There was a problem with request to openai API: API responded with status code: 404. Request token size: 23 tokens. Response text: {"error":{"message":"Model claude-3-sonnet is not available","code":404},"user_id":"user_2fAwa46HBxxxxxx"} The request to OPENROUTER API failed with error: API responded with status code: 404. Request token size: 23 tokens. Response text: {"error":{"message":"Model claude-3-sonnet is not available","code":404},"user_id":"user_2fAwa46HBIavZhQU9M1iKnD7a6d"}. Please try again later. Error connecting to the API. Please check your API key/endpoint and try again.

https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT-Pilot-with-Anthropic-models

**Comment by techjeylabs** [comment]
> Same here
> 
> There was a problem with request to openai API: API responded with status code: 404. Request token size: 23 tokens. Response text: {"error":{"message":"Model gemini-pro-1.5 is not available","code":404},"user_id":"user_2dtf11X9cCB0XclzwFOE3AZCZYJ"}

https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT%E2%80%90Pilot-with-Local-LLMs

**Comment by senko** [comment]
@myoussef89 @maxenergy @devninja2025 try prefixing the model name with `openai/` (ie. use `openai/anthropic/...` and see if that helps. We use provider prefixes internally and then strip the provider from the model name we pass on.

**Comment by Michal-Mikolas** [comment]
I confirm that prefixing model name (with basically anything) works. 

For example: 
`MODEL_NAME=openrouter/lynn/soliloquy-l3`
