### ISSUE TITLE
how to run on win 10

### ISSUE THREAD

**Issue by Qarqor5555555** [Pythagora-io/gpt-pilot#888]
### Version

Command-line (Python) version

### Operating System

Windows 10

### Your question

How do I run the program in Windows 10?

**Comment by techjeylabs** [comment]
hey there, i answered your question here: https://github.com/Pythagora-io/gpt-pilot/issues/890

> hey there, simply update your current vscode extension. For a Fresh installation just go to the VSCode Marketplace, you can find it here:
> 
> https://marketplace.visualstudio.com/items?itemName=PythagoraTechnologies.gpt-pilot-vs-code
> 
> Also you are invited to join our discord community:
> 
> https://discord.gg/jB94ADuT
