### ISSUE TITLE
New VS Extension 

### ISSUE THREAD

**Issue by Real-Experienes** [Pythagora-io/gpt-pilot#890]
How in the world do I get started with the latest VS Extension??😳
It just has the chat on one. Side and setup on the other. I subbed and checked advanced settings but nothing happens. Just says "installation done!".

🤷‍♂️🤷‍♂️🤷‍♂️🤷‍♂️🤷‍♂️🤷‍♂️🤷‍♂️🤷‍♂️

**Comment by techjeylabs** [comment]
hey there, simply update your current vscode extension. For a Fresh installation just go to the VSCode Marketplace, you can find it here:

https://marketplace.visualstudio.com/items?itemName=PythagoraTechnologies.gpt-pilot-vs-code


Also you are invited to join our discord community:

https://discord.gg/jB94ADuT
