### ISSUE TITLE
[Bug]: Automated workspace Deletion and Continuous Loading Loop in VSCode Extension

### ISSUE THREAD

**Issue by mariusorani** [Pythagora-io/gpt-pilot#895]
### Version

VisualStudio Code extension

### Operating System

MacOS

### What happened?

I am experiencing a critical issue with the Pythagora VC extension where attempting to load an existing high-level task results in the deletion of the entire workspace. Post this event, all files within the workspace are gone, and the extension enters a continuous loading loop, making it inaccessible.

### Steps to Reproduce
1. Open the Pythagora VC extension.
2. Attempt to load an existing app configured for a high-level task.
3. Observe that the workspace is unexpectedly deleted and all files are removed.
4. Notice that the extension then continuously attempts to reload, stuck in a loop.

### Expected Behavior
The app should load the existing workspace without deleting any files and allow for normal operation without entering a loading loop.

### Actual Behavior
The entire workspace is deleted, and the Pythagora VC extension is stuck in a continuous loading loop, preventing any access to the extension. (It took a lot of money and effort... )

### Environment
Pythagora VC extension version: Pythagora v0.1.16 / GPT Pilot v0.1.12

**Comment by LeonOstrez** [comment]
Hi @mariusorani 

I'm sorry this happened to you. I would like to see if we can restore your project and figure out what happened. It would be very helpful if you could do these few things:

- could you please explain what a "high-level task" is?
- could you please make a short video showing when extension attempts to reload, stuck in a loop?
- please, go to extension settings and click "Upload database" so that we see if it is possible to restore anything

Once again, I'm sorry this happened to you.
Leon

**Comment by mariusorani** [comment]
Hi @LeonOstrez,

Apologies for the confusion earlier. To clarify, by "high-level task," I meant that the task's progress was around 70%, following the completion of several smaller tasks.

I've recorded a quick Loom video to provide more details; I hope that's convenient for you.
https://www.loom.com/share/904910662cc646e8b45a14351347ab9a?sid=3ce6fa24-2cf5-44fb-a23d-6d1019cb9fa2

Thank you for your assistance.

**Comment by mariusorani** [comment]
#Update:

I somehow managed to recover the files and restore the workspace. I don't know how, but it seems that Pythagora stores backups of the workspace by default.

![image](https://github.com/Pythagora-io/gpt-pilot/assets/25396213/89a28f2e-3321-477d-a72a-0cc2976b60d6)

I then removed all the files inside the gpt-pilot directory, copied all the files from the backup directory, pasted them into the gpt-pilot directory, and restarted the extension. Everything started working properly, and the app loaded again.
