### ISSUE TITLE
[Howto]: avoid prompts

### ISSUE THREAD

**Issue by simsketch** [Pythagora-io/gpt-pilot#908]
### Version

Command-line (Python) version

### Operating System

MacOS

### Your question

How can I have gpt-pilot stop asking me for permission? I just want to enter the initial prompt, have it do its thing, and come back to a mostly finished codebase

**Comment by techjeylabs** [comment]
hey there, there is a setting in the advanced setting page of your pythagora plugin. Just hit the checkbox @ Allow command runs

**Comment by simsketch** [comment]
And how can i do it via command line?
