### ISSUE TITLE
[Bug]: Discord-toy-pseudso-ticketsystem is driving away potential customers

### ISSUE THREAD

**Issue by chymian** [Pythagora-io/gpt-pilot#911]
### Version

VisualStudio Code extension

### Operating System

Linux (other)

### What happened?

I wanted to topen a ticket on discord, b/c your are more resposive there then here :(

the text, which I was not able to send to you on discord!

I opened a ticket in the normal dev-wokflow, meaning on github which is not taken care of.
https://github.com/Pythagora-io/gpt-pilot/issues/905
since this (toy-)ticket-tool here not in the devops workflow, and has a tiny-matchboxsize window (really?), it's completely unusable and a real pain to use. please respond to GITHUB and stay with the established devOps workflows if you want to attract the according clientele.
Your tool looks very promising. I would love to pay you guys for the usage, if the rest of the product-environment is reliable and I can put it in my tool-box.
discord is a not a pro devops platform! it's a pain to use. and max. ok for chatting, IMHO

and speaking of it, I could not send this ticket to your play-pseudo-service and had to go to github.
what a waste of time!
Let me know when you are reachable without wasting hours on pseudo-devops-tools. 

![2024-05-06_11-26-GPT-Pilot](https://github.com/Pythagora-io/gpt-pilot/assets/1899961/513bf920-32ce-4964-bc19-101963c859aa)

**Comment by techjeylabs** [comment]
hi there, this has nothing todo with the GPT-Pilot repo, we spoke about this topic in Discord. Discord is never ment to replace Github. Issues are still beeing tracked here. this system was setup to actually channel the traffic that has been unmoderated the whole time. I am goin to close this issue since its out of scope.
