### ISSUE TITLE
[Bug]: Using the new GPT-4o as the LLM model makes Pythagora sometimes spew out and endless loop which stops the next agent from being able to do anything

### ISSUE THREAD

**Issue by MathieuDawes** [Pythagora-io/gpt-pilot#924]
### Version

VisualStudio Code extension

### Operating System

MacOS

### What happened?

When I run Pythagora using GPT-4o it produces very long json outputs and keeps repeating the code for each step over and over. Whereas when it's using gpt-4-turbo it doesn't repeat the code unnecessarily in the json instructions.

**Comment by RKonnerth-A** [comment]
I have the same Bug, or is it a feature for creating a vector knowledge base for the project ?
