### ISSUE TITLE
Project is broken atm.

### ISSUE THREAD

**Issue by Inukares** [Pythagora-io/gpt-pilot#93]
Running docker-compose results in:
```
> [ 7/10] RUN python -m venv pilot-env:
#0 0.289 Error: [Errno 2] No such file or directory: '/usr/src/app/pilot-env/bin/python'
------
failed to solve: executor failed running [/bin/sh -c python -m venv pilot-env]: exit code: 1
```

Documentation for setting it up manually also doesn't work, as there is no env example to copy

**Comment by nalbion** [comment]
https://github.com/Pythagora-io/gpt-pilot/blob/main/pilot/.env.example

**Comment by nalbion** [comment]
@Inukares  Are you running this from the `gpt-pilot` directory?

**Comment by ffesseler** [comment]
I'm having the same issue by running  'docker compose build' from the base 'gpt-pilot' directory

**Comment by nalbion** [comment]
@ffesseler `docker compose build` is working here in CI - https://github.com/Pythagora-io/gpt-pilot/actions/runs/6467905534/job/17558895933

**Comment by ffesseler** [comment]
Will do a new clone of the project this evening. I remember trying the manual install first and ended up in an error when executing ```python main.py``` then tried the docker install. I don't know if it's linked or not

**Comment by ffesseler** [comment]
Worked after doing a new git clone so I guess it came from trying to follow manual install steps first 🤨

**Comment by nalbion** [comment]
Great to hear
