### ISSUE TITLE
[Bug]: Azure Open AI Doesnt work inside config.json - Version 0.2.1

### ISSUE THREAD

**Issue by queryit-admin** [Pythagora-io/gpt-pilot#971]
### Version

Command-line (Python) version

### Operating System

Windows 11

### What happened?

I have deployed and tested Azure OpenAI Model after being ddeployed, i tried to enter the same cred inside config.json and it gives me "API check for openai failed with: Resource not found"

![image](https://github.com/Pythagora-io/gpt-pilot/assets/140688330/31bb3afa-1443-4778-88d9-fe654ebe59a5)

Code that works with deployed Azure OpenAI Model
```python
import os
from openai import AzureOpenAI

# Assuming the API key is set as an environment variable
api_key = "***********"

client = AzureOpenAI(
    api_key=api_key,
    api_version="2024-02-01",
    azure_endpoint="https://openaiqueryit.openai.azure.com"
)

completion = client.chat.completions.create(
    model="QueryIt",  # Use the deployment name as the model identifier
    messages=[
        {
            "role": "user",
            "content": "Translate the following English text to French: 'Hello, world!'",
        },
    ]
)

print(completion)

```

This is how the terminal response looks like:

![image](https://github.com/Pythagora-io/gpt-pilot/assets/140688330/8c36922a-2373-4103-a840-f622d2e46b8a)

The folder pilot now has nothing in it, assuming the latest version(0.2.1) removed the need for the files within that folder (Fyi):
![image](https://github.com/Pythagora-io/gpt-pilot/assets/140688330/3a831e21-9970-4143-a380-955fb8d6d59e)

**Comment by queryit-admin** [comment]
Code that works for deployed Azure Model

```python
import os
from openai import AzureOpenAI

# Assuming the API key is set as an environment variable
api_key = "******************"

client = AzureOpenAI(
    api_key=api_key,
    api_version="2024-02-01",
    azure_endpoint="https://openaiqueryit.openai.azure.com"
)

completion = client.chat.completions.create(
    model="QueryIt",  # Use the deployment name as the model identifier
    messages=[
        {
            "role": "user",
            "content": "Translate the following English text to French: 'Hello, world!'",
        },
    ]
)

print(completion)

```

**Comment by nikzart3** [comment]
when will this get fixed?
the update totally broke what i was doing
