### ISSUE TITLE
[Bug]: Configuring Pythagora with Together.ai API

### ISSUE THREAD

**Issue by JakeR92** [Pythagora-io/gpt-pilot#978]
### Version

VisualStudio Code extension

### Operating System

Ubuntu Linux

### What happened?

Cannot get gpt pilot to work with together.ai, getting this error:
Response text: {"error":{"message":"Unable to access model Llama-3-8b-chat-hf. Please visit https://api.together.xyz/ to see the list of supported models or contact the owner to request access.","type":"invalid_request_error","param":null,"code":"model_not_found"}}

I'm not sure if its removing the prefix from the model I add in the .env:
MODEL_NAME=meta-llama/Llama-3-8b-chat-hf

**Comment by senko** [comment]
Try prefixing the model name with `openai/`, eg `openai/meta-llama/Llama-3-8b-chat-hf`.

Also please note that we've just released version 0.2, which changes configuration format (it's now a JSON file) which allows (hopefully!) easier setup of local LLMs and even using different ones for different agents.

The extension that supports it is currently in pre-release mode and we plan to make a full update to the extension this week.

**Comment by JakeR92** [comment]
Thanks for the reply. I tried with the following configuration:
ENDPOINT=TOGETHERAI
TOGETHER_API_KEY=<My Key>
MODEL_NAME=meta-llama/Meta-Llama-3-70B

Which gets the following error:
API responded with status code: 404. Request token size: 23 tokens. Response text: {
    "error": {
        "message": "The model `Meta-Llama-3-70B` does not exist or you do not have access to it.",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}


When i try:
MODEL_NAME=openai/meta-llama/Meta-Llama-3-70B

I get this error:
API responded with status code: 400. Request token size: 23 tokens. Response text: {
    "error": {
        "message": "invalid model ID",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}
